### ISSUE TITLE
Mind to take care about the security of polymer-cli users?

### ISSUE THREAD

**Issue by limonte** [Polymer/polymer-cli#1034]
There are 3 high-severity and 3 medium-severity security issues: https://snyk.io/test/npm/polymer-cli

![image](https://user-images.githubusercontent.com/6059356/48935264-bd0b9180-ef0f-11e8-9924-d709d698b75a.png)

Would be nice if suspicious dependencies will be removed/upgraded.

**Comment by TimvdLippe** [comment]
Duplicate of https://github.com/Polymer/tools/issues/428
