### ISSUE TITLE
show status info and hide bower install output during polymer init

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/polymer-cli#120]
After init'ing an element project, Polymer CLI installs all the Bower dependencies. One, I think Polymer CLI should give a status update saying `Installing dependencies via Bower...`. Two, I think the Bower output itself should be hidden. The user can choose to view it by specifying a `--verbose` flag (or, during the init process, Polymer CLI can ask `View verbose output while Polymer CLI initializes the project? Y/ N`). It's just TMI and makes the Polymer CLI experience less clean.

**Comment by abdonrd** [comment]
I'm agree! :)

**Comment by justinfagnani** [comment]
We're adding a bunch of logging to all the commands today. @FredKSchott is going to add a prompt for bower install. Hopefully we can suppress Bower's output as well.

**Comment by FredKSchott** [comment]
To your first point, it actually currently does log that. It just gets immediately pushed off the screen by all the bower install output :)

To your second, bower doesn't support a cleaner progress bar like npm does. As far as I can see our choice is between the current output or nothing at all (via `--quiet`). The current output is definitely noisy, but it an error occurs its helpful to be able to see what went wrong. In quiet mode, that's not possible to the same degree. Choosing between those, I think we're stuck with the logs for now.

FWIW, yeoman is opinionated in its support of this output. By default, yeoman will output the following on `installDependencies()` and with no option to silence the bower output: 

```
I'm all done. Running npm install & bower install for you to install the required dependencies. If this fails, try running the command yourself.
```

**Comment by addyosmani** [comment]
Some CLIs also expose the opposite of a `--quiet` (i.e default to quiet and expose `--verbose` for those that want more detailed logging information). Imo, it's better to output the full log because beginners are especially prone to not discovering detailed logs until it's pointed out to them.

**Comment by justinfagnani** [comment]
For `--quite` I'd like to literally log nothing to the console, for tests and use by other shell tools. The default level should log plenty of information. `--verbose` will be really a lot.
