### ISSUE TITLE
Document project structure

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-cli#13]
This is important for other tools that want to be compatible with polytool projects.

**Comment by justinfagnani** [comment]
@kaycebasques can I assign this to you, and/or is it a duplicate of #44? Where should this documentation live?

**Comment by kaycebasques** [comment]
@justinfagnani sure, assign it to me. We can mention it in both the README and the Polymer CLI doc.

**Comment by justinfagnani** [comment]
Ugh, can't assign... <runs off to settings>

**Comment by justinfagnani** [comment]
Final action item wrt to this issue is to add basic app structure docs to the readme.

**Comment by FredKSchott** [comment]
@justinfagnani was this closed by https://github.com/Polymer/polymer-cli/pull/159?

**Comment by justinfagnani** [comment]
Yep
