### ISSUE TITLE
lint async files

### ISSUE THREAD

**Issue by garlicnation** [Polymer/polymer-cli#139]
- [ ] hydrolysis.Analyzer.analyze takes an `additionalImports` argument
- [ ] polylint pipes through `additionalImports`
- [ ] polymer-cli sets `additionalImports` based on config file

**Comment by stramel** [comment]
@justinfagnani @usergenic @FredKSchott I know the lazy-imports is just getting tagged now, just wanted to see if this is still relevant or not. It hasn't been reviewed in about a year.

**Comment by justinfagnani** [comment]
Thanks @stramel this has been taken care of my lazy-imports support.
