### ISSUE TITLE
sw-precache

### ISSUE THREAD

**Issue by gauntface** [Polymer/polymer-cli#15]
cc @robdodson 

## Some notes on sw-precache as requested
- It's a step that realistically has to happen at the end of a set of changes as it scans for files in a build location and creates a Service worker to cache those assets
- Run time cache is possible through a set of regex for urls and caching mechanisms
- During development you can pass in a variable to prevent sw-precache for handling any of the network requests.
- Something that may be useful to Polytool, depending on how you hook everything up, is that it can take a list of templates / separate files that contribute to making a single file and manage the cache accordingly (i.e. a vulcanized component of CSS, JS and HTML to a flattened HTML file).

## Things to be aware of
- It does some fairly unusual things with regards to cache management (every file is given it's own cache). Its not a problem, but may catch some developers out if they look at the final output.
- Developers can't easily alter the final service worker to include additional functionality. If they wanted to add push or bg sync, it requires some working around or with sw-precache.

Beyond that, the only code the developer needs to include in their page is a one line snippet to register the sw file sw-precache outputs.

**Comment by justinfagnani** [comment]
@gauntface Does the scanning need to happen against the filesystem, or could we hook it into a gulp stream? I've set up vulcanize so that it can read from a stream, and it'd be nice to plug this into the pipeline post-vulcanize.

**Comment by gauntface** [comment]
@justinfagnani It's reads directly from the filesystem based on paths / globs you give it.

**Comment by justinfagnani** [comment]
Fixed by #48 #49 etc.
