### ISSUE TITLE
Hooks for image optimization, copy, and ES2015

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer-cli#153]
There are a handful of things I'd like to do to get PSK to play nice with the CLI. These include image opt, copying static files (fonts, json files, etc), and ideally a hook to transform JS but that can come later.

@justinfagnani asked I open an issue to discuss

**Comment by FredKSchott** [comment]
Now supported by [polymer-build](https://github.com/Polymer/polymer-build)! 🎉
