### ISSUE TITLE
Feature request: autogenerate Web App Manifest

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer-cli#166]
_As a Polymer CLI user,
when I use `polymer init` to start a new app,
I want the Polymer CLI to generate a [Web App Manifest](https://www.w3.org/TR/appmanifest/),
so that the default scaffolds are one step closer to a true PWA._

Polymer CLI already has a lot of the information necessary to generate a Web App Manifest. It would be really cool if I got one for free when I ran `polymer init`, and if it were already included in the generated `index.html`.

**Comment by justinfagnani** [comment]
I'm going to implement this for now as just a file in the application template. Given the number of options available though, though could be a rally good target for the fabled `polymer gen` command, which generates files into the existing source directory.
