### ISSUE TITLE
polymer init: arrow keys are not showing up when clicked "up" or "down"

### ISSUE THREAD

**Issue by oneezy** [Polymer/polymer-cli#168]
Arrow keys are not showing up when clicked "up" or "down"

`git version 2.7.0.windows.1`

![image](https://cloud.githubusercontent.com/assets/7369575/15383962/a410c74a-1d5c-11e6-8a87-9764c58c25a5.png)

**Comment by justinfagnani** [comment]
This is the second report of key problems in Windows. @oneezy what version of Windows are you on?

**Comment by justinfagnani** [comment]
@addyosmani any reports of problems on the Yeoman side?

**Comment by oneezy** [comment]
I'm on Windows 10. 

Important to note, this is purely visual (as in not seeing the arrow move up/ down). When pressing up or down and hitting enter, it will select the correct template.

**Comment by azakus** [comment]
The issue here is `git bash`. Both `cmd.exe` and `powershell` work with arrows.

**Comment by azakus** [comment]
Upstream issue https://github.com/yeoman/yo/issues/424

**Comment by azakus** [comment]
Looks like the base issue is fixed with node v6.2.0: https://github.com/nodejs/node/issues/5384#issuecomment-219984590

**Comment by azakus** [comment]
Hmm, well it doesn't look fixed to me with 6.2 in git bash / mingw

**Comment by justinfagnani** [comment]
@azakus note at this point we're calling inquirer directly, so https://github.com/SBoudrias/Inquirer.js/issues/266 is the most direct upstream issue, I think.

**Comment by oneezy** [comment]
Ahh, I see... I'm using Node 4.2.2 (I think). 

I've got NVM installed though..will test this out on 6.2.0 when I get back to the desk

**Comment by oneezy** [comment]
Err.. spoke to soon.

**Comment by azakus** [comment]
@justinfagnani https://github.com/SBoudrias/Inquirer.js/issues/303#issuecomment-215501433 suggests a workaround is possible if we call inquirer

**Comment by FredKSchott** [comment]
This fix has been pushed to npm within v0.8.0 https://www.npmjs.com/package/polymer-cli
