### ISSUE TITLE
`serve` should open default browser

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer-cli#18]
Browsersync (which PSK1 uses) has this awesome feature when you run the local server it also opens the default browser and populates the URL. https://www.browsersync.io/docs/options/#option-open

I would loooooooove if polytool serve did this so i didn't have to copy/paste from terminal

**Comment by abdonrd** [comment]
I would love too! 😁 

PS: The `polyserve` already has the `-o` option.

**Comment by robdodson** [comment]
I see. I tried `polytool serve -o` but that didn't open the browser so maybe the argument isn't being passed. Either way I'd love if it were the default

**Comment by abdonrd** [comment]
Totally! :)

**Comment by FredKSchott** [comment]
Just dug into this a bit, `-o` needs an argument to work.

So `polytool serve --open "index.html"` is equivalent to `polyserve -o`

**Comment by FredKSchott** [comment]
Ah, it actually depends on your version of polyserve. Newer versions won't do anything unless you specify the path.

So: `polytool serve --open "index.html"` =  `polyserve --open "index.html"` (for version > 0.8) =  `polyserve --open` (for version < 0.8)

**Comment by justinfagnani** [comment]
Fixed in polyserve.

**Comment by robdodson** [comment]
I'm probably doing it wrong but this seems to be opening the wrong thing.

`polymer serve -o` will open `http://localhost:8080/components/polymer-starter-kit/` but I'm not building an element I'm building an app so I'd like it to open `http://localhost:8080`

I tried `polymer serve --open "index.html"` but that threw an error:

```
Starting Polyserve...
    serving on port: 8080
    from root: /Users/[path-to-my-project]/polymer-starter-kit/index.html

Error reading config at /Users/[path-to-my-project]/polymer-starter-kit/bower.json
{ Error: ENOTDIR: not a directory, open '/Users/[path-to-my-project]/polymer-starter-kit/index.html/bower.json'
