### ISSUE TITLE
app-drawer-template sample does not show up in Safari Version 9.1.1 (11601.6.17)

### ISSUE THREAD

**Issue by duk** [Polymer/polymer-cli#183]
Followed steps on https://www.polymer-project.org/1.0/start/toolbox/set-up.
When "polymer serve --open" on Safari Version 9.1.1 (11601.6.17), the page only show "My App."

Developer tool shows
localhost:39TypeError: null is not an object (evaluating 'document.body.appendChild')

**Comment by duk** [comment]
See the same issue on latest Firefox build

**Comment by justinfagnani** [comment]
@kevinpschaaf seems like an issue in the template. Should I move the issue?

**Comment by duk** [comment]
`// load webcomponents polyfills
    (function() {
      if ('registerElement' in document
          && 'import' in document.createElement('link')
          && 'content' in document.createElement('template')) {
        // browser has web components
      } else {
        // polyfill web components
        var e = document.createElement('script');
        
        e.src = '/bower_components/webcomponentsjs/webcomponents-lite.min.js';
        
        window.onload = function() {
          document.body.appendChild(e);
        }
      }
    })();` fixed the issue for me.

**Comment by vaadin-marcus** [comment]
I didn't want to wait for the document to load before loading the polyfill, so I ended up changing `document.body.appendChild(e);` to `document.head.appendChild(e);` – seems to work fine in both FF and Safari

**Comment by justinfagnani** [comment]
This was fixed upstream in https://github.com/Polymer/app-drawer-template/pull/3
