### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by leesander1** [Polymer/polymer-cli#184]
Following along with the Codelab tutorials having difficulties getting my project to build properly for firebase deployment. I am using windows 10. Seems to be an issue with the the build failing.

C:\Users\leesa\Downloads\app>polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to uglify file C:\Users\leesa\Downloads\app\bower_components\app-storage\app-indexeddb-mirror/app-indexeddb-mirror.html_script_0.js
warn:    Unable to uglify file C:\Users\leesa\Downloads\app\bower_components\web-component-tester\data/index.html_script_0.js
warn:    Unable to uglify file C:\Users\leesa\Downloads\app\bower_components\web-component-tester\data/index.html_script_2.js

**Comment by iblancasa** [comment]
If you go to "build" folder, you will have your files (I think).

I got this warnings too (ArchLinux with Node v4)

**Comment by JGSolutions** [comment]
I tried polymer build and i get this error

error { [Error: Cannot find module 'gulp'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'gulp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jerrygag/Desktop/gulpfile.js:13:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by leesander1** [comment]
this was a duplicate issue #178 that was fixed with #188 followed the fix by @tennosys with a few minor exceptions with gulp  complaining about the " so I changed them to ' then I just built the polymer-cli and it successfully built.

src/build/analyzer.ts line 83
`this.files.set(path.join('', file.path), file);`

src/build/uglify-transform.ts line 28
`file.path = path.join('', file.path);`

**Comment by tennosys** [comment]
Oh I see why my build is failing, thanks @leesander1

**Comment by JGSolutions** [comment]
Ok thanks @leesander1. I will keep track of this discussion.
