### ISSUE TITLE
polymer init application missing name?

### ISSUE THREAD

**Issue by Alos** [Polymer/polymer-cli#186]
Just installed the polymer-cli on OS X. After that I tried creating an application using:

 `polymer init application`

I get the following:

```
info:    Running template application
error { [AssertionError: A name parameter is required to create a storage]
  name: 'AssertionError',
  actual: '',
  expected: true,
  operator: '==',
  message: 'A name parameter is required to create a storage',
  generatedMessage: false }
AssertionError: A name parameter is required to create a storage
    at new Storage (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/util/storage.js:24:3)
    at ApplicationGenerator.Base._getStorage (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/base.js:665:10)
    at ApplicationGenerator.Base (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/base.js:157:22)
    at ApplicationGenerator (/usr/local/lib/node_modules/polymer-cli/lib/init/application/application.js:15:14)
    at Environment.instantiate (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:328:10)
    at Environment.create (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:305:15)
    at Environment.run (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:364:24)
    at runGenerator (/usr/local/lib/node_modules/polymer-cli/lib/commands/init.js:65:29)
    at /usr/local/lib/node_modules/polymer-cli/lib/commands/init.js:80:21
    at Environment.resolver.lookup (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/resolver.js:50:12)
```

I was expecting polymer-cli to ask for the project name or use the directory name as the default. While installing polymer-cli there where some warnings not sure they are related or not:

```
$ sudo npm install -g polymer-cli
Password:
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

Updating lodash and trying to install polymer-cli again. Will report back!

**Comment by Alos** [comment]
Updated other libs and tried with other template options (app-drawer-template, elements) with the same results. Runing nodejs v4.2.2

**Comment by Alos** [comment]
Turning on verbose mode shows that the config read appears ok:

```
debug:   config read 
{ root: '/Users/myuser/Desktop/myapp',
  entrypoint: '/Users/myuser/Desktop/myapp/index.html',
  fragments: [],
  inputs: [ '/Users/myuser/Desktop/myapp/index.html' ] }
```

**Comment by FredKSchott** [comment]
Hmm, I can't reproduce. A quick google-search brings up this issue and related fixes https://github.com/yeoman/generator-angular/issues/1099. 

Do you see any prompts / questions when you run `polymer init`? If so, at what stage does the tool crash (during questions, after questions, during bower install, etc)?

**Comment by sbesh91** [comment]
I've got a similar error with upon running polymer init app-drawer-template.

info:    Running template app-drawer-template
error:   Promise rejection: AssertionError: A name parameter is required to create a storage
error:   AssertionError: A name parameter is required to create a storage
    at new Storage (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/util/storage.js:24:3)
    at GithubGenerator.Base._getStorage (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/base.js:665:10)
    at GithubGenerator.Base (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/base.js:157:22)
    at GithubGenerator (/usr/local/lib/node_modules/polymer-cli/lib/init/github.js:22:18)
    at Environment.instantiate (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:328:10)
    at Environment.create (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:305:15)
    at Environment.run (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:364:24)
    at runGenerator (/usr/local/lib/node_modules/polymer-cli/lib/commands/init.js:65:29)
    at /usr/local/lib/node_modules/polymer-cli/lib/commands/init.js:131:25

**Comment by Alos** [comment]
So I get the error after I pick the type of template or right away if I run it as @sbesh91 here is how it looks like with -v on:

```
$ polymer init -v
debug:   got args: 
{ args: [ 'init', '-v' ] }
debug:   adding command build
debug:   adding command help
debug:   adding command init
debug:   adding command lint
debug:   adding command serve
debug:   adding command test
debug:   running...
debug:   command parsed 
{ name: 'init',
  options: { _all: { verbose: true }, global: { verbose: true } } }
debug:   config read 
{ root: '/Users/myuser/Desktop/submie2',
  entrypoint: '/Users/myuser/Desktop/submie2/index.html',
  fragments: [],
  inputs: [ '/Users/myuser/Desktop/submie2/index.html' ] }
debug:   Running command...
debug:   creating yeoman environment...
? Which starter template would you like to use? app-drawer-template
info:    Running template app-drawer-template
debug:   Running generator polymer-init-app-drawer-template:app
error:   Promise rejection: AssertionError: A name parameter is required to create a storage
error:   AssertionError: A name parameter is required to create a storage
    at new Storage (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/util/storage.js:24:3)
    at GithubGenerator.Base._getStorage (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/base.js:665:10)
    at GithubGenerator.Base (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/base.js:157:22)
    at GithubGenerator (/usr/local/lib/node_modules/polymer-cli/lib/init/github.js:22:18)
    at Environment.instantiate (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:328:10)
    at Environment.create (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:305:15)
    at Environment.run (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:364:24)
    at runGenerator (/usr/local/lib/node_modules/polymer-cli/lib/commands/init.js:65:29)
    at /usr/local/lib/node_modules/polymer-cli/lib/commands/init.js:131:25
```

**Comment by carltondickson** [comment]
Try running it in an empty directory and it works for 4.4.4 and 6.2.0

```bash
mkdir myapp && cd myapp
polymer init --name=application
```

It was broken for me, I was running it inside of an existing Laravel project which I'm guessing breaks things...could it be a package.json file causing some issues?

As a test I dropped the package.json from my Laravel project into an empty directory and it causes the problem again. 

```json
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "laravel-elixir": "^5.0.0",
    "bootstrap-sass": "^3.3.0"
  }
}
```

**Comment by carltondickson** [comment]
Should probably add that this works for the application template but didn't seem to work for app-drawer-template

```
carlton@carlton-ubuntu-16-04:~/myapp3$ polymer init --name=app-drawer-template
info:    Running template app-drawer-template
info:    Downloading latest release of Polymer/app-drawer-template

I'm all done. Running bower install for you to install the required dependencies. If this fails, try running the command yourself.

bower ENOENT        No bower.json present
```

**Comment by normmcgarry** [comment]
I'm getting the same issue on Windows 10 when trying to generate an element. Confirm that running the CLI in a folder outside of the main project works fine, but errors when inside a project.

**Comment by Alos** [comment]
@carltondickson thanks for the suggestions, this did not work. I was working on an empty directory anyways. passing the --name=application also does not help. 

Using Node v4.2.2

**Comment by Alos** [comment]
Update to Node v6.2.0 did not help :(

**Comment by Alos** [comment]
When you install polymer-cli does it also install a generator in yoman?

**Comment by Alos** [comment]
I think the issue is calling the generator by name. I can run the generator called generator-polymer-init using yoman directly but not when the init.js calls it :hushed:

**Comment by Alos** [comment]
Ok guys! Upon further investigation, the **options** object passed to the GtihubGenerator constructor looks like this:

```
options: %0 { env: 
   Environment {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     arguments: [],
     options: {},
     adapter: TerminalAdapter { promptModule: [Object] },
     cwd: '/Users/alos/Desktop/submie2',
     store: Store { _generators: [Object], _meta: [Object] },
     runLoop: Queue { queueNames: [Object], __queues__: [Object], _maxListeners: 0 },
     sharedFs: EventEmitter { domain: null, _events: {}, _eventsCount: 0, _maxListeners: 0 },
     lookups: [ '.', 'generators', 'lib/generators' ],
     aliases: [ [Object] ] },
  resolved: 'unknown',
  namespace: 'polymer-init-app-drawer-template:app' }
```
Please notice the **resolved** property is 'unknown'.

The constructor calls its parents constructor like this:

```
return class GithubGenerator extends yeoman_generator_1.Base {
        constructor(args, options) {
            console.log('options: %0', options);
            super(args, options);
```

Then if you look at the original error, the issue happens at line 667 of the base.js:

```
/**
 * Return a storage instance.
 * @return {Storage} Generator storage
 * @private
 */

Base.prototype._getStorage = function () {
  var storePath = path.join(this.destinationRoot(), '.yo-rc.json');
  console.log('rootGeneratorName' + this.rootGeneratorName());
  return new Storage(this.rootGeneratorName(), this.fs, storePath);
};
```
The problem is the rootGeneratorName() method that looks like this:
```

/**
 * Determine the root generator name (the one who's extending Base).
 * @return {String} The name of the root generator
 */

Base.prototype.rootGeneratorName = function () {
  var pkg = readPkgUp.sync({cwd: this.resolved}).pkg;
  return pkg ? pkg.name : '*';
};
```

**Comment by Alos** [comment]
On the [yeoman documentation](http://yeoman.io/authoring/integrating-yeoman.html) I see that:

> Note: Generators registered using #registerStub() will have "unknown" as resolved value.

Help?

**Comment by justinfagnani** [comment]
@Alos I'll try to reproduce this today

**Comment by Alos** [comment]
@justinfagnani thanks! Let me know if you want me to try something in my machine

**Comment by HenriTEL** [comment]
When I initialize an element using `polymer init` from my Polymer Starter Kit clone i get the `A name parameter is required to create a storage` error.
But when I initialize it from the outside everything is going well.

**Comment by jordyvandomselaar** [comment]
Has anyone come to a solution? I need this to work :(

**Comment by justinfagnani** [comment]
Looking more closely at the `resolved` option to generators, it's `"unknown"` in both the case where a package.json has a name and where it doesn't. So I don't think that's the issue. This is looking more like a bug in Yeoman to me.

**Comment by justinfagnani** [comment]
Oh, I forgot I had fixed this in the `GithubGenerator` a long while back, but just not in `ApplicationGenerator` or `ElementGenerator`. Fix coming soon.

**Comment by bicknellr** [comment]
https://github.com/Polymer/tools/pull/115 adds a Polymer 3.x element template - I don't think it's in any type of release yet.
https://github.com/Polymer/tools/pull/134 will add the (very minimal) Polymer 3.x application template.
