### ISSUE TITLE
Deprecated dependencies warning on npm install

### ISSUE THREAD

**Issue by LostInBrittany** [Polymer/polymer-cli#190]
Hi all!

While doing a npm install de polymer-cli, I got warnings about deprecated versions of `cross-spawn-async`, `graceful-fs`, `lodash` and `jade`:

```
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

```

For info, I'm using npm 3.4.1 and node v4.2.2 manually installed on a  Ubuntu linux 16.04 (not de deb package).

They are all dependencies of other dependencies, so it could be not very easy to fix it. I'll try to modify the dependencies, test if it works and make a PR, if I'm able to find versions

**Comment by abdonrd** [comment]
Reference: https://github.com/Polymer/polymer-cli/issues/64

**Comment by LostInBrittany** [comment]
Some more info:

The `jade` dependency problem comes from `gulp-mocha:2.2.0`, on its `mocha` dependency. 

```
├─┬ gulp-mocha@2.2.0 
│ ├─┬ mocha@2.5.1 
│ │ ├─┬ jade@0.26.3 
```

No easy solution for it, as the last version of `mocha` depends on `jade`. The issue is known there: https://github.com/mochajs/mocha/issues/2200 It won't be corrected before next major version of `mocha`.

The `cross-spawn-async` dependency comes from `yeoman-generator:0.23.0`

```
├─┬ yeoman-generator@0.23.3 
│ ├─┬ cross-spawn@2.2.3 
│ │ ├─┬ cross-spawn-async@2.2.4 
```

I've posted an issue over there: https://github.com/yeoman/generator/issues/934

Looking for the other warning later...

**Comment by LostInBrittany** [comment]
@abdonrd thanks! I didn't find your issue before, sorry

**Comment by LostInBrittany** [comment]
For info, the `cross-spawn-async` dependency that came from `yeoman-generator` won't be a problem soon, I've done an [PR over there](https://github.com/yeoman/generator/issues/934), and it has been accepted, so the problem will disappear in next version of `yeoman-generator`

**Comment by mustafa-zaman** [comment]
I am having same issue. Just wondering what is the way around. FYI: I am new at Ubuntu.
