### ISSUE TITLE
Windows polymer serve build/bundled ERRORS

### ISSUE THREAD

**Issue by kilombo** [Polymer/polymer-cli#191]
When i execute **polymer serve build/bundled** i have these errors:
**index.html_script_0.js:1 Uncaught SyntaxError: Unexpected token <**

![screenshot-localhost 8080 2016-05-22 19-37-52](https://cloud.githubusercontent.com/assets/3757913/15455442/cc6c4d0e-2054-11e6-90f6-119698d4e5a3.png)

**Comment by leesander1** [comment]
A syntax error of some sort maybe missing a comma `,` or a colon`;`  somewhere.

**Comment by kilombo** [comment]
Thanks for your reply @leesander1 but this is directly downloaded without modifications. I want to bundle and test it from Firebase hosting.

I dont't know where is the error.

**Comment by leesander1** [comment]
which project template are you working with and on what operating system?

**Comment by kilombo** [comment]
OS: Windows 10
Node version: v.5.1.0

Project: git clone https://github.com/Polymer/shop.git

**Comment by leesander1** [comment]
@kilombo I was unable to replicate your issue. Did you receive any errors on build?

**Comment by kilombo** [comment]
@leesander1 no errors on build:

![polymer-build](https://cloud.githubusercontent.com/assets/3757913/15479112/dafe59a0-211e-11e6-9c77-3ae17ff4f4ae.png)

**Comment by leesander1** [comment]
ah this is a polymer-cli build issue on windows. I had a similar experience and ended up compiling the tool with a fix #188 please check out #184

**Comment by kilombo** [comment]
Sorry @leesander1 but on src/build/analyzer.ts line 83 i have:
`this.files.set(file.path, file);`

and on src/build/uglify-transform.ts line 28
`let contents = file.contents.toString();`

**Comment by leesander1** [comment]
@kilombo yes the current branch has yet to be updated for this fix. To fix this you will have to make the changes yourself and compile using the instructions in the README. 
On src/build/analyzer.ts line 83: 
you will be replacing `this.files.set(file.path, file);` with 'this.files.set(path.join('', file.path), file);'

On src/build/analyzer.ts line 254: 
You will need to insert 'filepath = path.join(path.parse(this.analyzer.root).root, filepath)'  afer 'if (filepath) {'

On src/build/uglify-transform.ts line 15:
Insert 'import * as path from 'path';'

On src/build/uglify-transform.ts line 26:
Insert 'file.path = path.join("", file.path);'  before 'if (file.contents && file.path.endsWith('.js')) {'

**Comment by jwayong** [comment]
BashOnWindows (Ubuntu) with Windows 10 Insider Preview build 14352 will work :)

**Comment by kilombo** [comment]
Sorry @leesander1 i made your changes and the same result.
I restarted Windows.

**Comment by Stefdv** [comment]
Any idea when this fix will be officially released?

**Comment by jwuliger** [comment]
No issues here. Strange. I am running Win 10 Ent. Insider Build 14352, Node 6.2, NPM 3.9.6 and CMD as Admin. It built and served with no issues. I hope that helps in some way.

**Comment by jay8t6** [comment]
happening to me on a mac too.. when will this be released?

**Comment by FredKSchott** [comment]
This should be fixed as of the latest version, v0.13.0!

Please update and try again, and create a new issue if this issue is still affecting your system/application.
