### ISSUE TITLE
polymer build doesn't appear to work correctly.

### ISSUE THREAD

**Issue by Stormsys** [Polymer/polymer-cli#202]
There appears to be some odd behaviour on windows 10 x64 using the polymer-cli build feature.

Steps to reproduce:

> npm install -g polymer-cli
> checkout shop-master from Polymer/shop
> polymer build

> shop-master>polymer build
> info:    Building application...
> info:    Generating build/unbundled...
> info:    Generating build/bundled...
> warn:    Unable to uglify file shop-master\bower_components\web-component-tester\data/index.html_script_0.js
> warn:    Unable to uglify file shop-master\bower_components\web-component-tester\data/index.html_script_2.js
> info:    No file found for shop-master\{Users\x\location\}\shop-master\src\shop-app.html
> info:    No file found for shop-master\{Users\x\location\}\shop-master\src\shop-list.html
> info:    No file found for shop-master\{Users\x\location\}\shop-master\src\shop-detail.html
> info:    No file found for shop-master\{Users\x\location\}\shop-master\src\shop-cart.html
> info:    No file found for shop-master\{Users\x\location\}\shop-master\src\shop-checkout.html
> info:    No file found for shop-master\{Users\x\location\}\shop-master\src\lazy-resources.html

a few things that i can note about the build output:

Index.html contains the following script tag, but no file exists.

> `<script src="index.html_script_0.js"></script>`

In bunbled/index.html the file contains the following link, which i believe is just for HTTP/2, note that neither folders actually contain manifest.json
> `<link rel="manifest" href="/manifest.json">`

most components, eg shop-chart.html contain a script import but no scripts exist.
> `<script src="shop-cart.html_script_0.js"></script>`

**Comment by tennosys** [comment]
U can apply fix here #199 
or you can use my fix here #188

**Comment by FredKSchott** [comment]
This has been fixed on master. A new version will be released with this fix to npm soon.
