### ISSUE TITLE
consider not doing `bower install` as part of `polymer init`

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer-cli#218]
I want to `git init` the initial set of files for my app, but files installed with bower shouldn't be included so I need to do `rm -rf bower_components` befor `git init && git add *` and then do `bower install` again.

It seems a little pointless to do it as part of `polymer init`.

IMO, it should be something like this :
1. polymer init # after this I can do whatever I want with git/etc
2. polymer build # this does bower install
3. polymer serve

**Comment by ncrawlins** [comment]
I want to be able to serve without having to build.  I don't want bower install running every time I build.

you are going to have to create a .gitignore file regardless?  why not do that first and add bower_components to it before you initialize git?  seems like you're making everyone who uses the cli have to to do an extra command and an unnecessary build to get started developing just to fit your particular git workflow where you combine init with add *

**Comment by davidmaxwaterman** [comment]
Yes, I agree that having it in the build is perhaps sub-optimal, but imo it should be a separate build - after all, it *is* actually a *build* step, not an 'init' step.

I don't like having things like bower_components in .gitignore because it hides the files (duh) and I want to actually see what is there in my git status.

Yes, I think it *should* be an extra command and you're right in that is what I am asking. IMO, it is a bug to combine a build step in the init. I think the work flow is very common (the most common?). 1. npm install, 2. bower install, 3. grunt/gulp/etc.

I agree that it isn't a build step you need to run every time.

But, hey...it's just a minor annoyance for an experienced developer, and makes it easier for the beginner, so perhaps that's the point - in which case, fair enough.

**Comment by justinfagnani** [comment]
I don't think we should `bower install` on build, installation is a separate distinct step that can sometimes change how your app behaves. It's also not always possible to go back to the previous state after installation.

I think there are two things here: 1) we could prompt for `bower install`. This doesn't seem to be the norm for Yeoman generators, but we can put in a prompt around the call ourselves. 2) We can produce a `.gitignore` in `init` that ignores `bower_components/`, `node_modules/` and other fun folders.

**Comment by ncrawlins** [comment]
oh, so you still want to commit the bower_components folder, but not on the initial commit? what is the reasoning for that?

Regardless, in my mind, installing bower dependencies isn't a build step it's an initialization step and in the *vast* majority of cases, if you took it out the polymer init, it would just end up being the very next thing people did.  maybe just add an optional flag to the init that skips the install rather than prompting every time.  `polymer init --noinstall` or whatever and setting that would skip the bower install.

**Comment by davidmaxwaterman** [comment]
Yeah, I agree that I shouldn't have called it a 'build step' because it isn't really something done every time you build - ie not 'polymer build' (unless it can avoid doing it if it's already done, like make can).

I suppose I was thinking that 'polymer' was more like 'yoeman' in that it would just give your the directory structure and basic files...however, I notice that it installs a whole load of stuff I don't need - loads of icon, paper, ...all sorts. Those are PolymerElements, not Polymer...and I selected the `Which starter template would you like to use? application` which I presumed was a mostly empty template...I will have to remove  almost all of that, and add `platinum-sw` - which is actually the only PolymerElement my app uses (so far). I had assumed that platinum-sw would be in there and am bemused that it isn't.

**Comment by ncrawlins** [comment]
that just sounds like you have issues with the template choices more than with the init process.

**Comment by davidmaxwaterman** [comment]
> oh, so you still want to commit the bower_components folder, but not on the initial commit? what is the reasoning for that?

No, I don't want to *commit* bower_components...that is a directory needed for building the app, and should be generated (perhaps that's a better word to use than 'build step').

However, I don't want `bower install` run for me when I start a blank project...how can it possibly know. Maybe for one of the other 'polymer init' options where you're actually asking for a more 'full' project, but I asked for a 'blank' one...I forget the words now.

Yes, you might be right about the choices the `polymer init` command is making the template I selected....the wording is 'a blank application template'....didn't expect *any* bower_components/ (ie didn't expect `bower install` to be run)...I don't mind it creating a bower.json file, but with perhaps only polymer.html and webcomponents.js in it; and what I got is a whole chunk of bower_components that I have no intention of using (though that might change).

**Comment by ncrawlins** [comment]
> No, I don't want to commit bower_components...that is a directory needed for building the app, and should be generated (perhaps that's a better word to use than 'build step').

Again, if you don't want to commit it to git, then you are going to have to add it to your .gitignore at some point, just do that before you do your init. or as @justinfagnani mentioned, maybe the templates should include a basic .gitignore file to ignore the bower and build folders.

**Comment by davidmaxwaterman** [comment]
Anyway, like I said in the summary, all I wanted in this issue is for the authors to *consider* not doing `bower install` in the `polymer init`.

I think perhaps it would be fine to only not do it in the *blank* template, but really I just wanted to express my surprise (as a somewhat seasoned html5 app developer) that it had this behaviour and for them to *consider* changing it.

So, it has been considered and I'll leave it up to other people to decide if they do anything about it, or not.

**Comment by davidmaxwaterman** [comment]
> Again, if you don't want to commit it to git, then you are going to have to add it to your .gitignore at some point, just do that before you do your init. or as @justinfagnani mentioned, maybe the templates should include a basic .gitignore file to ignore the bower and build folders.

That's not correct. I don't add it to my .gitignore and I don't want to commit it. I do a `git add` for things I want to commit, and I would never do that for `bower_components/`. I still want to see them listed in the 'untracked files' section in `git status`.
If a .gitignore file is added that includes `bower_components/` or `node_mobules/` for that matter, then I am sure to promptly remove them. I've never seen the point in the .gitignore file, tbh...perhaps I need to look at it again, but I like to do a `git clean -dfx` to clean out the repo when I see there is build stuff there in 'untracked files' part of the 'git status' output.

Perhaps I'm just odd, but I have worked on projects with other people so I know it's not quite 'just me'. If it is judged to be 'odd', then so be it and I'll be fine with whatever decision is made...I will anyway, tbh. All I asked is that it is considered, and I think it has been...though I perhaps haven't communicated it too well (sorry about that).

**Comment by justinfagnani** [comment]
None of the templates are useful without a `bower install`, so for 99% of the users, they will need to install.

I've also never seen anyone before not use `.gitignore` to ignore `bower_components/` and `node_modules/`. I'm curious about this use case. Untracked git files are something you generally want to avoid, and `.gitignore` lets you do that. Why would you want to keep it _out_ of `.gitignore`?

**Comment by davidmaxwaterman** [comment]
well, like I said...I like to see them there so I know what is going on. It's only two lines and I find it reassuring. It is a bit like the '.' files...they're hidden in ls output by default, and I'd simply rather know they are there.
I have had a discussion on #polymer and I can see the arguments, but there's nothing really I didn't already know - it's just that I like to see what is there, and haven't had any issues spotting files that shouldn't be there (and so should be git added).
Either way, it's a red herring in my mind. I accept I am unusual in this respect and accept it is probably good to have it added to .gitignore.
I still think bower install should be a step separate from polymer init, just like bower install actually is...or is there a magic step other than bower install that notices when I've added things to bower.json and then runs it?
If the user has to run bower install anyway at some point, why not simply have them get used to it?
Unfortunately, 'polymer build' is broken for me atm, so I can't actually tell what it does...perhaps it's a little like 'make' and only runs bower install if the bower.json file is newer than something or other.
The other issue is that bower.json certainly doesn't need all those dependencies in it for the 'blank project'. I think that's still valid.

**Comment by davidmaxwaterman** [comment]
This issue has become complicated. Let me try to enumerate the issues.

Removed issues :
1. I accept that the (vast) majority would prefer bower_components/ added to .gitignore (my preference is unusual).
1. I see that some dependencies in bower_components/ are actually *dev* dependencies in bower.json, so I guess they are actually for the tools rather than my app, so that's fair enough. This also implies that a `bower install` during `polymer init` is fair enough.

Remaining :
1. I still consider that `bower install` is a separate step. EG, I added platinum-sw to bower.json and did a `polymer build` and no 'bower install' step was run. 
1. The documentation at https://www.polymer-project.org/1.0/start/toolbox/set-up 'Initialize Git repository (optional)' implies the `bower_components/` directory is added to the git repo, which I think it wrong...will this be 'fixed' by adding it to `.gitignore`? If so, fair enough, though I think it would be good to add any other generated directories too, plus a 'warning' in the docs to warn for committing generated files might be appropriate - yes, it's easy enough to fix that problem, but no need if it isn't one to start with.
1. Perhaps webcomponentsjs should be moved to the 'dependencies' from the 'devDependencies'?

**Comment by addyosmani** [comment]
> None of the templates are useful without a bower install, so for 99% of the users, they will need to install.

This was the case for a lot of templates in Yeoman generators too. For some, we worked on making the templates useful without the need for a package manager installation step, but the reality is if you're using a CLI tool that's being prescriptive having it take care of a step most beginners aren't going to realise they will need (`bower install`), makes sense.

**Comment by davidmaxwaterman** [comment]
Yes, I can agree with that...the beginner aspect. I suppose the only argument I can see is that they are almost certainly going to need to use such a tool/step pretty quickly, so why not introduce it right away?

In any case, I think this aspect has been considered well enough and it seems to me to be valid that a `bower install` step during `polymer init`, combined with appropriate additions to a `.gitignore` file, and the dependencies correctly defined in `bower.json` as plain or development dependencies, is a good decision for the new user. It seems to be that this tool is targeting the new user and more experienced users can adapt easily enough.

**Comment by davidmaxwaterman** [comment]
One aspect that might be worth considering is that this tool is targeted at beginners. I should point out that I am not a beginner, but I still found myself trying to use this tool. Thinking about it, it wasn't obvious to me that it is targeted at beginners (it's not mentioned on the web page [0]). My motivation for using the tool are to have a project architecture that is some how 'standard', or perhaps just 'recommended'; to relieve myself of the burden of maintaining the build tools as much as possible. I recently attempted to convert a project to use the PSK, but found myself needing to modify the gulpfile quite a bit.

So, is this tool *really* targeting people who are new, and who don't already know about 'npm install', and 'bower install' - both of which have become almost automatic to me?

[0] <https://www.polymer-project.org/1.0/toolbox/>

**Comment by Rayraegah** [comment]
I changed the code a little prevent polymer cli's `init` module to skip installation using a switch like

    $ polymer init --no-install

The Yeoman-generator used by polymer pushes a bower install command which can be skipped or halted.

![image](https://cloud.githubusercontent.com/assets/1559650/19081697/230d5b18-8a53-11e6-8d99-4182066469c4.png)

**Comment by davidmaxwaterman** [comment]
This is old now and lately irrelevant so closing.
