### ISSUE TITLE
is <platinum-sw-register> needed with polymer-cli

### ISSUE THREAD

**Issue by pinkflozd** [Polymer/polymer-cli#228]
Hello.

Is platinum-sw-register still needed if i use the sw-precache-config.js and then build the app with polymer build?

**Comment by justinfagnani** [comment]
You can use `<platinum-sw-register>` if you like, but I'm not sure it's worth it. Just add a simple script to your index.html:

```
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('/service-worker.js', { scope: '/' });
}
```
