### ISSUE TITLE
error:   Promise rejection: AssertionError: A name parameter is required to create a storage

### ISSUE THREAD

**Issue by kenchris** [Polymer/polymer-cli#247]
Just installed polymer-cli following the instructions, then when I try it in my test/ dir, I get the following errors.

test (master)$ polymer init 
? Which starter template would you like to use? app-drawer-template
info:    Running template app-drawer-template
error:   Promise rejection: AssertionError: A name parameter is required to create a storage
error:   AssertionError: A name parameter is required to create a storage
    at new Storage (/usr/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/util/storage.js:24:3)
    at GithubGenerator.Base._getStorage (/usr/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/base.js:665:10)
    at GithubGenerator.Base (/usr/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/base.js:157:22)
    at GithubGenerator (/usr/lib/node_modules/polymer-cli/lib/init/github.js:21:36)
    at Environment.instantiate (/usr/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:328:10)
    at Environment.create (/usr/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:305:15)
    at Environment.run (/usr/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:364:24)
    at runGenerator (/usr/lib/node_modules/polymer-cli/lib/commands/init.js:65:29)
    at /usr/lib/node_modules/polymer-cli/lib/commands/init.js:131:25

**Comment by justinfagnani** [comment]
I'll try to reproduce this today.

**Comment by justinfagnani** [comment]
@kenchris can't reproduce yet. Can you tell me more about your environment? What OS and node version are you using? Do you have a bower.json or package.json in this folder?

**Comment by kenchris** [comment]
Sure, latest Ubuntu, Node.js v5.11.0

**Comment by kenchris** [comment]
I ran this inside my existing project which you can actually check out, if that helps:

https://github.com/01org/webnfc-shoppingcart-demo

I can it inside app/ I believe and also tried in root first

**Comment by kenchris** [comment]
23 var Storage = module.exports = function Storage(name, fs, configPath) {
 24   assert(name, 'A name parameter is required to create a storage');

It is failing on this line, so name must be null or undefined somehow.

**Comment by kenchris** [comment]
The this.appname inside /usr/lib/node_modules/polymer-cli/node_modules/yeoman-generator/lib/base.js +157 seems to be fine, as it is the same as the current directory.

But the rootGeneratorName is undefined:

663 Base.prototype._getStorage = function () {
664   var storePath = path.join(this.destinationRoot(), '.yo-rc.json');
665   console.log(this.rootGeneratorName());
666   return new Storage(this.rootGeneratorName(), this.fs, storePath);
667 };

**Comment by kenchris** [comment]
So that must be the issue, that name is set to '' somehow (project is based on PSK)

Notice the ```  name: '',```

```
$ polymer init 
? Which starter template would you like to use? application
info:    Running template application
{ private: true,
  devDependencies: 
   { 'browser-sync': '^2.7.7',
     'connect-history-api-fallback': '^1.1.0',
     del: '^2.0.2',
     'glob-all': '^3.0.1',
     gulp: '^3.8.5',
     'gulp-autoprefixer': '^3.1.0',
     'gulp-cache': '^0.4.0',
     'gulp-changed': '^1.0.0',
     'gulp-gh-pages': '^0.5.4',
     'gulp-html-extract': '^0.1.0',
     'gulp-if': '^2.0.0',
     'gulp-imagemin': '^2.2.1',
     'gulp-jscs': '^3.0.0',
     'gulp-jscs-stylish': '^1.1.2',
     'gulp-jshint': '^1.6.3',
     'gulp-load-plugins': '^1.1.0',
     'gulp-minify-css': '^1.2.1',
     'gulp-minify-html': '^1.0.2',
     'gulp-rename': '^1.2.0',
     'gulp-replace': '^0.5.4',
     'gulp-size': '^2.0.0',
     'gulp-uglify': '^1.2.0',
     'gulp-useref': '^2.1.0',
     'jshint-stylish': '^2.0.0',
     'merge-stream': '^1.0.0',
     'require-dir': '^0.3.0',
     'run-sequence': '^1.0.2',
     vulcanize: '>= 1.4.2',
     'web-component-tester': '^4.0.0',
     'http2-push-manifest': '^1.0.0' },
  scripts: 
   { test: 'gulp test:local',
     start: 'gulp serve',
     lint: 'gulp lint' },
  engines: { node: '>=0.10.0' },
  name: '',
  version: '',
  readme: 'ERROR: No README data found!',
  _id: '@' }

{ private: true,
  devDependencies: 
   { 'browser-sync': '^2.7.7',
     'connect-history-api-fallback': '^1.1.0',
     del: '^2.0.2',
     'glob-all': '^3.0.1',
     gulp: '^3.8.5',
     'gulp-autoprefixer': '^3.1.0',
     'gulp-cache': '^0.4.0',
     'gulp-changed': '^1.0.0',
     'gulp-gh-pages': '^0.5.4',
     'gulp-html-extract': '^0.1.0',
     'gulp-if': '^2.0.0',
     'gulp-imagemin': '^2.2.1',
     'gulp-jscs': '^3.0.0',
     'gulp-jscs-stylish': '^1.1.2',
     'gulp-jshint': '^1.6.3',
     'gulp-load-plugins': '^1.1.0',
     'gulp-minify-css': '^1.2.1',
     'gulp-minify-html': '^1.0.2',
     'gulp-rename': '^1.2.0',
     'gulp-replace': '^0.5.4',
     'gulp-size': '^2.0.0',
     'gulp-uglify': '^1.2.0',
     'gulp-useref': '^2.1.0',
     'jshint-stylish': '^2.0.0',
     'merge-stream': '^1.0.0',
     'require-dir': '^0.3.0',
     'run-sequence': '^1.0.2',
     vulcanize: '>= 1.4.2',
     'web-component-tester': '^4.0.0',
     'http2-push-manifest': '^1.0.0' },
  scripts: 
   { test: 'gulp test:local',
     start: 'gulp serve',
     lint: 'gulp lint' },
  engines: { node: '>=0.10.0' },
  name: '',
  version: '',
  readme: 'ERROR: No README data found!',
  _id: '@' }
error:   Promise rejection: AssertionError: A name parameter is required to create a storage
error:   AssertionError: A name parameter is required to create a storage
```

**Comment by kenchris** [comment]
Now I don't have name set in the package.json so it must be inferred from somewhere else.

**Comment by justinfagnani** [comment]
It's probably that there's a package.json at all. Yeoman is inferring the name, @addyosmani do you know if Yeoman has trouble with package.json with no name field?

**Comment by justinfagnani** [comment]
Ok, reproduced now, I think I have a fix.
