### ISSUE TITLE
Polymer Build Error when including polymerfire

### ISSUE THREAD

**Issue by craftyc0der** [Polymer/polymer-cli#248]
This error prevents the building of an bundled package. 
Reproduce by adding polymerfire to bower.json
`"polymerfire": "firebase/polymerfire#^0.9.2",`
Error:
> ```
debug:   no file for ../bower_components/firebase-sdk/index.js :(
debug:   No file found for ../bower_components/firebase-sdk/index.js
debug:   no file for ../bower_components/promise-polyfill/Promise.js :(
debug:   No file found for ../bower_components/promise-polyfill/Promise.js
debug:   no file for ../bower_components/promise-polyfill/Promise-Statics.js :(
debug:   No file found for ../bower_components/promise-polyfill/Promise-Statics.js
error:   Promise rejection: Error: no resolver found for ../bower_components/firebase-sdk/index.js
error:   Error: no resolver found for ../bower_components/firebase-sdk/index.js
```

**Comment by Scarygami** [comment]
Building with polymerfire works for me. Maybe delete your `bower_components` folder and do another `bower install` to make sure all dependencies are fetched correctly?

**Comment by craftyc0der** [comment]
I have, but I'll do it again. FYI, it failed on both windows 7 and 10. Stand by for a more detailed procedure to recreate failure. I started with one of the new demos, so there may be a strange dependency issue.

**Comment by craftyc0der** [comment]
My apologies. This is related to a bad build file for the polymer-cli. Adding Firebase appeared the proximate cause but I was in error. Thank you for your efforts!
