### ISSUE TITLE
[Install] Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by LostInBrittany** [Polymer/polymer-cli#253]
I wanted to update `polymer-cli` to the last version, so I did a `npm install -g polymer-cli` and the install failed with a rather cryptic *Maximum call stack size exceeded* error.

Running it on an Ubuntu 16.04, with Node 4.2.2 and npm 3.4.1binaries manually installed from nodejs.org (not using the ubuntu package).

The full response of npm:

 ```
$ npm install -g polymer-cli
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
loadDep:which → 304       ▀ ╢██████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/opt/node-v4.2.2-linux-x64/bin/node" "/opt/node/bin/npm" "install" "-g" "polymer-cli"
npm ERR! node v4.2.2
npm ERR! npm  v3.4.1

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/horacio/cityzendata/git/webcomponents/warp10-dashboard/npm-debug.log
```

I'm updating my node and npm to a more recent on and trying again, but if I recall correctly it should work with that setting. At least it worked as a charme the two first times I installed it...

**Comment by LostInBrittany** [comment]
I switched to npm 3.9.5 and the problem isn't there, switched back et 3.4.1 and the problem was back, so I guess it's some weird npm related issue. 

I guess I should be closing it, and keeping it in the closed issues list as a cue to other people finding the same problem...

What do you think?

**Comment by justinfagnani** [comment]
Let's close, since we can't possibly keep all issues that might be relevant open. Hopefully people can search closed issues :)
