### ISSUE TITLE
ES6 Vanilla Web Component Template Feature

### ISSUE THREAD

**Issue by Nevraeka** [Polymer/polymer-cli#267]
### Description

I wanted to automate creation of vanilla web components I'm building. This feature would do that using the Polymer CLI. As a hackathon project [I forked polymer-cli and added a template, tests, etc](https://github.com/Nevraeka/polymer-cli/commit/e6eb0c16113848547798fc4c06dbab0da143d623). My work is from a hackathon...so its needs to be a bit refined. I was just going to submit a PR but after chatting with @robdodson I thought I'd create an issue first. 

I'm totally open to changing the template from webpack/babel to TypeScript or JSPM/System. What ever makes the most sense. The structure is just the basics of what I've been working with.  Other than that here are a few changes I was planning on getting to

#### TODO
- update cli help files
- simplify element and reduce mixins
- replace webpack w/ more standardized approach (jspm/systemjs ?)
- capitalize generated className prop
- update tests
- write/add webcomponents dependency loader mixin
- Update README with better docs
- Solidify prompts & content
- rename to vanilla instead of es6 (reserve name 4 a polymer es6 tmpl)

I appreciate any thoughts and direction since I am new to the project. thank you

Also adding a link to this in the Polymer Slack Channel (https://bit.ly/polymerslack)

**Comment by Nevraeka** [comment]
cc @revillweb @treshugart @JanMiksovsky @deebloo

**Comment by justinfagnani** [comment]
You don't have to fork the CLI to add tempaltes. Just publish an npm module that starts with the name `generator-polymer-init-`.

**Comment by Nevraeka** [comment]
@justinfagnani - thanks. I'll look on NPM for examples. Anything special I should know about publishing these?

**Comment by RevillWeb** [comment]
Hi @justinfagnani is there any documentation for the npm modules? I'd like to help @Nevraeka out with this. Thanks for your time.

**Comment by justinfagnani** [comment]
@RevillWeb the README mentions it, but it's just a normal yeoman generator with a package name prefix of `generator-polymer-init-`. That's about all the docs would have in it.

**Comment by FredKSchott** [comment]
@RevillWeb @Nevraeka check out http://yeoman.io/authoring/ for a how to on writing your own Yeoman generator. As long as it's name follows the  "generator-polymer-init-*" pattern and is installed globally, `polymer init` will pick it up and offer it as an option.

Good luck! If you have any polymer questions while building, feel free to check out our [Slack Channel](https://bit.ly/polymerslack)
