### ISSUE TITLE
Add new init tempaltes

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-cli#27]
app-layout and others...

**Comment by kaycebasques** [comment]
There should also be a lightweight element init template for app projects. Something that just asks for an element name (e.g. `my-el`) and creates the barebones files under `src/` (e.g. `src/my-el/my-el.html`).

**Comment by justinfagnani** [comment]
Yes, this is the fabled `polytool gen` command

**Comment by justinfagnani** [comment]
Closing until we have actual templates to add.
