### ISSUE TITLE
[feature request] flexible app structure

### ISSUE THREAD

**Issue by AliMD** [Polymer/polymer-cli#277]
Could you please add some option for flexible app structure
I'm trying to change folder structure to polymer starter kit but i can't move my files to app folder
Polymer-cli need to access `bower.json` and at root then i must run `polymer serve` in root but i need to move my index file to app folder and need something like this in configuration
```
"server": { "baseDir": "app" }
```
 Thank you in advance

**Comment by AliMD** [comment]
I found `root` config in the source but its different with serve `baseDir` and make issue with access `bower.json`

**Comment by abdonrd** [comment]
Reference: https://github.com/Polymer/polymer-cli/issues/273

**Comment by FredKSchott** [comment]
Yes, closing as a duplicate #273 (we'll use 273 to track this feature request)
