### ISSUE TITLE
[feature request] add option for change components url

### ISSUE THREAD

**Issue by AliMD** [Polymer/polymer-cli#278]
We usually rename `bower_components` to `components`
And I can't load `/components` anymore because it conflict with polymer-cli components url
Could you please add an option for change components url
And/or disable this feature or/and log warning if the `components` folder exist

I will happy to contributing if it can't be in the active milestone.

**Comment by addyosmani** [comment]
Hmm. I wonder if it makes sense to respect a local `.bowerrc` if one is defined for this use-case. That said, unsure how much @justinfagnani wants to support configuring package paths so deferring to him for more thought here.

**Comment by AliMD** [comment]
@addyosmani Thank you

@justinfagnani i know its not have any priority then if you permit and make little help I will happy to contributing

**Comment by justinfagnani** [comment]
This issue was moved to PolymerLabs/polyserve#101
