### ISSUE TITLE
build fails TypeError: Cannot read property 'is' of null

### ISSUE THREAD

**Issue by milesje** [Polymer/polymer-cli#281]
### Description
Build fails with Uncaught exception: TypeError: Cannot read property 'is' of null

### Versions & Environment
- Polymer CLI: v0.11.1
- node: v6.2.1
- Operating System: Debian Jessie

#### Steps to Reproduce
run command: polymer build

#### Expected Results
Polymer build of bundled and unbundled versions.

#### Actual Results
Error is thrown

> error:   Uncaught exception: TypeError: Cannot read property 'is' of null
> error:   TypeError: Cannot read property 'is' of null
>     at Parser.parseDeclarationOrRuleset (/usr/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:191:33)
>     at Parser.parseRule (/usr/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:80:21)
>     at Parser.parseRules (/usr/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:62:25)
>     at Parser.parseStylesheet (/usr/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:55:47)
>     at Parser.parse (/usr/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:51:19)
>     at css (/usr/lib/node_modules/polymer-cli/node_modules/css-slam/index.js:51:39)
>     at GulpTransform._transform (/usr/lib/node_modules/polymer-cli/node_modules/css-slam/index.js:69:36)
>     at GulpTransform.Transform._read (_stream_transform.js:167:10)
>     at GulpTransform.Transform._write (_stream_transform.js:155:12)
>     at doWrite (_stream_writable.js:307:12)
>     at writeOrBuffer (_stream_writable.js:293:5)

**Comment by milesje** [comment]
I wonder if it is blowing up on some element that I have installed. I created a fresh project and performed the polymer init (chose app-drawer-template) and then ran polymer build and it works.  So I will experiment with adding each element and then performing a build to see what element is causing the build to error out. I am suspecting that it is the Vaadin-grid but I will make sure.

**Comment by vaadin-marcus** [comment]
@milesje – yes, there was a syntax error in a CSS file in one of `vaadin-grid`'s demos (not sure why they get parsed at all by the CLI). See https://github.com/vaadin/vaadin-grid/issues/382

You can use master for now, we should get a new release out shortly.

**Comment by FredKSchott** [comment]
Thanks for jumping in and responding @vaadin-marcus!

Some point soon we may want to add better logging on this class of error.
