### ISSUE TITLE
Auto reload all browsers on file changes

### ISSUE THREAD

**Issue by IchordeDionysos** [Polymer/polymer-cli#286]
I love it how you can easily develop with Polymer Starter Kit because it refreshes automatically on file changes, so you don't have to refresh the page each time manually.
But the downside on Polymer Stater Kit is that you always have to download all npm packages for each project as small it is ...
So I wondered if you could implement such auto reload, to help me out of my conflict between PSK and CLI.
Thanks Dennis Kugelmann

**Comment by addyosmani** [comment]
@justinfagnani Two cents: After using auto-reload-all-browsers-on-file-changes (BrowserSync-style) reload for a few years, I've found it to offer diminishing returns in starter projects. My vote would be for sticking with the current behaviour for the sake of simplicity.

**Comment by FredKSchott** [comment]
@IchordeDionysos thanks for the feedback. This feature request is already being tracked in #230.
