### ISSUE TITLE
Why aren't we using Commander.js?

### ISSUE THREAD

**Issue by gaurav21r** [Polymer/polymer-cli#287]
Hi there, just a friendly tip / doubt.

Wouldn't the program architecture be a tad simple if we use https://github.com/tj/commander.js?
It seems to be extremely popular and covers most of the options we need in the CLI

1. Will you accept PRs which refactor the current CLI system to Commander?
2. Just a thought on why this wasn't chosen at start?

**Comment by addyosmani** [comment]
What specifically is more complex with the current architecture that would be alleviated with commander.js?

**Comment by FredKSchott** [comment]
We're currently pretty happy with our command/argument parsing logic & libraries. If there's anything that could be significantly improved by refactoring to use Commander please let us know (although it would have to be a pretty big improvement to warrant such a big change).
