### ISSUE TITLE
Re-usable element template error when dev console open

### ISSUE THREAD

**Issue by NicolasRannou** [Polymer/polymer-cli#288]
I got an error when reloading an element with the dev console is open.
```
nico@OSXLAP01821-2:~/work$ polymer --version
0.11.0
nico@OSXLAP01821-2:~/work$ mkdir yoyo
nico@OSXLAP01821-2:~/work$ cd yoyo/
nico@OSXLAP01821-2:~/work/yoyo$ polymer init
? Which starter template would you like to use? element
info:    Running template element
? Element name yoyo-element
? Brief description of the element 
...
Project generated!
...
```

Then
```
nico@OSXLAP01821-2:~/work/yoyo$ polymer serve
Starting Polyserve...
    serving on port: 8080
    from root: /Users/nico/work/yoyo
  
Files in this directory are available under the following URLs
    applications: http://localhost:8080
    reusable components: http://localhost:8080/components/yoyo-element/
```

When I go to `http://localhost:8080/components/yoyo-element/`, with the dev console open (Chrome 51), it catches an error.
![screen shot 2016-06-24 at 2 09 37 pm](https://cloud.githubusercontent.com/assets/214063/16337372/5cf560f2-3a15-11e6-877d-2b42f8236a00.png)

It the console is closed, it proceeds successfully....

**Comment by FredKSchott** [comment]
Cannot reproduce in v0.13.0, try updating and let us know if you're still running into this.
