### ISSUE TITLE
Re-usable element missing markup

### ISSUE THREAD

**Issue by NicolasRannou** [Polymer/polymer-cli#289]
The re-usable element template is missing markup so it doesn't show the "demo" button form the element page.

In your-element.html, it misses
```
<!--
your-element
@demo demo/index.html
-->
```

Apologizes as it is probably not the right place to report that but I find hard to know where the templates are coming from (maybe some doc in the README would help :) )

**Comment by FredKSchott** [comment]
This feature is on master but has not yet been released. We are currently planning a release that should be released soon. Until then, you can install polymer-cli directly from Github to get the latest code.

Thanks for filing!
