### ISSUE TITLE
Straight "polymer init app-drawer-template;polymer serve": app fail as bower_components is in the wrong path

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer-cli#294]
### Description

polymer init and polymer serve out of the box don't work as bower_components seem to be in the wrong tree

### Versions & Environment
- Polymer CLI: 0.11.1
- node: v4.4.4
- Operating System: Ubuntu

#### Steps to Reproduce

Install app-drawer-template:

    $ polymer init app-drawer-template 
    info:    Running template app-drawer-template
    info:    Downloading latest release of Polymer/app-drawer-template
    info:    Unpacking template files
    info:    Finished writing template files
    I'm all done. Running bower install for you to install the required dependencies. If this fails, try running the command yourself.
    bower cached        git://github.com/polymerelements/app-layout.git#0.9.1
    bower validate      0.9.1 against git://github.com/polymerelements/app-layout.git#^0.9.0
    bower cached        git://github.com/polymerelements/iron-icon.git#1.0.8
    ...
    stacky#1.3.2 app/bower_components/stacky
    $

Serve:

    Starting Polyserve...
        serving on port: 8081
        from root: /disk/home/merc/Data/Development/node/my_apps/node_modules/gigsnet/AA
      
    Files in this directory are available under the following URLs
        applications: http://localhost:8081
        reusable components: http://localhost:8081/components/app-drawer-template/

Go to http://localhost:8081 with browser. You get a whole lot of "file not found", for example:

http://localhost:8080/bower_components/polymer/polymer.html 

Making a symlink between "fixes" it:

    ln -s app/bower_components bower

But... surely, this isn't a fix!
(It's likely I am doing something silly... as ever

**Comment by claudiordgz** [comment]
This seems fixed in master

**Comment by mercmobily** [comment]
Yep. Sorry.
