### ISSUE TITLE
App-location using the use-hash-as-path attribute don't work

### ISSUE THREAD

**Issue by syu93** [Polymer/polymer-cli#296]
Hi, it's my first issue here, sorry if it's a non-sens

### Description

Using the shop demo, I need to use the hash routing way, but it seem not to be working.
I've add the **use-hash-as-path** property 
The URL is still updated but without adding the hash 
### Versions & Environment

- Polymer CLI:0.11.1
- node:5.11.0
- Operating System:Debian Jessie
#### Steps to Reproduce

add the *_use-hash-as-path *_ property to the app-location

``` html
<app-location route="{{route}}" use-hash-as-path></app-location>
```
#### Expected Results

Routing using hash
#### Actual Results

No routing at all

**Comment by jamesmgg** [comment]
@syu93 I had the same issue but by checking out another of the github issue I found the solution:
You have to make the links look like this: #/view1. Hope this works. Cheers

**Comment by syu93** [comment]
@jamesmgg Sorry for the very late response.

I figured it out long time ago. But thx bro
