### ISSUE TITLE
Best practices as where to place a scripts that create README.md automagically?

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer-cli#309]
I created a [terrible but functional script](https://github.com/mercmobily/hot-form-validator/blob/master/make_readme.sh) that creates README.md from my simple element.

I missed the recent discussions about grunt etc., and was just wondering... what are the best practices at the moment to make sure that this happens semi-automatically?

If this were your component, and you were the author of [this pearl](https://github.com/mercmobily/hot-form-validator/blob/master/make_readme.sh) to get the README.md generated, where would you place it and how would you run it?

**Comment by FredKSchott** [comment]
There are not currently any hooks into polymer-cli commands for running custom scripts like this. 

My advice would be to create a custom [npm script](https://docs.npmjs.com/misc/scripts) that calls whatever you want before/after calling `polymer X`. So for example, to run a custom script before build, you could include `"build": "./custom-script && polymer build"` in your `package.json` file scripts object, and then run `npm run build` to execute those two commands.

Good luck!
