### ISSUE TITLE
Error "Promise rejection: Error: no resolver found for ../polymer/polymer.html" for "polymer build" with 0.12.0

### ISSUE THREAD

**Issue by jfletcher-nuxeo** [Polymer/polymer-cli#314]
### Description
Build fails for release 0.12.0 with the following errors:

    error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
    error:   Error: no resolver found for ../polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
(the errors repeat 3 times)

I also tried changing the `<link..>` path to `../bower_components/polymer/polymer.html` and it still fails; the errors contain the updated path.

### Versions & Environment
- Polymer CLI: 0.12.0
- node: 4.4.1
- Operating System: OS X El Capitan

#### Steps to Reproduce
* `mkdir polymer-test`
* `cd polymer-test/`
* `polymer init` (accept defaults)
* `polymer build`

#### Expected Results
Build should not fail for out-of-the box projects.

#### Actual Results
Build fails with default project.

**Comment by FredKSchott** [comment]
@jfletcher-nuxeo can you still reproduce after update polymer-cli to latest? We just released a new version of the cli that included a few major fixes to the build pipeline that have hopefully fixed this. If you can still reproduce, can you include a new copy of the error logs so that I can take a look?

Really appreciate your help!

**Comment by quangv** [comment]
I had the same previous error on `polymer build` on 0.12

```
quang@debian:~/todo-polymer$ polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to optimize .js file /home/quang/todo-polymer/src/todo-polymer-app/todo-polymer-app.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: name (text)',
     filename: 0,
     line: 25,
     col: 12,
     pos: 466,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)\n    at token_error (eval at <anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)\n    at unexpected (eval at <anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)\n    at semicolon (eval at <anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2123:56)\n    at simple_statement (eval at <anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:73)\n    at eval (eval at <anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2183:19)\n    at eval (eval at <anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)\n    at block_ (eval at <anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)' } }
```

^-- new nicer looking error message on 0.13, on my public sample polymer project: https://github.com/quangv/todo-polymer

**Comment by adefran83** [comment]
`debug:   got args: 
{ args: [ 'build', '-v' ] }
debug:   config file not found 
{ path: 'polymer.json' }
debug:   got default config from file: 
{ config: {} }
debug:   adding command build
debug:   adding command help
debug:   adding command init
debug:   adding command lint
debug:   adding command serve
debug:   adding command test
debug:   running...
debug:   command 'build' found, parsing command args: 
{ args: [ '-v' ] }
debug:   command options parsed from args: 
{ 'sw-precache-config': 'sw-precache-config.js', verbose: true }
debug:   final project configuration generated: 
{ root: '/Users/anthonydefrancesco/code/polymer-test',
  entrypoint: '/Users/anthonydefrancesco/code/polymer-test/polymer-test.html',
  fragments: [],
  inputs: [ '/Users/anthonydefrancesco/code/polymer-test/polymer-test.html' ] }
debug:   Running command...
debug:   building with options 
{ sources: undefined,
  includeDependencies: undefined,
  swPrecacheConfig: 'sw-precache-config.js',
  insertDependencyLinks: undefined,
  html: {},
  css: {},
  js: {} }
debug:   building via standard build()...
debug:   sourceGlobs: 
	/Users/anthonydefrancesco/code/polymer-test/polymer-test.html
	/Users/anthonydefrancesco/code/polymer-test/src/**/*
	/Users/anthonydefrancesco/code/polymer-test/bower.json
debug:   root: /Users/anthonydefrancesco/code/polymer-test
debug:   shell: undefined
debug:   entrypoint: /Users/anthonydefrancesco/code/polymer-test/polymer-test.html
debug:   fragments: /Users/anthonydefrancesco/code/polymer-test/polymer-test.html
debug:   sources: /Users/anthonydefrancesco/code/polymer-test/src/**/*,/Users/anthonydefrancesco/code/polymer-test/bower.json
debug:   includeDependencies: 
info:    Building application...
debug:   Reading source files...
debug:   sourceGlobs: 
	/Users/anthonydefrancesco/code/polymer-test/polymer-test.html
	/Users/anthonydefrancesco/code/polymer-test/src/**/*
	/Users/anthonydefrancesco/code/polymer-test/bower.json
debug:   Reading dependencies...
debug:   No service worker configuration found at /Users/anthonydefrancesco/code/polymer-test/sw-precache-config.js, continuing with defaults
debug:   Analyzing build dependencies...
debug:   addFile: /Users/anthonydefrancesco/code/polymer-test/polymer-test.html
info:    Generating build/unbundled...
info:    Generating build/bundled...
debug:   accept: polymer-test.html
debug:   accept: ../polymer/polymer.html
debug:   new dependency found, pushing into dependency stream... /Users/anthonydefrancesco/code/polymer/polymer.html
error:   Uncaught exception: Error: ENOENT: no such file or directory, open '/Users/anthonydefrancesco/code/polymer/polymer.html'
error:   Error: ENOENT: no such file or directory, open '/Users/anthonydefrancesco/code/polymer/polymer.html'
    at Error (native)
debug:   addFile: /Users/anthonydefrancesco/code/polymer-test/bower.json
`

Here is the error I get when trying to build it.

This is just accepting the defaults, i get the same error message when creating app-drawer-template

**Comment by jfletcher-nuxeo** [comment]
With 0.13.0 I get:

    info:    Building application...
    info:    Generating build/unbundled...
    info:    Generating build/bundled...
    error:   Uncaught exception: Error: ENOENT: no such file or directory, open '/Users/jfletcher/temp/polymer/polymer.html'
    error:   Error: ENOENT: no such file or directory, open '/Users/jfletcher/temp/polymer/polymer.html'
        at Error (native)

And verbose output:

    debug:   got args: 
    { args: [ 'build', '--verbose' ] }
    debug:   config file not found 
    { path: 'polymer.json' }
    debug:   got default config from file: 
    { config: {} }
    debug:   adding command build
    debug:   adding command help
    debug:   adding command init
    debug:   adding command lint
    debug:   adding command serve
    debug:   adding command test
    debug:   running...
    debug:   command 'build' found, parsing command args: 
    { args: [ '--verbose' ] }
    debug:   command options parsed from args: 
    { 'sw-precache-config': 'sw-precache-config.js', verbose: true }
    debug:   final project configuration generated: 
    { root: '/Users/jfletcher/temp/polymer-test',
      entrypoint: '/Users/jfletcher/temp/polymer-test/polymer-test.html',
      fragments: [],
      inputs: [ '/Users/jfletcher/temp/polymer-test/polymer-test.html' ] }
    debug:   Running command...
    debug:   building with options 
    { sources: undefined,
      includeDependencies: undefined,
      swPrecacheConfig: 'sw-precache-config.js',
      insertDependencyLinks: undefined,
      html: {},
      css: {},
      js: {} }
    debug:   building via standard build()...
    debug:   sourceGlobs: 
    	/Users/jfletcher/temp/polymer-test/polymer-test.html
    	/Users/jfletcher/temp/polymer-test/src/**/*
    	/Users/jfletcher/temp/polymer-test/bower.json
    debug:   root: /Users/jfletcher/temp/polymer-test
    debug:   shell: undefined
    debug:   entrypoint: /Users/jfletcher/temp/polymer-test/polymer-test.html
    debug:   fragments: /Users/jfletcher/temp/polymer-test/polymer-test.html
    debug:   sources: /Users/jfletcher/temp/polymer-test/src/**/*,/Users/jfletcher/temp/polymer-test/bower.json
    debug:   includeDependencies: 
    info:    Building application...
    debug:   Reading source files...
    debug:   sourceGlobs: 
    	/Users/jfletcher/temp/polymer-test/polymer-test.html
    	/Users/jfletcher/temp/polymer-test/src/**/*
    	/Users/jfletcher/temp/polymer-test/bower.json
    debug:   Reading dependencies...
    debug:   No service worker configuration found at /Users/jfletcher/temp/polymer-test/sw-precache-config.js, continuing with defaults
    debug:   Analyzing build dependencies...
    debug:   addFile: /Users/jfletcher/temp/polymer-test/polymer-test.html
    info:    Generating build/unbundled...
    info:    Generating build/bundled...
    debug:   accept: polymer-test.html
    debug:   accept: ../polymer/polymer.html
    debug:   new dependency found, pushing into dependency stream... /Users/jfletcher/temp/polymer/polymer.html
    error:   Uncaught exception: Error: ENOENT: no such file or directory, open '/Users/jfletcher/temp/polymer/polymer.html'
    error:   Error: ENOENT: no such file or directory, open '/Users/jfletcher/temp/polymer/polymer.html'
        at Error (native)
    debug:   addFile: /Users/jfletcher/temp/polymer-test/bower.json

**Comment by FredKSchott** [comment]
@quangv interesting, I can reproduce that same output when run in your project. It looks like it's just failing silently which is no good. Digging into it now...
@jfletcher-nuxeo @adefran83 usually a "no such file or directory" error appears when a bad path in your project is encountered. Check your project for where that path may have come and make sure it's pointing where you need it to.

**Comment by FredKSchott** [comment]
@quangv not sure where it's failing, but I was able to get it working for you. Here are the relevent lines from your output:

```
debug:   sourceGlobs: 
        /home/quang/todo-polymer/index.html
        /home/quang/todo-polymer/src/**/*
        /home/quang/todo-polymer/bower.json
debug:   root: /home/quang/todo-polymer
debug:   shell: undefined
debug:   entrypoint: /home/quang/todo-polymer/index.html
debug:   fragments: /home/quang/todo-polymer/index.html
debug:   sources: /home/quang/todo-polymer/src/**/*,/home/quang/todo-polymer/bower.json
debug:   includeDependencies: 
```

An undefined shell is okay, but fragments shouldn't be your `index.html`. If you run this, it successfully builds:

```
polymer build --verbose --fragment src/todo-polymer-app/todo-polymer-app.html 
```

Looks like we might have a problem with our defaults. As a work around for now, I'd suggest running with the `--fragment` flag or adding a polymer.json file to your project. See: https://www.polymer-project.org/1.0/docs/tools/polymer-cli#build-config

**Comment by FredKSchott** [comment]
Hmm, that actually ended up being an error with the logs:

```diff
-    logger.debug(`fragments: ${this.entrypoint}`);
+    logger.debug(`fragments: ${this.fragments}`);
```

But even after fixing that, it looks like we have some faulty logic when fragments aren't defined. Please define them as a work around for now (see: https://www.polymer-project.org/1.0/toolbox/server#app-structure)

**Comment by JeanRemiDelteil** [comment]
Even after defining a fragment it still fails silently for me.
It doesn't fails if I remove some import. But as it fails silently, it's complicated to find out why.

By comparing logs with faulty import removed or not, it fails before this part:
> external dependency ignored

**Comment by FredKSchott** [comment]
@JeanRemiDelteil it looks like it is actually outputting an error for you, your output above has: 

```
error:   Uncaught exception: Error: ENOENT: no such file or directory, open '/Users/jfletcher/temp/polymer/polymer.html'
error:   Error: ENOENT: no such file or directory, open '/Users/jfletcher/temp/polymer/polymer.html'
    at Error (native)
```

It looks like one of your files is incorrectly loading `polymer/polymer.html`, when it should be loading `bower_components/polymer/polymer.html` instead. Look for an incorrect number of `../` in your paths.

**Comment by JeanRemiDelteil** [comment]
@FredKSchott I'm not sure what you are mentioning because I did not post any logs ;)
I just know that my build fails silently before logging the following even once:
> external dependency ignored

I will try to track in detail why it's happening (or I could just revert to 0.12.0 that was working once I put all external files in local..., but that is not cool).

**Comment by JeanRemiDelteil** [comment]
@FredKSchott after tracking down the issue, it seems that the build will fail silently if you include <script> tag with local resources with a path relative to root.
Like the following:
`<script src="/lib/loader.js"></script>`

Current work around is just to set the path to be relative to the current HTML file.

**Comment by adefran83** [comment]
@FredKSchott I'm just trying to build the provided app-drawer-template, shouldn't it build without issues right out of the box? I checked any references and they appear to be correct. Are we supposed to be running the polymer build from a specific directory or the root of the project? In the build/bundled and build/unbundled folders i see the correct polymer file, but after running bower install, I don't see it in the bower_components folder in the root, is that the issue?

**Comment by FredKSchott** [comment]
@JeanRemiDelteil whoops! Sorry about that. Glad you got if figured out. 

We recommend using relative paths for all projects, so I'd replace all absolute URL paths like `/lib/loader.js` with ones relative to the current file. As an example, here's a random snippet of how this is done in the shop template:

```html
<!-- https://github.com/Polymer/shop/blob/master/src/shop-cart-item.html -->
<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../bower_components/iron-flex-layout/iron-flex-layout.html">
<link rel="import" href="../bower_components/paper-icon-button/paper-icon-button.html">
<link rel="import" href="shop-icons.html">
<link rel="import" href="shop-image.html">
<link rel="import" href="shop-select.html">
```

I think it's become obvious that regardless of what people think about this, we have a documentation problem (`polymer-serve` hiding some of these issues doesn't help much, either). I think the solution for now is to give a much more helpful error message here, and then looking into our project documentation as a whole to make this more clear.

**Comment by FredKSchott** [comment]
@adefran83 no one that I've seen has experiences issues with app-drawer-template out of the box. Can you open another issue with exact steps to reproduce? Thanks!

**Comment by FredKSchott** [comment]
@jfletcher-nuxeo `polymer build` is not currently supported for elements like the default element template. Please try running it on a different application template like `shop` or `app-drawer-template`.

**Comment by JeanRemiDelteil** [comment]
@FredKSchott I agree that in most case relative paths are the way to go,
however in the case of imported javascript library, I'm not a fan of having relative path:

Every js files are stored in a proper way (i'm talking about a production app here), and it does not make sense to refer to these files relatively as they are stored at a fixed path from the root of the app.

Anyway, i agree on the documentation problem ! I was looking to call polymer build from grunt, and it's not doable without looking at the code itself

**Comment by FredKSchott** [comment]
@JeanRemiDelteil check out https://github.com/Polymer/polymer-build/pull/19, we're writing a new readme as we speak :)

**Comment by FredKSchott** [comment]
Moving discussion to #337. If you have a similar problem but are confident that there are no absolute URL paths in your application, please open a new issue with clear steps to reproduce.
