### ISSUE TITLE
Error code return as 0 on failed polymer test run

### ISSUE THREAD

**Issue by pmaudsley** [Polymer/polymer-cli#315]
### Description
I am running test on custom elements using the Polymer CLI on a build server. The build server is setup to report a successful build on an exit code of 0 and failed builds on an exit code of !0. Currently Polymer CLI does not return any codes on a error which is resulting in the build I run to be successful all the time, even on failures. 

I will put a PR adding process.exit(1) on a error from cli.run()

### Versions & Environment
- Polymer CLI: 0.12.0
- node: v6.3.1

#### Steps to Reproduce

1. Create an test element: `polymer init element`
2. Run test: `polymer test`
3. Check exit code: `echo $?`
4. Edit test to result in error: change assert.equal(element.is, 'test-element') to assert.equal(element.is, 'foo');
5. Re-run test: `polymer test`
6. Check exit code: `echo $?`

#### Expected Results
Error code to be 0 on successful test and error code to be !0 on a failed test.

#### Actual Results
Error code is 0 on successful test and on a failed test.

**Comment by FredKSchott** [comment]
Fixed in #316 and released in v0.13.0!
