### ISSUE TITLE
Element template has incorrect path for polymer.html import

### ISSUE THREAD

**Issue by catiejojo** [Polymer/polymer-cli#317]
### Description
Relative path for polymer.html is wrong, so element template doesn't build out of the box.

### Issue
_These aren't relevant to the issue, but just to be thorough..._
- Polymer CLI: 0.12
- Node: 4.4.5
- Operating System: Mac OSX El Capitan 10.11.5

#### Steps to Reproduce
1. Create an element: `polymer init element`
2. Build: `polymer build`

#### Results
```
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
```

### Fix
I think the files in this project may have gotten reorganized without the paths getting updated. If you go to line one of the custom-element.html file, the polymer import path is "../polymer/polymer.html". However, that file is actually under the bower_components folder, so the line should be `<link rel="import" href="bower_components/polymer/polymer.html">
`. Making this change and rebuilding it fixes the error.

**Comment by jfletcher-nuxeo** [comment]
This is normal. It's explained here: https://github.com/Polymer/polymer-cli/issues/222#issuecomment-223631794

The idea is that in a deployed environment all the elements exist as siblings so relative paths need to be used.

**Comment by catiejojo** [comment]
Thanks for the quick reply, @jfletcher-nuxeo! I think I get what you're saying. So when I use `polymer build`, the minifying process condenses the file tree structure and puts everything in a single directory, so "bower_components/polymer/polymer.html" would be the wrong path in a deployed environment even though it's the right path in a local one. Is that accurate?

#### If so...follow-up question
How can I deploy my app if it won't build in the first place? As-is, the element template doesn't compile the build/bundled folder, and the only way I could find to fix it was to add bower_components to the path. Is it just that I'm supposed to compile the element within a larger project? What am I missing? Either way, I definitely agree with [this comment on the same thread](https://github.com/Polymer/polymer-cli/issues/222#issuecomment-223767145) that it should be documented somewhere.

Thanks again!

**Comment by jfletcher-nuxeo** [comment]
You can't, it's broken (hence issue #314 )

**Comment by jfletcher-nuxeo** [comment]
I wanted to add some clarification: what I said is true for *elements*. But not for *apps*. For apps the app won't be a sibling in `bower_components` so you may have a path like the one you posted.  In fact an absolute path is probably better in that case to avoid importing polymer.html from more than one URL (this causes problems).

**Comment by FredKSchott** [comment]
Thanks for the help here @jfletcher-nuxeo! What he said here is correct, `polymer build` isn't currently supported for element projects.

**Comment by FredKSchott** [comment]
added discussion to improve here: #338

**Comment by dsnowdon** [comment]
@jfletcher-nuxeo How are you using gulp? Could you post the relevant code from your gulpfile to show how to do this? When I run gulp over a element I get no such file or directory, how can I intercept any links that go back outside the project directory and resolve them as going to /bower_components/?
