### ISSUE TITLE
Feature request: serve command should support https

### ISSUE THREAD

**Issue by arodic** [Polymer/polymer-cli#323]
### Description

Polymer server should support https protocol since some web APIs require it.
#### Expected Results

Following comand should run a server with https protocol.

``` bash
polymer serve --https
```

Served application should be accessible at https://localhost:8080

**Comment by FredKSchott** [comment]
@arodic thanks for the feature request! Can you update your issue with instructions on how to reproduce what isn't working for you?

**Comment by arodic** [comment]
There is a related [issue](https://github.com/PolymerLabs/polyserve/issues/47) in polyserve project although it hasn't been addressed since February. Also found a closed issue #302 here.

I'd suggest to keep this issue open until polyserve [issue](https://github.com/PolymerLabs/polyserve/issues/47) has been addressed and appropriate argument mapping implemented in polymer-cli.

**Comment by TimvdLippe** [comment]
[This pullrequest](https://github.com/PolymerLabs/polyserve/pull/98) seems to resolve this issue.

**Comment by TimvdLippe** [comment]
Polyserve has been updated and now can use http2. I think this issue can be closed.

**Comment by FredKSchott** [comment]
Whoops I thought we closed this. This was fixed on master and will be pushed out soon. Thanks!
