### ISSUE TITLE
bundled files not present after build (compiling from source, latest master) 

### ISSUE THREAD

**Issue by christophe-g** [Polymer/polymer-cli#328]
I could not get any bundled files after a build  - using a version build from source against 66d0350. 

I am not getting any error message, but the shell and fragment  bundled files are absent from the bundled directory. It is as if the build process exists  after composing the dependency tree (no vulcanization seem to happen). 

The last output from `--verbose` option is : 
```sh
debug:   dependency has already been pushed, ignoring... 
{ dep: 'src/widget/pattern-icon.html' }
```
Cheers,
C.

npm@3.6.0
node@v5.6.0
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian

**Comment by christophe-g** [comment]
The reason for this happening was an unresolved href link (`<link rel="import" href="../../bower_components/polymer/polymer.html">` instead of `<link rel="import" href="../../../bower_components/polymer/polymer.html">` for one of my component...

Would help if the build process outputs some error message when this is happening.

Thanks,
C.

**Comment by FredKSchott** [comment]
Closing as fixed!

@christophe-g So did build silently fail to include `../../bower_components/polymer/polymer.html`? I agree it would be much more helpful to log an error (or warning) in that case.
