### ISSUE TITLE
Bug: polymer init asks for app name and then ignores it

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer-cli#343]
Sometimes I initialize new applications using `polymer init`. During the initialization process, it asks me what the name of my app is, and then after that it asks me what my main element should be called.

### What I expected to happen

The default suggestion for the main app element is based on the app name I just provided.

### What actually happened

The default suggestion for the main app element is based on the name of the current working directory where I am running the command.

### Example

![image](https://cloud.githubusercontent.com/assets/240083/17444434/c7b419a6-5af4-11e6-96fe-a25d0a9103b0.png)

**Comment by FredKSchott** [comment]
arg, I can reproduce too 😕 I'll look into this

**Comment by FredKSchott** [comment]
Good news: it is still persisting your application name, it just doesn't base the main element name default off of that.
