### ISSUE TITLE
images folder not included after running polymer build

### ISSUE THREAD

**Issue by Momoumar** [Polymer/polymer-cli#346]
### Versions & Environment

- Polymer CLI: 0.13
- node: v4.4.7
- Operating System: Mac OSx 10.11.6

#### Steps to Reproduce

1. Create an application project: `polymer init application`
2. Build: `polymer build`

#### Expected Results

The folder  build/bundled/images/ should be present

#### Actual Results

The folder  build/bundled/images/ is not present

**Comment by justinfagnani** [comment]
Is images/ in src/?

**Comment by Momoumar** [comment]
@justinfagnani nope, images/ is in the home directory, same level as src/.

**Comment by FredKSchott** [comment]
include non-`src` source files directly via the `--sources` argument. In the next version of polymer-cli, you will also be able to define these in your `polymer.json` file.

```
polymer build --sources index.html src/ images/
```

you can always run `polymer help build` to find out more about the different CLI arguments available.

**Comment by arodic** [comment]
The following command did not copy images as expected (latest polymer-cli):
```
polymer build --sources index.html src/ images/
```
It appears that the toolbox demo is therefore broken. Since this [page](https://www.polymer-project.org/1.0/start/toolbox/deploy) assumes images are present in bundled directory after running ```polymer build```

**Comment by FredKSchott** [comment]
Ah you're right, we thought this was supported but it wasn't. Please see https://github.com/Polymer/polymer-cli/pull/374 for the fix in progress.
