### ISSUE TITLE
Polymer build with ES6 code

### ISSUE THREAD

**Issue by ansarizafar** [Polymer/polymer-cli#348]
I am using es6 code in my custom elements but it seems polymer build command doesn't support es6. Is there any plan in near future to officially support es6 in build process?

**Comment by FredKSchott** [comment]
Polymer CLI uses `uglify` internally to minify your builds. Uglify doesn't currently support ES6 code.

Take a look at `polymer-build`, which you can use to define your own build pipeline. In this you could compile ES6 down to ES5 before running it through uglify, or you could replace uglify with a minifier that can handle es6 code.

**Comment by ansarizafar** [comment]
@FredKSchott Could you please share a sample.

**Comment by FredKSchott** [comment]
Polymer-starter-kit has a good gulp file to look at: https://github.com/PolymerElements/polymer-starter-kit/blob/psk2/gulpfile.js

You can also look at how the CLI uses polymer-build internally: https://github.com/Polymer/polymer-cli/blob/master/src/build/build.ts

we're currently working on documentation and examples for the repo, but for now those two should help get you started.
