### ISSUE TITLE
Can't scaffold custom generator by name

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer-cli#352]
### Description
I can't use the command `polymer init custom-build` to scaffold my generator.

Generator repo:
https://github.com/PolymerElements/generator-polymer-init-custom-build

Running `polymer init` does display the name `custom-build` but if I run `polymer init custom-build` I get errors.

```
info:    Running template polymer-init-custom-build:app...
error:   Template polymer-init-custom-build:app not found
error:   cli runtime exception: Error: Template polymer-init-custom-build:app not found
error:   Error: Template polymer-init-custom-build:app not found
    at /Users/robdodson/.nvm/versions/node/v6.3.0/lib/node_modules/polymer-cli/lib/init/init.js:164:19
```

Maybe the issue is because I'm not using the subgenerator `:app`?
Maybe if that sub generator doesn't exist CLI could throw a warning and the docs could mention I need a `:app` subgenerator

**Comment by robdodson** [comment]
The fix was to use the structure `generators/app`

**Comment by FredKSchott** [comment]
Yea that seems a bit strict, we can look into improving this if the need is there

**Comment by maisnamraju** [comment]
I also have the same issue, it shows up on yo command but otherwise I am unable to get it running.

**Comment by robdodson** [comment]
@maisnamraju if you follow the structure of https://github.com/PolymerElements/generator-polymer-init-custom-build it should work. Just put your templates files in `generators/app`
