### ISSUE TITLE
polymer serve messaging when bower.json is not present could stand to be improved

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer-cli#357]
![image](https://cloud.githubusercontent.com/assets/240083/17563314/ad7522c2-5ee3-11e6-9a2d-ed98a1dceea5.png)

When running `polymer serve` in a directory that does not contain a `bower.json` configuration, some relevant messaging is provided by the CLI to warn the user of this condition.
### What I expected to happen

`polymer serve` warns me that the expected `bower.json` is not available, but assures me with natural language that `polymer serve` will still work despite this condition.
### What actually happened

`polymer serve` echos the raw error. This error is formatted as JSON, suggesting it was potentially unexpected. `polymer serve` continues to work just fine, although no natural language assurance of this is given.

**Comment by FredKSchott** [comment]
+1, right now it feels like every bugs / human error manifests as a "no such file or directory" Error. This is on our roadmap to improve across the entire CLI.
