### ISSUE TITLE
Bug: Polymer CLI prompts for upgrade to its own version

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer-cli#362]
![image](https://cloud.githubusercontent.com/assets/240083/17606435/580b2376-5fd4-11e6-8032-a82ddb35cc02.png)

After installing a new Polymer version (v0.14.0), I checked the version of the CLI with `polymer --version`

### What I expected to happen

The version is reported. If there is a greater version than the reported version available to be installed, a prompt notifying of the new available version is shown.

### What actually happened

The version is reported. A prompt recommending I upgrade to the version I already have is shown.

Note: this is very difficult to reproduce, but I suspect it might happen if you check the version immediately after you upgrade from v0.13.0 to v0.14.0.

**Comment by FredKSchott** [comment]
Seems to be discussion around this in the tool we use: https://github.com/yeoman/update-notifier/issues/67 (& linked issue in comments).

We're not doing much other than calling the update=notifier library, so I'd be surprised if its something wrong on our end. Maybe related to the "cannot kill" bug? I'll try to find some time to dig into this.

**Comment by FredKSchott** [comment]
This seems relatively uncommon and minor. We'll wait for the fix to come downstream through update-notifier unless we start seeing this more often.
