### ISSUE TITLE
base href corrupts index.html output

### ISSUE THREAD

**Issue by CaptainCodeman** [Polymer/polymer-cli#363]
### Description
Adding a `<base href>` element to index.html doesn't work correctly. Use case is loading static assets from a different domain to the index.html request.

### Versions & Environment
- Polymer CLI: 0.14.0
- node: v6.2.1
- Operating System: Mac OS X

#### Steps to Reproduce
1. Add `<base>` tag to index.html:
```
<title>My App</title>
<base href="https://mycdn/">
<meta charset="utf-8">
```
2. Build: `polymer build`

#### Expected Results
The `<base>` tag should survive the build intact

#### Actual Results
The `<base>` tag is stripped and the following meta-tag is corrupted making the html invalid:
```
<title>My App</title>
<meta="" charset="utf-8">
```

**Comment by FredKSchott** [comment]
Not sure what step in our build pipeline is causing this by looking at it. It looks like it's more of a problem with HTML parsing or bundling, or potentially in html-minifier. 

/cc @usergenic who's been looking into supporting the base tag more in general

**Comment by CaptainCodeman** [comment]
Thanks, I'll see if I can play around with the polymer-build to find out exactly where it's happening.

**Comment by CaptainCodeman** [comment]
Well, I just tried it again today and it's working fine now so maybe something upstream got updated to solve the issue.

**Comment by FredKSchott** [comment]
🎉  woo! We'll keep an eye out for this anyway just in case. Thanks for following up @CaptainCodeman
