### ISSUE TITLE
Build folder does not contain images and manifest

### ISSUE THREAD

**Issue by grandstop** [Polymer/polymer-cli#376]
### Description
Build ignores polymer.json configuration
```
{
  "entrypoint": "index.html",
  "shell": "src/my-app.html",
  "fragments": [
    "src/my-view1.html",
    "src/my-view2.html",
    "src/my-view3.html",
    "src/my-view404.html"
  ],
  "sourceGlobs": [
   "src/**/*",
   "images/**/*",
   "bower.json"
  ],
  "includeDependencies": [
    "manifest.json",
    "bower_components/webcomponentsjs/webcomponents-lite.min.js"
  ]
}
```
### Versions & Environment
- Polymer CLI: v0.14.0
- node: v6.4.0
- Operating System: Windows 10

#### Steps to Reproduce
1. Create an application project: `polymer init starter-kit`
2. Build: `polymer build`

#### Expected Results
The images will be there in the build folders, and the manifest.json should be there too.

#### Actual Results
Both the bundled and unbundled build don't have the images folder and the manifest.json resulting to 404 issues.

**Comment by FredKSchott** [comment]
This is a known problem that we're actively working on (although I can't find any past issues on github atm). 

See fix here: #374

**Comment by FredKSchott** [comment]
Fixed in v0.16.0 (just pushed out)

**Comment by abdonrd** [comment]
@FredKSchott `manifest.json` should be in `includeDependencies` or in `sourceGlobs `?

**Comment by grandstop** [comment]
In the latest custom build the manifest.json reside in sw-precache-config.js

```javascript
module.exports = {
  staticFileGlobs: [
    '/index.html',
    '/manifest.json',
    '/bower_components/webcomponentsjs/webcomponents-lite.min.js'
  ],
  navigateFallback: '/index.html'
};
```

**Comment by grandstop** [comment]
Comfirmed the latest starter-kit v2 resolved this issue.
