### ISSUE TITLE
How to extend polymer serve?

### ISSUE THREAD

**Issue by davidsteinberger** [Polymer/polymer-cli#387]
_From @davidsteinberger on August 30, 2016 20:40_

Is there a possibility to extend `polymer serve` or is there a standard _escape hatch_ (similar to the default gulp tasks that replaces `polymer build`) to spin up a development proxy to directly work with backend apis?

_Copied from original issue: PolymerElements/generator-polymer-init-custom-build#29_

**Comment by davidsteinberger** [comment]
_From @robdodson on August 30, 2016 21:17_

I think this is more of a Polymer CLI question. Would you mind moving the issue to https://github.com/Polymer/polymer-cli ?

**Comment by FredKSchott** [comment]
How would you like to extend `polymer serve`? 

The cli `serve` command is a pretty light wrapper around [polyserve](https://github.com/PolymerLabs/polyserve). Looking into using that library directly would be a good first step towards building your own serving logic.

**Comment by davidsteinberger** [comment]
That's exactly what I did. I just found it weird at first to have a cli and then fall back to own gulp tasks for build and serve. Thinking about it a bit more, this is probably the most flexible solution (although I still like how much e.g. the ember-cli gives u out of the box).

**Comment by FredKSchott** [comment]
@davidsteinberger the Polymer CLI is still in its early development and we're constantly adding new features and fix bugs as we work towards v1.0.  Contrast that with a tool like the ember-cli, which is 2+ years old. 

Providing the tools that the CLI wraps gives our users a ton of control over these tasks without having to build every possible configuration option into the CLI. As our tooling matures, we'll be bringing the most common customizations to building, serving, etc. back into the CLI.

**Comment by FredKSchott** [comment]
Closing as resolved

**Comment by davidsteinberger** [comment]
Sorry, forgot to close. Just wanted to add that I've been using it for the last 2 weeks and I now love the flexibility it provides!

**Comment by FredKSchott** [comment]
Really happy to hear that @davidsteinberger 😄 Thanks for following up!
