### ISSUE TITLE
Description not shown in Yeoman generated templates

### ISSUE THREAD

**Issue by samiheikki** [Polymer/polymer-cli#389]
### Description
Using `polymer init` and selecting a template generated with Yeoman, the description is not shown.

### Versions & Environment

- Polymer CLI: 0.16.0
- node: v4.2.4
- Operating System: Windows 10

#### Steps to Reproduce

1. `npm install -g polymer-cli generator-polymer-init-custom-build`
2. `polymer init`
3. Description of `custom-build` is not shown

#### Expected Results
Description from package.json should be shown as the description

#### Actual Results
![no_description](https://cloud.githubusercontent.com/assets/8615573/18126020/f5a087a4-6f81-11e6-889d-f58db2cf4617.PNG)

**Comment by FredKSchott** [comment]
Thanks for reporting! This is already being tracked here (https://github.com/Polymer/polymer-cli/issues/351) and a fix was recently merged for v0.17.0 here (https://github.com/Polymer/polymer-cli/pull/360)

**Comment by samiheikki** [comment]
Thanks @FredKSchott
