### ISSUE TITLE
Minify HTML and CSS in unbundled build

### ISSUE THREAD

**Issue by greenyouse** [Polymer/polymer-cli#397]
### Description
There currently isn't any minification for HTML or CSS in the unbundled build. Could this be added to improve the file sizes? That would still be compatible with HTTP/2 since the files aren't being concatenated together.

### Versions & Environment
- Polymer CLI: 0.16.0
- node: 6.3.1
- Operating System: Linux

#### Steps to Reproduce
1. Create the shop app: `polymer init shop`
2. Build: `polymer build`
3. Inspect: `less build/unbundled/src/shop-app.html`

#### Expected Results
Each application file has HTML, CSS, and JavaScript minified.

#### Actual Results
Only the JavaScript is minified.

**Comment by qqiao** [comment]
Have you looked at polymer-build project? https://github.com/Polymer/polymer-build

It gives you much better control in terms of what you can do at each step.

**Comment by FredKSchott** [comment]
HTML minification should be happening, do you see any warnings in your file output? There is a known bug stopping CSS minification so that should be expected for the moment.

**Comment by greenyouse** [comment]
Sorry, this was completely my fault. I didn't notice the `html.collapseWhitespace` flag. Besides the CSS bug that you mentioned this looks like it's working just fine.
