### ISSUE TITLE
print warning if bower is not installed after initializing an element

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/polymer-cli#40]
When bower is available globally, `polytool` conveniently installs all of the bower dependencies after generating the element files and directories. When bower's not available, `polytool` just silently skips this step. It should, instead, print a warning indicating that the element's dependencies have not been installed because `bower` is not available.

**Comment by justinfagnani** [comment]
@addyosmani do you know if there's an easy way to get Yeoman to do this? I'm just calling `this.bowerInstall()`

**Comment by justinfagnani** [comment]
This is related to #57

**Comment by FredKSchott** [comment]
we should look into switching from .bowerInstall() to .installDependencies() instead
see: http://yeoman.io/generator/Base.html
its a bit smarter

**Comment by justinfagnani** [comment]
Since we're just delegating to Yeoman here, I think we can close for now. If `installDependencies` isn't working well enough, or we have some specific different behavior we want to implement, we can open again.
