### ISSUE TITLE
Build error on starter-lit project

### ISSUE THREAD

**Issue by phidias51** [Polymer/polymer-cli#401]
I created a new application using **polymer init starter-kit** using version 0.16.0.  When I ran **polymer build**, I got this error:

```
error:   Uncaught exception: Error: ENOENT: no such file or directory, open '/Users/markfortner/Documents/workspace_aspen/aspen_website/bower_components/polymer/polymer.html'
error:   Error: ENOENT: no such file or directory, open '/Users/markfortner/Documents/workspace_aspen/aspen_website/bower_components/polymer/polymer.html'
    at Error (native)

```

Looking at the default project directory layout, it appears that the **bower_components** directory is buried one level deeper than expected in the **/app** directory.  This also causes problems when attempting to run the project directly without building it.

**Comment by FredKSchott** [comment]
I've run into this before myself, it's usually because an older project's `.bowerrc` file is still in your directory (`rm -rf *` won't delete dotfiles). Delete that file and bower should install properly.
