### ISSUE TITLE
caching strategy for Rest API data in Polymer cli

### ISSUE THREAD

**Issue by prithviraju1369** [Polymer/polymer-cli#405]
In polymer.json file, as mentioned in Readme.md, caching for the htmls & src files are available. But how to configure Caching strategy for data coming from server in polymer.json file through polymer cli

**Comment by FredKSchott** [comment]
I'm sorry I don't understand your issue. Could you include an example of the behavior you're interested in?

**Comment by prithviraju1369** [comment]
For Example [Polymer Shop APP](https://github.com/Polymer/shop) 

it has its JSON data coming from **data** directory(folder), if you observe the project in github source code. But in a real case, if i have a node rest api end point on server sending data. how do i cache incoming json data using service workers when i use polymer-cli

**Comment by FredKSchott** [comment]
Okay, I think I understand your problem better. However the Polymer CLI currently delegates service worker generation to the https://github.com/GoogleChrome/sw-precache library. Here's a similar question asked in their repo, with an answer from the team: https://github.com/GoogleChrome/sw-precache/issues/165#issuecomment-244844081

>You can't, really, if you're using the Firebase Web Socket interface. Web Socket calls bypass the service worker completely.
>
>If you are using the REST interface, then it's possible to have the service worker intercept those calls, but it's not necessarily going to be the best approach (and it forces you to use REST instead of the realtime API).
>
>Instead, what I'd recommend doing is using IndexedDB to handle offline scenarios. Unfortunately, this isn't officially baked into the Firebase JavaScript SDK at the moment, so you'll have to roll your own solution.
>
>https://www.youtube.com/watch?v=srdKq0DckXQ is @addyosmani's talk from Google I/O 2016, that goes into some detail on how he accomplished this in a sample app. You can also take a look at the open source code for the Google I/O Web App, which implements IndexedDB queueing for all read and write operations to handle offline scenarios: https://github.com/GoogleChrome/ioweb2016/blob/master/app/scripts/helper/firebase.js


Adding our own service-worker generator is not something we're interested in pursuing, so unfortunately we won't be able to help you implement this. I would recommend following their suggestion to cache API data through some other method (IndexDB, etc).

**Comment by prithviraju1369** [comment]
okay . thank you
