### ISSUE TITLE
Roadmap: Polymer CLI too constraining

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer-cli#409]
_From @akc42 on June 4, 2016 11:57_

I have a polymer project which consists of both a client app AND a nodejs server based on using http/2.  The new polymer cli is a great tool for dealing with the client side of the app, but it is annoying that I am forced to create a bundled build when actually all I really want is the unbundled one.

The other strange decision is for each element of an application to need its own directory..  I could understand this approach if the idea was that tests were also contained with the element, but given that the test directory is separate it would seem to me that I could easily support 200 custom elements in a single directory without feeling the need for a directory hierarchy..  

_Copied from original issue: Polymer/project#25_

**Comment by filaraujo** [comment]
i agree with the above, however I would like to be able to have each component in its own directory w/ tests in the same component directory.  

I guess a way to provided resource mapping would be nice

**Comment by FredKSchott** [comment]
@akc42 Thanks for the feedback! Our current plan is to simplify the build step to perform a single type of build by default.

As for elements needing their own directory, I'm not sure if I understand what you mean. As far as I'm aware, projects can have multiple elements in any directory. For example, the Polymer Shop demo application has one big [`src`](https://github.com/Polymer/shop/tree/master/src) directory of all elements.

**Comment by akc42** [comment]
@FredKSchott doing a `polymer init` with the application template you end up with a `test` directory and a `src` directory, but the first element is in its own subdirectory beneath `src`.  I was suggesting that it should just be an element in the `src` directory.  No need for another subdirectory.  My current project which is about 1/3 completed has about 60 element files directly under src.  Very easy to manage that way and I might only add one layer of heirarchy if I do get up near the 200 element mark. I would have found it particular difficult when I am continually cross referring between the elements to not have them all in the same directory (using Sublime Text).

**Comment by FredKSchott** [comment]
@akc42 I agree, nesting all elements under `src/` would remove some unnecessary boilerplate from such a simple app.

**Comment by filaraujo** [comment]
I think it should be flexible enough not to assume a rigid directory structure, but instead allow of a configuration object to be set. I currently work on several polymer projects and our largest runs over 250 elements. For these projects we expect that our `app` directory contains a `component` directory with all element nested within it. Also each of the element directories house their own mocks, integration tests, unit tests and demo logic.  

We currently deploy a great deal of A/B testing and need the flexibility of being to easily add/remove elements without having to worry about left over artifacts. This folder structure allows us that freedom, and should be supported


```
|-- app
|    | --components
|    |    |-- some-element
|    |    |__ some-element2
|    |         |-- demo
|    |         |-- tests
|    |
|    |-- scripts
|
|-- build
```

**Comment by web-padawan** [comment]
I agree that nesting directories is a good idea. In our team it looks like this:

```
src/
|
|-- components/ 
|   |-- app/
|   |   |-- pack-app/   # Root endpoint required by index.html
|   |
|   |-- core/               # Smart components for app logic
|    |    |-- some-element
|    |    |__ some-element2
|    |         |-- tests
|   |   ...
|   |
|   |-- layout/             # Layout components, used on different pages
|   |-- pages/             # Page endpoints, lazy loaded by router
|   |-- shared/            # Reusable dummy components
```
This should be accepted by build tools, and PSK could also encourage developers to use detailed structure (instead of putting all elements in the same folder).

**Comment by phidias51** [comment]
According to the templates, the file structure you get is something like this:
src
bower_components
index.html

where the src directory seems to contain the top-level shards for the app. We typically use bower_components for external components, and have a"corp_components" directory for internally developed components.

**Comment by justinfagnani** [comment]
I'm going to close this as stale. The CLI doesn't require a bundled build, and doesn't really have any opinion on the directory structure of a project, outside of what the templates contain at least.
