### ISSUE TITLE
Installation / documentation Issues

### ISSUE THREAD

**Issue by RobMaskell** [Polymer/polymer-cli#421]
Tried to install CLI and Polymer starter-template using the instructions on this page

https://www.polymer-project.org/1.0/start/toolbox/set-up

but it's missing the command to install bower, the bower install command at the end of the process then fails silently and so when you run polymer server --open you get the html but no web app just a blank grey page.

I'm on version 0.16.0

**Comment by FredKSchott** [comment]
I'm not sure I follow, can you share some steps for us to reproduce?

**Comment by RobMaskell** [comment]
Vanilla Elementary Linux as I'm setting up my dev environment again after installing Loki.

I was following the instructions on this page https://www.polymer-project.org/1.0/start/toolbox/set-up and when I ran 'polymer server --open' I saw just a grey web page, the html for index.html was there but polymer was not doing anything.

The problem seems to be that the page referenced doesn't mention the bower install and update command that when I tried it made the whole thing work, so I was just suggesting you might want to update the docs for page one, page three already has the bower install command but I needed to do it earlier than that in the process to make the starter kit template work.

**Comment by FredKSchott** [comment]
Okay I think I understand. `polymer init starter-kit` will try to run `bower install` after initialization. Can you share your output from running the init command?

As an even better fix, we could check that bower was installed and throw an error before running, asking the user to install bower before running the init command.
