### ISSUE TITLE
Update ES2015 codelab

### ISSUE THREAD

**Issue by dandv** [Polymer/polymer-cli#422]
https://codelabs.developers.google.com/codelabs/polymer-es2015/index.html? points to v1.3.0. Would be nice to mention that we're at v2 now, before updating the codelab to use it.

**Comment by FredKSchott** [comment]
This issue was moved to googlecodelabs/psk-es2015#15

**Comment by FredKSchott** [comment]
Moved to psk-es2015

**Comment by FredKSchott** [comment]
Thanks for finding this, moving to psk-es2015 repo

**Comment by dandv** [comment]
> Thanks for finding this, moving to psk-es2015 repo

Thanks for moving this! You'd be amazed how often I report an issue and get told that it's in the wrong repo. Bonus points if I'm told where to move it. The devs actually moving it themselves... :clap:

**Comment by FredKSchott** [comment]
😊
