### ISSUE TITLE
Unresolved import paths should be caught by linter

### ISSUE THREAD

**Issue by bendavis78** [Polymer/polymer-cli#424]
If an import path does not resolve to an existing file, the linter throws an exception, rather than logging a proper error message:

    ERROR finding /home/ben/Projects/foo/foo-element.html
    Error: ENOENT: no such file or directory, open '/home/Projects/foo/foo-element.html'
        at Error (native)

This makes it difficult to integrate the linter with IDE's, since a missing file crashes the linter and all other errors and warnings are swallowed (also, the line/col is not reported).

The error should instead read:

    my-app.html:4:0
        could not find file referenced in import 'foo-element.html'

**Comment by bendavis78** [comment]
Moved to Polymerlabs/polylint#147

**Comment by justinfagnani** [comment]
Thanks for moving this!
