### ISSUE TITLE
I can't Install Polymer 

### ISSUE THREAD

**Issue by karangoswami31** [Polymer/polymer-cli#427]
Hi I am trying to install the Polymer by Npm and faceing issue 

G:\mydir>npm install -g polymer-cli
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.
isArray.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:78:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:87:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:98:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  polymerelements/test-fixture resetting remote C:\Users\ka
ran\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-f
ixture-git-4485c51b because of error: { [Error: not found: git] code: 'ENOGIT' }

npm ERR! git clone --template=C:\Users\karan\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git://github.com/polymerelements/test-fixture.git C:\Use
rs\karan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-t
est-fixture-git-4485c51b: undefined
npm ERR! git clone --template=C:\Users\karan\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git://github.com/polymerelements/test-fixture.git C:\Use
rs\karan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-t
est-fixture-git-4485c51b: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:78:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:87:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:98:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  polymerelements/test-fixture resetting remote C:\Users\ka
ran\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerelements-
test-fixture-git-a8830b55 because of error: { [Error: not found: git] code: 'ENO
GIT' }
npm ERR! git clone --template=C:\Users\karan\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror https://github.com/polymerelements/test-fixture.git C:\U
sers\karan\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerel
ements-test-fixture-git-a8830b55: undefined
npm ERR! git clone --template=C:\Users\karan\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror https://github.com/polymerelements/test-fixture.git C:\U
sers\karan\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerel
ements-test-fixture-git-a8830b55: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:78:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:87:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:98:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  polymerelements/test-fixture resetting remote C:\Users\ka
ran\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-f
ixture-git-8142662e because of error: { [Error: not found: git] code: 'ENOGIT' }

npm ERR! git clone --template=C:\Users\karan\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users
\karan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-tes
t-fixture-git-8142662e: undefined
npm ERR! git clone --template=C:\Users\karan\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users
\karan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-tes
t-fixture-git-8142662e: undefined
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "polymer-cli"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\mydir\npm-debug.log

please provide me solution

### Versions & Environment

- Polymer CLI:
- node:
- Operating System:

**Comment by web-padawan** [comment]
You must install [git](https://git-scm.com/download/win), which is required by some of dependencies. This is not a `polymer-cli` problem, but should be listed in prerequisites.

**Comment by karangoswami31** [comment]
I have install Git =>   Git-2.10.0-64-bit 
still i am facing same Issue

**Comment by web-padawan** [comment]
@karangoswami31 check if `git` is added to the PATH variable. 
And did you opened a new terminal after installing git? Sometimes PATH variables are only reloaded after re-opening command prompt. See [this question](http://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows) for details.

**Comment by FredKSchott** [comment]
@web-padawan thanks for looking into this. @karangoswami31 Sergey is correct, git is not in your system path. Please see this section of your logs:

```
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
```

This is an npm & git issue. There is nothing we can do in the polymer-cli to fix this for you. Please see this [this question](http://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows) for the solution.
