### ISSUE TITLE
canonical location for sub-elements in an element project

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/polymer-cli#44]
Suppose that I'm building an element for distribution, which itself is composed of smaller elements that are specific to this element. I have no plans to use the smaller elements in any context outside of this element. 

E.g. my top-level element is `chatbox-widget` which is composed of `chatbox-message` elements. 

Where does `polytool` expect `chatbox-message` to reside within my element project? In a directory
named `chatbox-message`? I.e.

```
chatbox-widget/
|--chatbox-widget.html
|--chatbox-message/
   |--chatbox-message.html
```

At the top-level? I.e.

```
chatbox-widget/
|--chatbox-widget.html
|--chatbox-message.html
```

**Comment by justinfagnani** [comment]
Top-level seems to be how it's done in the PolymerElements org. I think the reason is so that "sub-elements" are also easily importable.

I think this is consistent enough to go ahead and doc across polytool and other docs, but you may want to check in with the broader team.

**Comment by justinfagnani** [comment]
@kaycebasques is this enough info?

**Comment by kaycebasques** [comment]
@justinfagnani yes, thanks
