### ISSUE TITLE
'polymer build' does not throw error if fragment path is incorrect in polymer.json.

### ISSUE THREAD

**Issue by CDDelta** [Polymer/polymer-cli#447]
### Description

Polymer CLI does not throw an error when the path I inputted in 'fragments' of polymer.json is incorrect. This causes the entire build to not complete and the service worker to not be generated.
### Versions & Environment
- Polymer CLI: 0.16.0
- node: v6.9.1
- Operating System: Windows 10
#### Steps to Reproduce
1. Create an application project: `polymer init application`
2. Edit an invalid entry into fragments in polymer.json.
3. Run `polymer build`.
#### Expected Results

Polymer CLI to throw an error that the fragment path is invalid.
#### Actual Results

No error is thrown and some fragments are left out. The service worker is also not generated.

**Comment by vtellier** [comment]
Possible same problem than #398 ?

**Comment by CDDelta** [comment]
That does not seem to be the case as there is no error thrown. The issue
also seems to only happen when the path to the fragment in polymer.json is
wrong.
On Thu, 27 Oct 2016 at 4:16 AM, Vincent Tellier <notifications@github.com>
wrote:

Possible same problem than #398
<https://github.com/Polymer/polymer-cli/issues/398> ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Polymer/polymer-cli/issues/447#issuecomment-256416715>,
or mute the thread

**Comment by CDDelta** [comment]
Although deltaepsilon's issue sounds similar to the one I encountered
except mine is concerning app fragments instead of the dependancies of
fragments.

**Comment by n1ywb** [comment]
getting this as well, with my CLI starter kit based app; one wrong path in polymer.json fragments == silent failure.

    $ polymer --version
    0.17.0

**Comment by FredKSchott** [comment]
This is fixed by the new analyzer, which you can try out via `npm install -g polymer-cli@next`. We're working to get this published to the master npm branch soon
