### ISSUE TITLE
i can't install polymer in Window 10

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer-cli#449]
_From @karangoswami31 on October 25, 2016 12:55_

Help me out i can't install Polymer

D:>npm install -g polymer-cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\karan\AppData\Roaming\npm\polymer -> C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\bin\polymer.js

> sauce-connect-launcher@0.16.0 postinstall C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\sauce-connect-launcher
> node scripts/install.js || nodejs scripts/install.js
> 
> wct-sauce@1.8.5 postinstall C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\wct-sauce
> node scripts/postinstall.js

Prefetching the Sauce Connect binary.
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
 npm WARN install:wct-sauce@1.8.5 wct-sauce@1.8.5 postinstall: `node scripts/postinstall.js`
npm WARN install:wct-sauce@1.8.5 Exit status 1
C:\Users\karan\AppData\Roaming\npm
`-- polymer-cli@0.16.0
`-- web-component-tester@4.3.5
    `-- test-fixture@1.1.1  (git://github.com/polymerelements/test-fixture.git#05514d6f32ade6fe54de5b242bbb43ea9dcff3c0)

_Copied from original issue: Polymer/polymer#4093_

**Comment by kevinpschaaf** [comment]
_From @TimvdLippe on October 25, 2016 13:20_

Please ask such questions on the Polymer Slack (https://polymer-slack.herokuapp.com/) or on Stackoverflow (http://stackoverflow.com/questions/tagged/polymer).

**Comment by FredKSchott** [comment]
It looks like your machine is having trouble downloading sauce. Do you know if your computer connects to the internet through a proxy?

**Comment by jordyvandomselaar** [comment]
I have the same problem. Sauce seems to download just fine. 
`    C:\Users\jordy>npm install -g polymer-cli
    npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
    npm WARN deprecated node-uuid@1.4.7: use uuid module instead
    C:\Users\jordy\AppData\Roaming\npm\polymer -> C:\Users\jordy\AppData\Roaming\npm\node_modules\polymer-cli\bin\polymer.js

    > sauce-connect-launcher@1.1.1 postinstall C:\Users\jordy\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\sauce-connect-launcher
    > node scripts/install.js || nodejs scripts/install.js


    > wct-sauce@1.8.6 postinstall C:\Users\jordy\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\wct-sauce
    > node scripts/postinstall.js

    Prefetching the Sauce Connect binary.
    Missing Sauce Connect local proxy, downloading dependency
    This will only happen once.
    Downloading 3.86MB
    Archive checksum verified.
    Unzipping C:\Users\jordy\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\sauce-connect-launcher\sc\sc-4.4.1-win32.zip
    Removing C:\Users\jordy\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\sauce-connect-launcher\sc\sc-4.4.1-win32.zip
    Sauce Connect downloaded correctly
    - glob@5.0.15 node_modules\polymer-cli\node_modules\sauce-connect-launcher\node_modules\glob
    - lodash@3.10.1 node_modules\polymer-cli\node_modules\sauce-connect-launcher\node_modules\lodash
    - rimraf@2.4.3 node_modules\polymer-cli\node_modules\sauce-connect-launcher\node_modules\rimraf
    C:\Users\jordy\AppData\Roaming\npm
    `-- polymer-cli@0.17.0
      +-- @types/inquirer@0.0.30
      | `-- @types/rx@2.5.34
      +-- @types/node@6.0.51
      +-- @types/request@0.0.32
      | `-- @types/form-data@0.0.33
      +-- css-slam@1.2.1
      | `-- dom5@1.3.6
      |   `-- @types/parse5@0.0.31
      |     `-- @types/node@6.0.51
      +-- fs-extra@1.0.0
      | `-- graceful-fs@4.1.11
      +-- polylint@2.10.1
      | +-- dom5@1.3.6
      | | `-- @types/parse5@0.0.31
      | |   `-- @types/node@6.0.51
      | `-- hydrolysis@1.24.1
      |   `-- dom5@1.3.6
      |     `-- @types/parse5@0.0.31
      |       `-- @types/node@6.0.51
      +-- polymer-build@0.4.1
      | +-- dom5@1.3.6
      | | `-- @types/parse5@0.0.31
      | |   `-- @types/node@6.0.51
      | `-- vulcanize@1.14.12
      |   `-- dom5@1.3.6
      |     `-- @types/parse5@0.0.31
      |       `-- @types/node@6.0.51
      +-- request@2.79.0
      | `-- http-signature@1.1.1
      |   `-- sshpk@1.10.1
      |     `-- dashdash@1.14.1
      `-- web-component-tester@5.0.0
        +-- test-fixture@1.1.1  (git://github.com/polymerelements/test-fixture.git#a0d9d6d1fedfdbc715e244ffc6116021256788fe)
        +-- wct-local@2.0.13
        | `-- launchpad@0.5.4
        |   +-- async@2.1.4
        |   `-- restify@4.3.0
        |     `-- bunyan@1.8.5
        |       `-- moment@2.17.0
        +-- wct-sauce@1.8.6
        | `-- sauce-connect-launcher@1.1.1
        |   `-- async@2.1.4
        `-- wd@0.3.12
          `-- archiver@0.14.4
            `-- buffer-crc32@0.2.13


    C:\Users\jordy>cd  Documents\apps

    C:\Users\jordy\Documents\apps>mkdir code_editor

    C:\Users\jordy\Documents\apps>cd code_editor

    C:\Users\jordy\Documents\apps\code_editor>polymer init
    'uname' is not recognized as an internal or external command,
    operable program or batch file.
    error:   cli runtime exception: Error: write EINVAL
    error:   Error: write EINVAL
        at exports._errnoException (util.js:1022:11)
        at WriteStream.Socket._writeGeneric (net.js:715:26)
        at WriteStream.Socket._write (net.js:734:8)
        at doWrite (_stream_writable.js:334:12)
        at writeOrBuffer (_stream_writable.js:320:5)
        at WriteStream.Writable.write (_stream_writable.js:247:11)
        at WriteStream.Socket.write (net.js:661:40)
        at MuteStream.ondata (stream.js:31:26)
        at emitOne (events.js:96:13)
        at MuteStream.emit (events.js:188:7)
    error:   Promise rejection: Error: This socket is closed
    error:   Error: This socket is closed
        at WriteStream.Socket._writeGeneric (net.js:683:19)
        at WriteStream.Socket._write (net.js:734:8)
        at doWrite (_stream_writable.js:334:12)
        at writeOrBuffer (_stream_writable.js:320:5)
        at WriteStream.Writable.write (_stream_writable.js:247:11)
        at WriteStream.Socket.write (net.js:661:40)
        at Console.log (console.js:43:16)
        at module.exports.UI.onForceClose (C:\Users\jordy\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\inquirer\lib\ui\baseUI.js:32:11)
        at emitOne (events.js:101:20)
        at process.emit (events.js:188:7)

    C:\Users\jordy\Documents\apps\code_editor>`

**Comment by FredKSchott** [comment]
@jordyvandomselaar your issue seems different from OP's. Please create a new issue and include the neccessary info.
