### ISSUE TITLE
Build fails when run out of the box

### ISSUE THREAD

**Issue by skamansam** [Polymer/polymer-cli#453]
### Description
Build fails when run out of the box. The path to the polymer.html file is incorrect.

### Versions & Environment
- Polymer CLI: 0.17.0
- node: v4.2.4
- Operating System: Fedora 24

#### Steps to Reproduce
1. Create an application project: `polymer init element`
2. Build: `polymer build`

#### Expected Results
No error is thrown

#### Actual Results
```
info:    Preparing build...
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
error:   Uncaught exception: Error: file path is not in root: /path/to/element/../polymer/polymer.html (/path/to/element)
error:   Error: file path is not in root: /path/to/element/../polymer/polymer.html (/path/to/element/../)
...
```

**Comment by FredKSchott** [comment]
`polymer build` is for building applications for deployment. There is currently no way to build an element since an element is meant to live in `bower_components`. See https://github.com/Polymer/polymer-cli/issues/317 & https://github.com/Polymer/polymer-cli/issues/338 for more discussion

**Comment by nicholaswmin** [comment]
@FredKSchott Then how do we transpile an element to ES5? Are there any guides/tools you can point me to?

**Comment by justinfagnani** [comment]
@nicholaswmin you don't transpile individual elements to ES5. Distribute them as ES6 (since custom elements _must_ be classes, compiling them would break them), then let applications compile to ES5 if necessary, and if they set up the ES5 custom elements adapter so that they will work.

**Comment by nicholaswmin** [comment]
@justinfagnani I didn't mention I was talking about Polymer 1.x which uses the factory method instead of class. Nevertheless I get the point. Thanks.
