### ISSUE TITLE
Can't exit `polymer serve` if npm update notification triggers

### ISSUE THREAD

**Issue by mbleigh** [Polymer/polymer-cli#460]
### Description

If I launch `polymer serve` and get prompted to update the CLI to the latest version via updatenotifier, I am unable to use `Ctrl-C` to exit

### Versions & Environment

- Polymer CLI: 0.16
- node: 6.7.0
- Operating System: Ubuntu

#### Steps to Reproduce

Run `polymer serve` after not updating for a while.

#### Expected Results

I can still use `Ctrl-C` to exit the server after the update displays.

#### Actual Results

I cannot.

**Comment by SPessall** [comment]
+1. I have seen the same behaviour on Windows 7.

**Comment by hatimk** [comment]
Same thing on OS X El Capitan 10.11.6.

**Comment by FredKSchott** [comment]
Thanks for reporting everyone, this is a known issue that we are tracking here: https://github.com/Polymer/polymer-cli/issues/341.
