### ISSUE TITLE
Produce live docs for installed elements (like godoc)

### ISSUE THREAD

**Issue by larsgk** [Polymer/polymer-cli#469]
(Enhancement)

### Description
consider making 'polymer docs' serve a browsable doc tree similar to what godoc does
(https://godoc.org/golang.org/x/tools/cmd/godoc)

As polymer (frontend) and golang (backend) complement each other well - and both google technologies - it would be nice with some alignment :)

Also - I was recently in an airplane (no wifi), coding - and although the source for the bower installed compoents was (of course) searchable and possible to view in the text editor, a nice overview page would have been brilliant.

/cc @notwaldorf

**Comment by FredKSchott** [comment]
Thanks for posting! `polymer serve` will serve component demos and API references for any components you have installed. See https://www.polymer-project.org/1.0/docs/tools/polymer-cli#serve for more info.
