### ISSUE TITLE
Add https support on serve command

### ISSUE THREAD

**Issue by emanuelbsilva** [Polymer/polymer-cli#474]
Hi,

I'm using the app toolbox and because of this line of code`navigator.serviceWorker.register`, when testing using a mobile device, Chrome is triggering the exception: `DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).`.

As you can see in google's explanation, when not using https, only a few wildcards are considered "secure origins":
```
(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)
(chrome-extension, *, —)
```

Unfortunately, when using a mobile device, the only way to test is to point to the machine's IP address running polymer serve. As i see it there are 2 solutions for this problem:

1. Add support for https when running polymer serve. I believe this is the best way to solve the problem because it also makes it future proof for other features that might have the same problem.
2. Remove the registration of the service worker in the development environment. Because the service worker is actually only being used in production, there is no need to event try to register it. If we go by this approach we just need to change the polymer build task to add the service worker registration to the index.html.

What are your thoughts on this? Is there anything else that can be done (ie. regarding network configuration)?

**Comment by FredKSchott** [comment]
Support for https, http2, http2/push was actually added in polyserve v0.14.0. You can see more information here: https://github.com/PolymerLabs/polyserve/pull/98

Would you be interested in updating our cli's version of polyserve, and including new CLI options to match polyserve's?

**Comment by justinfagnani** [comment]
I made the CLI just use polyserve's, so this works now.
