### ISSUE TITLE
Unable to install in Ubuntu Server

### ISSUE THREAD

**Issue by ramanan-java** [Polymer/polymer-cli#505]
### Description

I tired to install **polymer-cli** using npm in my Ubuntu server. But it always stop the process while extracting the polymer package. I am not getting any **waring or error** message and stay back to prompt.
### Versions & Environment

- npm: 4.0.3
- node: v5.12.0
- git: 1.9.1
- Operating System: Ubuntu 14.04.3 LTS

#### Steps to Reproduce

sudo npm install -g -d polymer-cli
#### Actual Results

$ sudo npm install -g -d polymer-cli
npm info it worked if it ends with ok
npm info using npm@4.0.3
npm info using node@v5.12.0
npm info attempt registry request try #1 at 2:59:50 AM
npm http request GET https://registry.npmjs.org/polymer-cli
npm http 304 https://registry.npmjs.org/polymer-cli
npm info addNameTag [ 'polymer-cli', 'latest' ]
...
...
...
npm http 304 https://registry.npmjs.org/multimatch
npm info attempt registry request try #1 at 2:58:08 AM
npm http request GET https://registry.npmjs.org/yeoman-generator
npm http 304 https://registry.npmjs.org/yeoman-generator
npm info attempt registry request try #1 at 2:58:08 AM
npm http request GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/lru-cache
npm info attempt registry request try #1 at 2:58:08 AM
npm http request GET https://registry.npmjs.org/editions
npm http 304 https://registry.npmjs.org/editions
$ / extract:polymer-cli: sill doParallel extract 1081
$

**Comment by FredKSchott** [comment]
Unfortunately this is an issue with  npm on your machine, there's nothing we can do on our side to help you.

Some other users have had trouble with npm and proxies, please search our issues if you think this is the case: https://github.com/Polymer/polymer-cli/search?q=proxy&type=Issues&utf8=%E2%9C%93
