### ISSUE TITLE
Webcomponents-lite V1 is incorrectly inlined during build

### ISSUE THREAD

**Issue by etimberg** [Polymer/polymer-cli#537]
### Description
*I am not sure if this is a webcomponents.js issue or a polymer-cli issue but I think it is more correct to fix this in the CLI.*

When running `polymer build` on a Polymer v2 sample project, `webcomponents-lite.js` v1 is inlined. This breaks the webcomponents polyfill because it expects to be able to find the script path for itself. See `webcomponents-lite.js` [line 18](https://github.com/webcomponents/webcomponentsjs/blob/v1/webcomponents-lite.js#L18)

### Versions & Environment
- Polymer CLI: 0.17.0
- node: v6.9.1
- Operating System: Windows 7 64bit

#### Steps to Reproduce
Assuming your machine already has polymer-cli and bower installed
1. `git clone https://github.com/PolymerLabs/polymer-2-carousel.git`
2. `cd polymer-2-carousel/step-09`
3. `bower install`
4. `polymer build`
5. open `build/bundled/index.html` in FireFox and notice the console errors (image below)

![errors](https://cloud.githubusercontent.com/assets/6757853/21735362/50d3efde-d437-11e6-9568-183d91ca9d5d.png)

The first error is from [line 66](https://github.com/webcomponents/webcomponentsjs/blob/v1/webcomponents-lite.js#L66) of webcomponents-lite.js caused by the failure on line 18 to find the script tag to generate the relative path.

#### Expected Results
I think the expected result is to generate a script tag for `webcomponents-lite.js` instead of inlining the source.

#### Actual Results
On browsers with native WebComponent implementations this error does not cause a problem since the polyfills are not needed. In browsers where the polyfills are needed, the page does not work.

**Comment by justinfagnani** [comment]
You really shouldn't be bundling the polyfills... what's your polymer.json look like?

**Comment by etimberg** [comment]
The sample project I followed has no `polymer.json` file. It may have never intended to be built.

**Comment by FredKSchott** [comment]
@etimberg very strange, we should look into why this is happening. Can you show us how you're importing webcomponents?

Either way, you should be able to solve this by creating a polymer.json configuration for your app, and and including the `webcomponents/` directory as a member of `includeDependencies`. See https://www.polymer-project.org/1.0/docs/tools/polymer-cli#build for more info.

**Comment by etimberg** [comment]
@FredKSchott the sample I was following is https://github.com/PolymerLabs/polymer-2-carousel/tree/master/step-09 

index.html has a script tag for `webcomponents-lite.js` and the `my-carousel` component imports `polymer-element.html`.

**Comment by FredKSchott** [comment]
Ah yea, the bundler would definitely try to bundle that.

Can you try to add a polymer.json with the following, and let us know if that fixes things?

```
{
  "includeDependencies": [
    "bower_components/webcomponentsjs/*"
  ]
}
```

**Comment by etimberg** [comment]
I gave that a try, but it was still inlined. I also tried changing the glob to `"bower_components/webcomponentsjs/webcomponents-lite.min.js"` just to see but it had the same result.

**Comment by FredKSchott** [comment]
Hmm, what if you replace it with something like https://github.com/Polymer/shop/blob/master/index.html#L62,L73 ? Written like that, the analyzer can't read it, which means it won't be inlined. It's a bit of a hack, but would help as a workaround.

**Comment by etimberg** [comment]
@FredKSchott I tried a later version of polymer, `0.18.0-alpha.8` which seems to work fine, even if no `polymer.json` file exists. 

I can go ahead and close this if that's good enough for you.

**Comment by FredKSchott** [comment]
great! That makes sense, we made a lot of good improvements to building in the latest `next` version of the CLI. Hopefully we can get that out more publicly soon.
