### ISSUE TITLE
Polymer build command fails to find files in root path

### ISSUE THREAD

**Issue by ergo** [Polymer/polymer-cli#540]
### Description

`polymer build` command fails to include some files from element during build process, on 0.17 and 0.18.0-alpha.6.

#### Steps to Reproduce

1. Clone https://github.com/ergo/polymer-cli-test
2. Run `bower install`
3. Build: `polymer build`

#### Expected Results
No errors

#### Actual Results
    error:   Promise rejection: Error: file path is not in root: /bower_components/crossroadsjs-router/vendor/signals.js

**Comment by FredKSchott** [comment]
I can reproduce on `0.18.0-alpha.6`, but I'm unable to reproduce in the latest CLI `next` release, `0.18.0-alpha.8`. Can you try on `alpha.8`?

**Comment by ergo** [comment]
Yes, `alpha.8` doesn't throw any visible errors.

**Comment by ergo** [comment]
closing.

**Comment by FredKSchott** [comment]
👍
