### ISSUE TITLE
v0.18.0 Release Plan

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-cli#542]
The latest version of Polymer CLI is now 2+ months old. It contains an old version of build that often  analyzes incorrectly and silently fails. In contrast master currently contains bug fixes, two new commands, a rewritten build process that prints warnings instead of silently failing on errors, and more. 

WCT & Serve are the only two underlying libraries that we're waiting on to hit public release versions. Do we feel comfortable releasing CLI v0.18.0 on top of `pre-` versions of these libraries? I know the variants-related work is still new, but no one outside of our team is using that yet. Is there anything else that might be worth holding up release for?

Releasing would also free me up to merge the new build flags directly into master instead of the current feature branch.

@justinfagnani @rictic wdyt?

**Comment by justinfagnani** [comment]
We should not release with prerelease dependencies. We can get these closed out this week.

**Comment by christophe-g** [comment]
>We can get these closed out this week.

Thank would be fantastic, thanks!

**Comment by FredKSchott** [comment]
Moved to milestone tracking
