### ISSUE TITLE
0.18.0-alpha.9 is not working properly with polymer-starter-kit- or shop-app-example

### ISSUE THREAD

**Issue by fooloomanzoo** [Polymer/polymer-cli#550]
### Description
The bundeled version does not bundle the files.

### Versions & Environment

- Polymer CLI: 0.18.0-alpha.9
- node: 7.4.0
- Operating System: Windows

#### Steps to Reproduce
1. Create an application project: `polymer init polymer-starter-kit`
2. Build: `polymer build`

#### Expected Results
Files that contain the dependencies

#### Actual Results
![image](https://cloud.githubusercontent.com/assets/9318952/22426776/dce501b2-e700-11e6-8b62-8544c1a51bc3.png)

**Comment by tony19** [comment]
This looks like a duplicate of https://github.com/Polymer/polymer-build/issues/114.

**Comment by FredKSchott** [comment]
Yes, duplicate on #114. Working on a fix now
