### ISSUE TITLE
`init` may need to run `npm install`

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-cli#57]
If a template has a gulpfile, `build` will attempt to load it, causing a module not found error if gulp hasn't been installed yet.

**Comment by FredKSchott** [comment]
A quick fix here would just be to check if a node_modules folder exists in the directory.

**Comment by justinfagnani** [comment]
It won't, because `npm i` will have never been run. `package.json` will exist though.

**Comment by FredKSchott** [comment]
Sorry i should have been more clear. `polymer build` could do a quick check to see if the `node_modules/` directory exists in the project. If it does not, it could show a helpful message or even run an `npm install` itself.
