### ISSUE TITLE
polymer init fails with npm installed version of 0.18.0-pre.10

### ISSUE THREAD

**Issue by CaptainCodeman** [Polymer/polymer-cli#576]
### Description
`polymer init` errors when installed with npm

Installing `polymer-cli` and the `tmp` packages locally works. Also using yarn (global install) works too.

### Versions & Environment
- Polymer CLI: 0.18.0-pre.10
- node: 4.1.2
- Operating System: macOS Sierra 10.12.3 

#### Steps to Reproduce
Install 0.18.0-pre.10 using npm:

    npm install -g polymer-cli@next

Then run `polymer init`

#### Expected Results
Prompt for project template to use

#### Actual Results
```
error:   cli runtime exception: Error: Cannot find module 'tmp'
error:   Error: Cannot find module 'tmp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/external-editor/main/index.js:15:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/external-editor/main/index.js:208:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by FredKSchott** [comment]
The fact that the release is passing on Travis@v4 I think this might be an issue with your environment, @CaptainCodeman. Can you do a full uninstall and re-install of the CLI?

```
npm uninstall -g polymer-cli
npm install -g polymer-cli@next
```

**Comment by CaptainCodeman** [comment]
Still gives the same result.

Discussion in Slack suggested it might be todo with `tmp` being in devDependencies (?)

**Comment by jsilvermist** [comment]
Can't reproduce locally using `npm install -g polymer-cli@next` and `polymer init`, template seems to load fine.
Maybe try using node 6 if possible?

**Comment by CaptainCodeman** [comment]
I'm using node v6.2.1 (sorry, didn't think to include it in the original issue)

If I install `tmp` globally (`npm install -g tmp`) then it works but presumably that shouldn't be necessary (?)

**Comment by FredKSchott** [comment]
Ah you're right, travis is hiding this issue by installing dev dependencies.

This is a shrinkwrap issue then, because I don't see tmp anywhere in the shrinkwrap. That would also explain why npm suffers but yarn doesn't. I'll regenerate the shrinkwrap file and see if tmp is added.

**Comment by FredKSchott** [comment]
@rictic @justinfagnani @usergenic I think its safe to say that npm shrinkwrap has caused more trouble than its been worth so far. What do you all think about removing it and blessing yarn for users who want/need a deterministic/reproducible dependency graph? (Yarn's lockfile is easier to maintain and doesn't silently fail like shrinkwrap)

**Comment by FredKSchott** [comment]
suprisingly, this is just an npm bug. After deleting the shrinkwrap and doing a complete `rm -rf node_modules && npm i` tmp is still not installed. 

Funny enough, Running `npm install` a second time does install tmp.

```
$ rm -rf node_modules
$ npm install
$ npm ls
npm ERR! missing: tmp@^0.0.29, required by external-editor@1.1.1
$ npm install
polymer-cli@0.18.0-pre.10
└─┬ inquirer@1.2.3
  └─┬ external-editor@1.1.1
    └── tmp@0.0.29 #installed
```

**Comment by rictic** [comment]
Wow, that's unexpected. What versions of npm does this effect?

As a workaround we can add a direct dependency on `tmp` I suppose.

**Comment by kristianmandrup** [comment]
I had the same problem. Ran the uninstall of polymer-cli then reinstall.

```
npm uninstall -g polymer-cli
npm install -g polymer-cli@next
```

Been using npm 4.4.0 and Node 6.9.1. Still got same error after clean reinstall. 
Worked after running `npm install -g tmp` as noted above.

**Comment by FredKSchott** [comment]
I can no longer reproduce, I believe this has been fixed. Please comment if you are still having trouble
