### ISSUE TITLE
Polymer-CLI starter-kit 404 errors

### ISSUE THREAD

**Issue by ta1188** [Polymer/polymer-cli#577]
When running `polymer init starter-kit` within a new project directory, and then `polymer serve --open` nothing displays. Upon inspecting the console, there are many 404 issues with files under the `bower_components` directory. 

_Example_
>http://localhost:8080/bower_components/polymer/polymer.html Failed to load resource: the server responded with a status of 404 (Not Found)

I had found that there seemed to be an issue with the recognition of the `bower_components` folder path. By moving it to the root project folder, it solved the issue and now successfully serves the project. 

_Note:_ I initially tried to update all the locations I could find referencing the `bower_components` in its path and update them to `app/bower_com...` but it didn't seem to fix the issue. 

If someone knows how to maintain original file structure, but resolve the 404 error, let me know. 
Thanks!

**Comment by jsilvermist** [comment]
You need to run `bower install` from the directory you ran `polymer init` to install all dependencies first.

If you don't have bower, you can install it with `npm install -g bower`.

**Comment by jsilvermist** [comment]
The file `.bowerrc` can be used to change the install location of `bower_components`.

To change the location they install to, add this to `.bowerrc` in the root directory:
```json
{
  "directory": "app/bower_components"
}
```
Or remove it if you require they be install in the default (root directory) location.

**Comment by FredKSchott** [comment]
starter-kit works as expected with the default bower config. You may have a `.bowerrc` left over from a previous installation in your working directory. Unfortunately PSK cannot support every possible path, but this should be fixed by updating all import paths that reference `bower_components` directly.
