### ISSUE TITLE
Lighthouse Fails Test - Redirects HTTP traffic to HTTPS

### ISSUE THREAD

**Issue by homerjonathan** [Polymer/polymer-cli#578]
When checking a website created by using Polymer-Cli default init using Lighthouse it fails an important test of security with the tests reporting that it fails when it ***Redirects HTTP traffic to HTTPS***

So can the default image have some kind of redirect from http: to https: included in the boilerplate code especially when **polymer build** is being used.  Just a simple line below or equivalent.

`    if (location.protocol != 'https:')
    {
        location.href = 'https:' + window.location.href.substring(window.location.protocol.length);
    }`

I feel that the Polymer-Cli should be updated to add this default code in the index.html just before checking the Polymer version etc. as part of the ***polymer init*** process when choosing the _starter-kit_ option etc.

**Comment by web-padawan** [comment]
Please pay attention to that `polymer serve` is not designed to be used in production. You need something like `nginx` or another http server, and you should configure redirects there.

**Comment by tony19** [comment]
I think this is a duplicate of https://github.com/Polymer/polyserve/issues/149.

**Comment by homerjonathan** [comment]
Whilst I know that ***polymer serve*** is not for production.  It still made it very difficult to test our web application because the restful server running it was in production so was properly secure.  In the end we used node-static.

`var static = require('node-static');
var fs = require('fs');
// Create Server with Cache
var fileServer = new static.Server( __dirname + '/build/bundled/', { cache: 100 });

var options = {
    pfx: fs.readFileSync('certificate.pfx'),
    passphrase: "password"
};

require('https').createServer(options, function (request, response) {
    request.addListener('end', function () {
        //
        // Serve files!
        //
        fileServer.serve(request, response);
    }).resume();
}).listen(8080);`

**Comment by FredKSchott** [comment]
Thanks for bringing this us @homerjonathan. This sort of workaround for `https` redirects is outside the scope of our starter templates. There is too much potential to confuse or even break for new users, and many users will want to handle this on the server instead of the app. 

Luckily it is an easy thing to search for and add yourself once you are ready to deploy, especially with Lighthouse.
