### ISSUE TITLE
Integration tests seem to take unusually long

### ISSUE THREAD

**Issue by tony19** [Polymer/polymer-cli#581]
### Description
This might not be a bug: I just updated to tip of master (4936124), and ran `yarn`, which included several integration tests that seem to take over 10 seconds. A couple tests took 50-60 seconds. Is this normal?

### Versions & Environment

- Polymer CLI: 0.18.0-pre.10 (4936124)
- node: 7.6.0
- Operating System: macOS Sierra

#### Steps to Reproduce

Run this command (which includes running the integration tests):
```shell
git clone https://github.com/Polymer/polymer-cli.git
```

#### Expected Results
The test command completes within 1 minute.

#### Actual Results
The test command takes a few minutes to complete.
```
[19:58:45] Starting 'test:integration'...


  install-variants
    ✓ installs variants (1458ms)

  integration tests
    init templates
      ✓ test the polymer 1.x application template (13815ms)
      ✓ test the polymer 2.x application template (19464ms)
      ✓ test the polymer 2.x "element" template (12336ms)
      ✓ test the polymer 1.x "element" template (11544ms)
info:    Finding latest release of Polymer/shop
info:    Downloading v1.1.2 of Polymer/shop
info:    Unpacking template files
info:    Finished writing template files
      ✓ test the "shop" template (17580ms)
info:    Finding latest release of PolymerElements/polymer-starter-kit
info:    Downloading v2.1.2 of PolymerElements/polymer-starter-kit
info:    Unpacking template files
info:    Finished writing template files
      ✓ test the "starter-kit" template (11521ms)
    tools-sample-projects templates
info:    Finding latest release of Polymer/tools-sample-projects
info:    Downloading v0.1.0 of Polymer/tools-sample-projects
info:    Unpacking template files
info:    Finished writing template files
      ✓ test the "polymer-1-app" template (50491ms)
      ✓ test the "polymer-2-app" template (67258ms)

  polymer lint
    ✓ handles a simple correct case (1180ms)
    ✓ fails when rules are not specified (751ms)
    ✓ takes rules from the command line (1109ms)
    ✓ fails when lint errors are found (1061ms)


  13 passing (4m)

[20:02:17] Finished 'test:integration' after 3.52 min
```

**Comment by rictic** [comment]
There's two pieces to this.

1. some of the integration tests hit the network for long `bower install` invocates
2. tests run on the npm `prepublish` hook when you run `npm install`

We should solve both.

The former can be solved passing `--offline` to our `polymer install` calls in the integration tests, and the latter can be solved either by using `prepublishOnly` once we drop support for node 4 in April, or just by dropping running tests in prepublish entirely, and standardize on the convention of only publishing using the `np` tool, which runs tests.

Or both.
