### ISSUE TITLE
npm install -g polymer-cli fails on node

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer-cli#584]
_From @lets-open-source on March 3, 2017 19:57_

```
root@nodejs-512mb-sfo1-01:~# npm -v
3.10.3
root@nodejs-512mb-sfo1-01:~# node -v
v6.5.0
root@nodejs-512mb-sfo1-01:~# npm install -g polymer
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
Killed        .....] - extract:polymer-cli: sill doParallel extract 1192

root@nodejs-512mb-sfo1-01:~# polymer
polymer: command not found
```

Very frustrating because I can't get started with the tutorial docs because of this first step craps out :/

This seems to be a trend in the npm universe. Follow the guide exactly and have it fail. Spend all morning googling for potential fixes but all issues are marked as closed when it hasn't even been fixed.

This will hinder polymer adoption when getting started guide results in a frustrating first impression.

_Copied from original issue: Polymer/polymer#4369_

**Comment by lets-open-source** [comment]
why did you close my issue and created a clone?

**Comment by justinfagnani** [comment]
different repo

**Comment by justinfagnani** [comment]
We don't own the `polymer` package on npm. The Polymer CLI is named `polymer-cli`.

**Comment by che-effe** [comment]
@justinfagnani is `polymer` not the command to utilize polymer cli?

**Comment by jsilvermist** [comment]
@che-effe That's correct.

```
npm i -g polymer-cli
polymer --version
```
