### ISSUE TITLE
External HTML Imports

### ISSUE THREAD

**Issue by jpincas** [Polymer/polymer-cli#586]
OK - I've posted this in a couple of other threads, but I think they are all closed and not sure if directly related, so posting again.  An external HTML import like:

`<link rel="import" href="http://localhost:3000/admin-panel/polymer-imports.html">`

breaks `polymer build`.

Looking through the analyser code a bit more closely I can see that ignoring external dependencies only applies to script and style dependencies. Is there a particular reason for this? I am importing a dynamically rendered html file from an external server which contains a lot of setup information as behaviors. It works perfectly with 'polymer serve' and seems like a good architecture. Is it unwise for some reason?

**Comment by rictic** [comment]
I'm not up on all the details of this issue, but the latest `@next` release of `polymer-build` did fix this issue for some people. I don't know off the top of my head if it handles HTML Imports specially or not though.

The release with the updated version of `polymer-build` was going to make it into the `v0.18.0-pre.11` on Friday, but we ran into a few linter issues that needed a more careful eye. Follow https://github.com/Polymer/polymer-cli/pull/580 for that release.

**Comment by FredKSchott** [comment]
Yup, @jpincas this should be fixed in the latest version of polymer-cli. You can get it by running `npm install -g polymer-cli@next`. We'll be releasing it to the main "latest" release channel as soon as possible.
