### ISSUE TITLE
polymer build should copy bundles when using webcomponents-loader

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer-cli#587]

**Comment by FredKSchott** [comment]
This can be handled today by including webcomponentsjs files in your `polymer.json` `extraDependencies` array:

```
"extraDependencies": [
  "bower_components/webcomponentsjs/*.js"
]
```

**Comment by FredKSchott** [comment]
Fixed in https://github.com/Polymer/polymer-cli/pull/594
