### ISSUE TITLE
WCT tests fail on freshly generated polymer-2-application

### ISSUE THREAD

**Issue by pghalliday** [Polymer/polymer-cli#603]
### Description

After generating a fresh project using `polymer init` and selecting `polymer-2-application`. The WCT test fails.

I'm pretty sure that this is because you can't get a static property from an instance directly. ie:

```javascript
assert.equal(element.is, 'polymer-2-test-app');
```

should be

```javascript
assert.equal(element.constructor.is, 'polymer-2-test-app');
```

### Versions & Environment

- Polymer CLI: 0.18.0-pre.13
- node: v7.7.1
- Operating System: macOS

#### Steps to Reproduce

```
polymer init
# choose polymer-2-application
polymer test
```

#### Expected Results

Tests pass

#### Actual Results

Tests fail with

```
expected undefined to equal 'polymer-2-test-app'
```

**Comment by FredKSchott** [comment]
This was fixed in in #649
