### ISSUE TITLE
Installing latest polymer cli error code 1

### ISSUE THREAD

**Issue by dasodi** [Polymer/polymer-cli#611]
$ sudo npm install -g polymer-cli@next
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
/usr/local/bin/polymer -> /usr/local/lib/node_modules/polymer-cli/bin/polymer.js

> dtrace-provider@0.8.1 install /usr/local/lib/node_modules/polymer-cli/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1142
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1142:25)
    at startup (bootstrap_node.js:127:32)
    at bootstrap_node.js:509:3

> dtrace-provider@0.6.0 install /usr/local/lib/node_modules/polymer-cli/node_modules/dtrace-provider
> node scripts/install.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1142
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1142:25)
    at startup (bootstrap_node.js:127:32)
    at bootstrap_node.js:509:3

> wd@1.1.3 install /usr/local/lib/node_modules/polymer-cli/node_modules/wd
> node scripts/build-browser-scripts

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1142
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1142:25)
    at startup (bootstrap_node.js:127:32)
    at bootstrap_node.js:509:3
/usr/local/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.1 (node_modules/polymer-cli/node_modules/bunyan/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.1 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 (node_modules/polymer-cli/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "polymer-cli@next"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! wd@1.1.3 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wd@1.1.3 install script 'node scripts/build-browser-scripts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build-browser-scripts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/datos1/dario/myapp/npm-debug.log
npm ERR! code 1

**Comment by dasodi** [comment]
I use Mac OS Sierra 10.12.3

**Comment by jsilvermist** [comment]
I got a similar error when trying to update without uninstalling first, try:
```
[sudo] npm uninstall -g polymer-cli
[sudo] npm install -g polymer-cli@next
```

**Comment by tony19** [comment]
@dasodi FWIW, I'm on the same version of macOS and cannot reproduce the error you're seeing when installing `polymer-cli@next`. I recommend [`n`](https://github.com/tj/n) or [`nvm`](https://github.com/creationix/nvm) to manage your `node` installations as non-root (which would obviate `sudo`).

**Comment by hkirk** [comment]
Using latest version of node, I get this error

```
$ sudo npm install -g polymer-cli@next
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "polymer-cli@next"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2

npm ERR! Invalid name: "@types/del"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/henrik/Private/pwa-from-scratch-master/npm-debug.log
```

Hope this can help
[npm-debug.log.zip](https://github.com/Polymer/polymer-cli/files/855735/npm-debug.log.zip)

**Comment by mmilutinovic1313** [comment]
Same errors as above. I have several lines of similar error messages and I've posted one below. I noticed that the build for the project is failing, so I don't know if that has an impact on this at all

```
npm ERR! System Darwin 16.4.0
npm ERR! command "/usr/local/Cellar/node/7.7.3/bin/node" "/usr/local/bin/npm" "install" "-g" "polymer-cli@next"
npm ERR! cwd /Users/mmilutinovic1313
npm ERR! node -v v7.7.3
npm ERR! npm -v 1.4.3
npm ERR! code E404
npm http 200 https://registry.npmjs.org/yeoman-generator/-/yeoman-generator-1.1.1.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mmilutinovic1313/npm-debug.log
npm ERR! not ok code 0
```

Also using nvm --

**Comment by FredKSchott** [comment]
@mmilutinovic1313 you're on npm version 1.4.3, you'll need to be on later version of npm (v3+ I believe) to be able to use the Polymer CLI.

@hkirk not sure what your issue is from that output, it says you're on npm version v4.1.2 which should support types. I cannot reproduce on that same version. Try [this](https://github.com/Polymer/polymer-cli/issues/611#issuecomment-287047100)? 

For everyone, we've found a lot more success with yarn on the Polymer team. I'd recommend it if you're having trouble with npm.

**Comment by mmilutinovic1313** [comment]
@FredKSchott it worked when I switched my version to 4.1.2 via `nvm use 4.1.2`. Thank you!

**Comment by FredKSchott** [comment]
@mmilutinovic1313 from your logs:
```
npm ERR! node -v v7.7.3
npm ERR! npm -v 1.4.3
```

Not sure how you got into that situation, since node v7 ships with npm v4. You may want to reinstall your version v7.7.3, otherwise you're almost guarenteed to run into future node issues.

**Comment by mmilutinovic1313** [comment]
@FredKSchott will having used the `nvm use 4.1.2` command fix that issue in the future? When I did that it installed polymer-cli properly .

**Comment by FredKSchott** [comment]
maybe, not sure. `nvm uninstall` + `nvm install` may work

**Comment by Temeteron** [comment]
Got in the same situation for a newer version of npm. I couldn't install polymer-cli with the following node and npm versions installed:
``
node -v: v7.x.x
npm  -v: v5.x.x
``
The solution is to downgrade npm to version 4.x.x

**Comment by codebugcode** [comment]
I had npm5 installed thanks @Temeteron Finally got it to work...

Wish they would mention this on the docs:
https://www.polymer-project.org/2.0/docs/tools/polymer-cli

Especially when it says on step 2 to updated to the latest npm version...

**Comment by tomsanders** [comment]
same issue here for even newer versions of node and npm. I could not install polymer-cli with these node and npm versions:

`node -v: v8.x.x `
` npm  -v: v5.3.x`

**Comment by frankbe** [comment]
same issue here for even newer versions of node and npm (under arch linux) ...
```
node -v: v8.7.0
npm -v: 5.5.1
```
