### ISSUE TITLE
Feature Request: Ability to select a single build

### ISSUE THREAD

**Issue by coreyfarrell** [Polymer/polymer-cli#613]
When using `polymer build` all targets found in polymer.json "builds" array are always built.  It would be useful if this could be controlled by config and command-line.

Example polymer.json builds section:
```
{
  "builds": [
    {
      "name": "default",
      "bundle": true,
      "js": {"minify": true},
      "css": {"minify": true},
      "html": {"minify": true}
    },
    {
      "name": "debug",
      "bundle": false,
      "autobuild": false
    }
  ]
}
```

The goal is that running `polymer build` should only build "default", but the "debug" settings can be left in polymer.json.  For compatibility the "autobuild" setting has to be true by default.

Second part of this request is the ability to select one or more build(s) from command-line.  This way if my code is broken I could run `polymer build --target debug` to build "debug" only instead of trying to troubleshoot in a giant bundled minified source.  The command-line option should cause all "autobuild" options to be ignored and only build the requested targets.

**Comment by FredKSchott** [comment]
+1 I agree, this would be a really useful feature for troubleshooting single builds. Also for faster iteration during development (1 target builds faster than N targets)

**Comment by timweightman** [comment]
I think this is a great idea, I'm definitely missing the feature right now.
Rather than `autobuild`, I would prefer env-specific config similar to #408 proposal.

Example:
```
{
  "environments": {
    "DEV": {
      "builds": [
        {
          "name": "debug",
          "bundle": false,
        }
      ]
    },
    "PROD": {
      "builds": [
        {
          "name": "default",
          "bundle": true,
          "js": {"minify": true},
          "css": {"minify": true},
          "html": {"minify": true}
        }
      ]
    }
  }
}
```

If there is a root `"builds"` property in polymer.json, it would always be built, and based on environment config, there may be additional builds for DEV, PROD etc.

**Comment by justinfagnani** [comment]
I think this is a great issue for a contribution, if anyone wants to take a crack.

**Comment by davidmaxwaterman** [comment]
How is this different to the `--name` option? Not that `--name` actually works, but hey.

**Comment by jsilvermist** [comment]
@davidmaxwaterman AFAIK `--name` is for setting the name of a build, aka the folder it's placed into.

I believe it currently doesn't take into account whether or not there's a entry in the `polymer.json`, so for a bundled build it would be:
```sh
polymer build --name bundled --bundle
```
even if you already have an entry in your `polymer.json` such as:
```json
{
  "name": "bundled",
  "bundle": true
}
```
That being said, making `--name` check if an entry exists using the same name and following that config, while allowing other flags to overwrite the saved config seems like a pretty good way to fix this IMO.

**Comment by davidmaxwaterman** [comment]
@jsilvermist gosh...I had totally misunderstood that then. I was totally using it as if it were the specify the build from polymer.json. See https://github.com/Polymer/polymer-cli/issues/827 for how I'm not the only one :/
Having a `--name` cli option *and* using that in the polymer.json file is surely quite confusing...

**Comment by andreabioli** [comment]
If I run:
`polymer build --help`
I obtain, among other things:
`--name string                 The build name. Defaults to "default".`
This gives me the idea that I can specify which one of the builds (that I have in my `polymer.json` file) I want to actually build.
The feeling is reinforced by the fact that if you run:
`polymer build`
The CLI builds *all* of the builds in `polymer.json`, while if you run:
`polymer build --name test`
You obtain *only* one build. :-(

Anyway, browsing the source (at `https://github.com/Polymer/polymer-cli/blob/master/src/build/build.ts`) the idea is that the `--name` option is used only for directory resolution (around line 40 and around line 116).

Someone should elaborate on this, and please, explain better...

**Comment by bennypowers** [comment]
This would be useful for CI, when building different builds for different customers or environments.

**Comment by coreyfarrell** [comment]
I haven't used polymer-cli in over a year so I'm closing this issue.  If this is still an issue and anyone cares feel free to open a new ticket under the monorepo.
