### ISSUE TITLE
inline css import after build

### ISSUE THREAD

**Issue by baocang** [Polymer/polymer-cli#614]
### Description

Can css import works or another way to import extra css file without move it into a html file

### Versions & Environment

- Polymer CLI:0.18.0-pre.13
- node:v7.7.2
- Chrome: Version 56.0.2924.87 (64-bit)
- Operating System: macOS Sierra Version 10.12.3

#### Steps to Reproduce

1. Create an application project: `polymer init polymer-2-application`
2. link a css file in app-shell ```<link rel="import" type="css" href="assets/style.css">```
3. Build: `polymer build --bundle`

#### Expected Results

inline style.css or keep <link rel="import" type="css" href="assets/style.css"> with right href

#### Actual Results

import has removed!

**Comment by baocang** [comment]
@FredKSchott I fixed this in PR https://github.com/Polymer/polymer-bundler/pull/463 with very few changes with tests, can you help me review it?

**Comment by usergenic** [comment]
@baocang I merged in #463 and created https://github.com/Polymer/polymer-bundler/pull/466 to cover the remaining adjustments prior to merging into `master`.

**Comment by FredKSchott** [comment]
Thanks @usergenic, closing this issue.
