### ISSUE TITLE
polymer experiment-lint fails if build directory exists with minified JS.

### ISSUE THREAD

**Issue by coreyfarrell** [Polymer/polymer-cli#616]
### Description
`polymer experimental-lint` scans the `build` directory produced by `polymer build`.  If JS was minified it fails.

### Versions & Environment
- Polymer CLI: 0.18.0-pre.13

#### Steps to Reproduce
1. Create a Polymer 2 application project: `polymer init application`
2. Add build configuration to polymer.json: `"builds": [{"js": {"minify": true}}]`
3. Build: `polymer build`
4. Analyze: `polymer experimental-lint`

#### Expected Results
Success.
1. Maybe ./build shouldn't even be scanned?  In real-world apps quoting the minified line to show the error produces unreasonably long output.
2. Polymer.Element should be detected even if it's in minified scripts.

#### Actual Results
>   <script>class MyApplication extends Polymer.Element{static get is(){return'test-app'}static get properties(){return{prop1:{type:String,value:'test-app'}}}}window.customElements.define(MyApplication.is,MyApplication);</script>
>                                        ~~~~~~~~~~~~~~~
> 
> build/default/src/test-app/test-app.html(12,39) error [unknown-superclass] - Unable to resolve superclass Polymer.Element

**Comment by justinfagnani** [comment]
@rictic sounds like `analyzePackage` needs to exclude the build directory by default.
