### ISSUE TITLE
Using --js-minify causes blank content area in app-drawer-layout

### ISSUE THREAD

**Issue by jifalops** [Polymer/polymer-cli#620]
### Description

Building with --js-minify causes the main content area (ala `app-drawer-layout `) to be blank. The drawer and toolbar work (are style, respond to clicks).

### Versions & Environment

- Polymer CLI: 0.18.0-pre.13
- node: v7.6.0
- Operating System: Linux Mint 17 Qiana

#### Steps to Reproduce
1. Clone my project (psk does not have the issue)

```
git clone https://github.com/jifalops/app-starter.git -b build-tests
cd app-starter
bower install
```
2. Build and test (unbundled should work, submitting another issue for bundled)

```
polymer build
polymer serve build/unbundled-es6
```

3. Minify JS, build and test (unbundled builds should have blank content area)
Change [this line](https://github.com/jifalops/app-starter/blob/build-tests/polymer.json#L34) (and similar) to true.
```
polymer build
polymer serve build/unbundled-es6
```

**Comment by FredKSchott** [comment]
Are you seeing any console errors when you serve the site? Do you see this across all browsers?

**Comment by jifalops** [comment]
Without --js-minify:

Chrome has a service worker error on some pages (disabling the SW build does not fix)

Firefox has an app-indexdb error on those same pages:
![image](https://cloud.githubusercontent.com/assets/826613/24124205/f9aeba90-0d98-11e7-871d-2a4775df5841.png)

With --js-minify:

No console errors in Chrome or Firefox, but content area is blank in both.

**Comment by khammami** [comment]
@jifalops  are you using app-indexeddb-mirror in users-page?

**Comment by jifalops** [comment]
This had the same cause as #621, A missing fragment entry in `polymer.json`.

**Comment by terrywarwar** [comment]
I'm getting the same issue when using `paper-date-picker`  Displays the days using `polymer serve` but when it's built using `polymer build --js-minify`, no content shows for the days.
![screen shot 2017-04-24 at 9 51 22 am](https://cloud.githubusercontent.com/assets/615545/25361853/d57937d8-2993-11e7-83a0-06f1cb42ab75.png)

**Comment by terrywarwar** [comment]
I'm no longer having this issue with the v0.18.3.

**Comment by justinfagnani** [comment]
Thanks for the update @terrywarwar 
@jifalops can you check to see if it's fixed for you?

**Comment by jifalops** [comment]
Sorry still getting the issue on the build-tests and master branches. It's probably something on my end, but not critical so I haven't really dug into it. Congrats on the 2.0 release!
