### ISSUE TITLE
polymer build --bundled Breaks only one of my pages

### ISSUE THREAD

**Issue by jifalops** [Polymer/polymer-cli#621]
### Description

Building with --bundled breaks only the messages page
![image](https://cloud.githubusercontent.com/assets/826613/24124685/517369c2-0d9b-11e7-8183-c34b7d426c50.png)

### Versions & Environment

- Polymer CLI: 0.18.0-pre.13
- node: v7.6.0
- Operating System: Linux Mint 17 Qiana

#### Steps to Reproduce
1. Clone my project

```
git clone https://github.com/jifalops/app-starter.git -b build-tests
cd app-starter
bower install
```

2. Build and test

```
polymer build
polymer serve build/bundled-es6
```

3. Navigate to the `messages` page (/messages). Many console errors appear (see above pic).
Serving the unbuilt code or the build but unbundled code has no errors.

**Comment by FredKSchott** [comment]
@usergenic mind taking a look?

**Comment by jifalops** [comment]
Sorry it was a simple mistake on my part. The page in question was missing from the `"fragments"` section of `polymer.json`.
