### ISSUE TITLE
Add ability to list/install 3rd party templates

### ISSUE THREAD

**Issue by phidias51** [Polymer/polymer-cli#624]
The out-of-the-box templates tend to be a bit limited.  It would be useful if there was a way to see all 3rd party templates from within **polymer**. The user would be able to see installed templates, and downloadable templates, and there would be some mechanism for installing the template.

**Comment by FredKSchott** [comment]
Great idea, this is actually already supported, just search http://yeoman.io/generators/ for `polymer-init` & then npm install it.

We won't be able to integrate this directly into the CLI at the moment, but it could make sense to revisit after v1.0.0 is released.

**Comment by phidias51** [comment]
So why are you closing it if you're planning on revisiting the idea later?
