### ISSUE TITLE
IE11 syntax error in custom-elements-es5-adapter

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-cli#627]
#625 introduces a bug whereby IE11 will throw a syntax error when loading the custom-elements-es5-adapter. This will not cause any other errors, and pages will work fine, there will just be an ominous error reported in the console.

We have a fix for this in mind, but it's somewhat complex and we want to unblock #605 first, as it does break pages.

The fix is for our compiling pipelines to insert some code that will run `custom-elements-es5-adapter.js` reliably, in a blocking and CSP-compliant manner, if and only if the browser natively supports custom elements. This rules out `document.write` which Chrome may skip for devices on 2G networks, `eval` which is not CSP-compliant, and appending the script dynamically using dom methods which does not block. The solution @azakus @FredKSchott and I came up with is to conditionally remove the parent element from the DOM. This means that we also have to move† the script import of the es5 loader into the body if it isn't there already, as no `<head>`-legal elements can have script children. The desired output looks something like this:

```html
  <div id="ce-es5-shim">
    <script>
      if (!window.customElements) {
        var ceShimContainer = document.querySelector('#ce-es5-shim');
        // This prevents custom-elements-es5-adapter.js from parsing or running.
        ceShimContainer.parentElement.removeChild(ceShimContainer);
      }
    </script>
    <script src="custom-elements-es5-adapter.js"></script>
  </div>
  <script src="webcomponents-loader.js"></script>
```

† moving a script out of head also means moving all subsequent styles, scripts, and links from the head too, in order to maintain the correct order

**Comment by valdrinkoshi** [comment]
That's a quite an elegant solution! 💯👌
It should be `if (!window.customElements)` right?

**Comment by FredKSchott** [comment]
@valdrinkoshi you're right, updating the example...

I'll be building this out for polymer-build & polymer-cli today

**Comment by usergenic** [comment]
If this is in a div in the body, how does this avert the problem when you have a `<link rel="import"` to a custom element in `<head>` from executing on Chrome?

**Comment by rictic** [comment]
We have to preserve ordering of links, scripts, and styles, so any of them after the `webcomponents-loader.js` import will need to be moved too.

**Comment by valdrinkoshi** [comment]
the es5 adapter could be injected as the first child of `<head>`, that should be enough

**Comment by usergenic** [comment]
@valdrinkoshi  (?) but can't `<div>` in the head...

**Comment by rictic** [comment]
Updated the top comment to mention maintaining ordering

**Comment by usergenic** [comment]
@FredKSchott There's a lot of specific logic in the Bundler for maintaining ordering after inlining of html import.  Let me know if I can be of any help walking through my approach to that.

**Comment by valdrinkoshi** [comment]
@usergenic you can http://jsbin.com/yulehe/3/edit?html,console
Tested in IE11, the scripts following the "remover" one are never executed
<img width="1108" alt="screen shot 2017-03-23 at 10 50 36 am" src="https://cloud.githubusercontent.com/assets/6173664/24262191/91923f34-0fb6-11e7-8b71-7d72e1c15b59.png">

**Comment by rictic** [comment]
@valdrinkoshi Look at the elements panel though, `<head>` is empty

**Comment by valdrinkoshi** [comment]
ugh, true ;_; TIL don't mess with `<head>`

**Comment by HendrikThePendric** [comment]
I'm a bit late to the party but solved this problem using the opposite approach, which means I could keep all scripts in the page head:
```html
<script id="custom-elements-es5-adapter-loader">
  if (window.customElements) {
    var src, currTag, script;
    src        = 'bower_components/webcomponentsjs/custom-elements-es5-adapter.js';
    currTag    = document.getElementById('custom-elements-es5-adapter-loader');
    script     = document.createElement('script');
    script.src = src;
    currTag.parentNode.insertBefore(script, currTag.nextSibling);
  }
</script>
<script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
```
Now IE11 will only have the webcomponent-lite, and Chrome will first have the adapter and then the webcomponents-lite.

**Comment by oravecz** [comment]
For me, on Chrome Version 60.0.3112.90 (Official Build) (64-bit) and Version 62.0.3167.0 (Official Build) canary (64-bit), the custom-elements-es5-adapter.js loads much later.
