### ISSUE TITLE
polymer-cli@next (0.18.0-pre.15) serve --open does opens component (404) instead of app

### ISSUE THREAD

**Issue by peterlauri** [Polymer/polymer-cli#628]
### Description
polymer-cli@next (0.18.0-pre.15) serve --open does not open app after initiating polymer-2-starter-kit

### Versions & Environment

- Polymer CLI: 0.18.0-pre.15
- node: v6.10.1
- Operating System: OSX

#### Steps to Reproduce

1. Install polymer-cli@next (0.18.0-pre.15)
2. Create a new folder && cd new folder
3. Run **polymer init polymer-2-starter-kit**
4. Run **polymer serve --open**

#### Expected Results
I expect for **http://127.0.0.1:8081** to be opened in the browser

#### Actual Results
**http://127.0.0.1:8081/components/polymer-starter-kit/** is opened and showing 404

**Comment by rictic** [comment]
@FredKSchott do you know if we can tell whether we're in an element or application in polymer-cli?

**Comment by FredKSchott** [comment]
Not currently, no. Our previous thinking was that if a polymer.json file existed, it was an application. But now that it stores the linting config for both elements and applications that's a little harder.

 We should nail down a plan for this once and for all next week.

**Comment by justinfagnani** [comment]
This issue was moved to Polymer/polyserve#171
