### ISSUE TITLE
polymer init should not generates .travis.yml from github templates

### ISSUE THREAD

**Issue by peterlauri** [Polymer/polymer-cli#629]
### Description
**polymer init polymer-2-starter-kit** generates a .travis.yml file that contains build for node_js 4, 5 and 6. Node 6 is defined as supported version, and running the tests on 4 and 5 doesn't make sense for polymer projects.

### Versions & Environment
- Polymer CLI: 0.18.0-pre.15
- node: v6.10.1
- Operating System: OSX

#### Steps to Reproduce

1. Install polymer-cli@next: 0.18.0-pre.15
2. Run **polymer init polymer-2-starter-kit**
3. cat .travis.yml

#### Expected Results
```
node_js:
  - '6'
```

#### Actual Results
```
node_js:
  - '6'
  - '5'
  - '4'
```

**Comment by FredKSchott** [comment]
+1. Honestly I say we get rid of this file entirely when running polymer init. Right now it's coming through because it's in the PSK github repo but it was never meant to be a recommendation of any sort.

**Comment by FredKSchott** [comment]
Renamed this issue, and filed the verison issue in PSK: https://github.com/PolymerElements/polymer-starter-kit/pull/993

**Comment by FredKSchott** [comment]
@peterlauri thanks again for reporting. Lets keep discussion in the older #446
