### ISSUE TITLE
Docs: might add heads-up in README to upgrade your `node` version if you're getting an error when you run

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer-cli#63]

**Comment by justinfagnani** [comment]
Yes, we need to publish supported versions.

Our target is current LTS, so 4.4.4.

**Comment by FredKSchott** [comment]
It's common to define which node.js versions you support in your
package.json.

**Comment by FredKSchott** [comment]
@justinfagnani & @tjsavage we now throw a warning when installing on a <v4 version, that says polymer-cli needs node v4.0 or higher. Is this enough or do we still want something in the README?

**Comment by tjsavage** [comment]
Perfect. Might just add a line in the README too just to potentially save people the step of Install > Error > Update
