### ISSUE TITLE
polymer build --verbose prompt information unfriendly 

### ISSUE THREAD

**Issue by baocang** [Polymer/polymer-cli#631]
### Versions & Environment

- Polymer: 2.0.0-rc.3
- webcomponentsjs: 1.0.0-rc.7
- Polymer CLI: 0.18.0-pre.15
- node: v7.7.3
- Operating System: macOS Sierra Version 10.12.3

When something with wrong, it throws:
```
error:   Uncaught exception: Error: EISDIR: illegal operation on a directory, read
error:   Error: EISDIR: illegal operation on a directory, read
```
When set js: { compile: true },  it note with:
```
[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".
```
...

Can provide more useful information with polymer-cli?

**Comment by baocang** [comment]
```
warn: [cli.build.analyzer]    In core/ReportSetting/report-create.html: [invalid-polymer-expression] - Expect an expression, not a LabeledStatement
```

**Comment by FredKSchott** [comment]
That's interesting, I haven't seen that error yet. Can you include steps for me to reproduce to see what is going on? It seems to be an issue inside of Bower.

One idea is that you don't have full permissions in the project directory you're building in.

In general, verbose logs are meant to be information-heavy, with the understanding that this may cause them to be ugly or even unfriendly. But it looks like we're missing log info about what caused your issue, so we should look into adding something once we know what's wrong.

**Comment by bennypowers** [comment]
I'm getting this too. I have some external scripts included (aws-sdk.min.js, mock-http-request) which might be involved (can't confirm that suspicion atm., also they don't have any stiles in 'em so ??)

**Comment by baocang** [comment]
@FredKSchot I found the wrong code:  `<input class="value" valuw="{{reMark:input}}">`
`reMark:input` parsed as `LabeledStatement`, but valuw can't accept it.
I found this problem by modify polymer-analyzer to log expression text and line. and i have more than two thousand custom element and totally one million lines of ten thousand source files. who can found this problem without tools 😓
do you need I create a PR for this?

**Comment by baocang** [comment]
@FredKSchott in PR https://github.com/Polymer/polymer-build/pull/171  I changed `getFullWarningMessage ` 
changes from
```
function getFullWarningMessage(warning: Warning): string {
  return `In ${warning.sourceRange.file}: [${warning.code}] - ${warning.message
  }`;
}
```
to
```
function getFullWarningMessage(warning: Warning): string {
  const sourceRange = warning.sourceRange;
  const start = sourceRange.start;
  const end = sourceRange.end;
  let lineInfo = '';

  if (start.line === end.line) {
    lineInfo = `line ${start.line} column ${start.column}`;
  } else {
    lineInfo = `line ${start.line} to ${end.line}`;
  }
  return `In ${warning.sourceRange.file} ${lineInfo}: [${warning.code}] - ${warning.message} `;
}
```
to makes warning log from 
```
warn: [cli.build.analyzer]    In src/app-shell/app-shell.html: [invalid-polymer-expression] - Expect an expression, not a LabeledStatement
```
to
```
warn: [cli.build.analyzer]    In src/app-shell/app-shell.html line 10 column 32: [invalid-polymer-expression] - Expect an expression, not a LabeledStatement
```
