### ISSUE TITLE
polymer lint seems not to exclude files, if bower_components directory is renamed

### ISSUE THREAD

**Issue by web-padawan** [Polymer/polymer-cli#632]
### Description
I get following errors then running `polymer-lint` on my [sandbox](https://github.com/web-padawan/polymer-sandbox):
```
#!/usr/bin/env node
[31m~[39m

src/vendor/async/perf/benchmark.js(0,0) [31merror[39m [parse-error] - Unexpected character '#'


#!/usr/bin/env node
[31m~[39m

src/vendor/async/support/sync-package-managers.js(0,0) [31merror[39m [parse-error] - Unexpected character '#'


#!/usr/bin/env node
[31m~[39m

src/vendor/mocha/scripts/upgrade-npm.js(0,0) [31merror[39m [parse-error] - Unexpected character '#'


<!doctype html>
[31m~[39m

src/vendor/web-component-tester/data/index.html(0,0) [31merror[39m [unable-to-analyze] - Unable to analyze file: URI malformed
```
etc (there are more).

### Versions & Environment

- Polymer CLI: 0.18.0-pre.14
- node: 6.9.3
- Operating System: Mac OS X El Capitan

#### Steps to Reproduce

1. Clone https://github.com/web-padawan/polymer-sandbox
2. Run `npm i && bower i`
3. Run `npm i -g polymer-cli@next`
4. Run `polymer-lint --rules polymer-1 > log.txt`
5. See the beginning of the file

#### Expected Results
No errors should be thrown about components from `src/vendor`, as it is a bower dependencies dir specified in `.bowerrc` (although located in `src` which is sources dir).
#### Actual Results
Errors are thrown.

**Comment by FredKSchott** [comment]
@web-padawan thanks for the clear OP & reproduction steps!

@rictic this is an interesting use case.

**Comment by rictic** [comment]
+1, thanks for the issue. Moved to the analyzer as https://github.com/Polymer/polymer-analyzer/issues/584
