### ISSUE TITLE
warning [databind-with-unknown-property] - importPath is not declared or used more than once.

### ISSUE THREAD

**Issue by coreyfarrell** [Polymer/polymer-cli#640]
### Description
Polymer builtin data binding property importPath is not recognized.

### Versions & Environment
- Polymer CLI: 0.18.0-pre.15
- node: v6.10.0
- Operating System: Fedora 25

#### Steps to Reproduce
1. Use `[[importPath]]` databinding in a custom element template.
2. Set `"lint": { "rules": ["polymer-2"] }` in polymer.json.
3. Run `polymer lint`.

#### Results
warning [databind-with-unknown-property] - importPath is not declared or used more than once.
Adding the annotation `/** @polymerElement @extends Polymer.Element */` before the class declaration of the effected element did not clear this warning.

**Comment by justinfagnani** [comment]
This is an intended warning. The polymer linter should have always warned if you don't declare a property used in a template, or use it twice in the template. It's to protect against typos in data-binding expressions.

**Comment by justinfagnani** [comment]
Oops! I just realized that `importPath` is a property declared on `Polymer.Element`. Sorry for closing prematurely.

The declaration of `rootPath` and `importPath` are declared in `@jsdoc` annotations, here: https://github.com/Polymer/polymer/blob/master/lib/mixins/element-mixin.html#L107

/cc @rictic

**Comment by justinfagnani** [comment]
This issue was moved to Polymer/polymer-linter#71
