### ISSUE TITLE
Warn when custom attributes are used on a custom element and not in its observedAttributes

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer-cli#642]
Polymer lint should produce a warning when an attribute is used that is custom but not in an element's `observedAttributes` list.

E.g. `<my-element username="Bob">` should warn if the `my-element` is observing `user-name` as it would if a user declared a Polymer property called `userName`.

**Comment by justinfagnani** [comment]
This issue was moved to Polymer/polymer-linter#73
