### ISSUE TITLE
`polymer serve` output page needs a trailing /

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer-cli#644]
`polyserve` is very cranky if you don't add a trailing `/`, and the `polymer serve`  variants page omits it for the links:
<img width="582" alt="screen shot 2017-04-04 at 12 31 12" src="https://cloud.githubusercontent.com/assets/1369170/24675114/db57b9ca-1932-11e7-8906-72f35e4aea48.png">

If you actually click on `http://127.0.0.1:8081/components/paper-input` it takes you to `http://127.0.0.1:8081/Users/noms/Code/polymer/paper-input/` which is incorrect.

Note: I am not requesting a change in `polyserve` behaviour, I'm just asking for a trailing `/` in that link

@FredKSchott @justinfagnani

**Comment by justinfagnani** [comment]
The underlying redirect problem was fixed in https://github.com/Polymer/polyserve/pull/159

**Comment by justinfagnani** [comment]
This issue was moved to Polymer/polyserve#172
