### ISSUE TITLE
Polymer serve causes runtime error

### ISSUE THREAD

**Issue by martijnnanne** [Polymer/polymer-cli#670]
### Description
Polymer serve causes runtime error after following the default steps to init a project, it does not matter wether I init an element, starter kit or application I will get this error when calling polymer serve :

error:   cli runtime exception: SyntaxError: Unexpected token [
error:   SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/polyserve/lib/start_server.js:33:30)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

### Versions & Environment

- Polymer CLI: 0.18.0
- node: v4.2.6
- Operating System: Ubuntu 16.04

#### Steps to Reproduce

After following the instructions on https://www.polymer-project.org/2.0/docs/tools/polymer-cli, I got the error shown above when running polymer serve. Other polymer commands do work fine eg. polymer lint, polymer build.

#### Expected Results
I expeced my local server to be started.

#### Actual Results
The mentioned error popped up and no local server was started.

**Comment by tjmonsi** [comment]
I am also getting this as well

**Comment by rogozinds** [comment]
This seems to be an issue with Ubuntu, my colleague doesn't have it on MacOS 10, with same Polymer CLI version.

**Comment by rogozinds** [comment]
Downgrading to 0.17.0 fixes the issue.

**Comment by tjmonsi** [comment]
I used 0.18.0-pre.13 ... I am testing it out with 0.18.0-pre.15 later if it will work.

**Comment by martijnnanne** [comment]
What I did right now was to initialize a project using the latest cli version, then downgraded to 0.17 to serve. It's not optimal but for anyone having this issue this might be a quick hack for the moment if you want to initialize a polymer 2.0 project.

**Comment by lscholten** [comment]
The changelog states the following:

> Remove Node v4 support: Node v4 is no longer in Active LTS, so as per the Polymer Tools Node.js Support Policy the Polymer CLI will not support Node v4 going forward. Please update to Node v6 or later to continue using the latest verisons of Polymer tooling.

I am currently running Ubuntu 16.10 and node version `6.3.0`.
The problem described does not occur and `polymer serve` runs without problems.

**Comment by tjmonsi** [comment]
Hmmmm thanks. Ill try to update again to 0.18.0 and see if it works on my
system and my node version there is 6.x. I encountered the error on my c9
account but i havent checked the node version on my c9 account. Will ping
back

**Comment by zet4** [comment]
Have the same issue on Windows machine, just installed from NPM so 0.18.0, Node version 5.7.1.
Happens both when trying to run `serve` and `test`.

**Comment by FredKSchott** [comment]
That's correct, we stopped supporting Node v4 as of a few weeks ago when Node dropped it from active LTS. 

We currently support Node v6 (active LTS) & v7 (current) only.

Please update to one of those supported versions of Node to continue to use Polymer tools.

**Comment by FredKSchott** [comment]
I've created https://github.com/Polymer/polymer-cli/issues/683 to improve the error message you're seeing on Node <v6. Hopefully this will make it much more clear for future people.
