### ISSUE TITLE
polymer-2-element test fail

### ISSUE THREAD

**Issue by Zecat** [Polymer/polymer-cli#672]
### Description

polymer-2-element test fail out of the box
### Versions

- Polymer CLI: 0.18.0
#### Steps to Reproduce

1. Create a polymer 2 element project: `polymer init polymer-2-element`
2. Run the test: `polymer test`

#### Expected Results
No error is throw

#### Actual Results
expected undefined to equal 'polymer-2-element'
expected undefined to equal 'new-prop1'

#### Cause
It seems that bug was introduced in #651

The element class name has been updated to `<%= elementClassName %>` but the custom element definition still refers to `MyElement`. See https://github.com/Polymer/polymer-cli/pull/651/files#diff-198d2e97df8ba75b401057b0261b98b2R33.

**Comment by FredKSchott** [comment]
@Zecat doh! Thanks for catching that, any interest in submitting a quick fix?

**Comment by Zecat** [comment]
Yes, also I was wondering, can we test in https://github.com/Polymer/polymer-cli/blob/master/test/unit/init/element_test.js that the element test is passing ?
I mean can we test a test ?

**Comment by FredKSchott** [comment]
we actually have integration tests that should be catching this, but I just realized we never commented them back in: https://github.com/Polymer/polymer-cli/blob/master/test/integration/integration_test.js#L48

@Zecat thanks again for catching this, I'll turn those integration tests back on and then fix the bug in the same PR.

**Comment by Zecat** [comment]
Cool ! Happy to help, thank for your quick answer, you guys do an amazing work !

**Comment by FredKSchott** [comment]
🎉 Fixed in #673!
