### ISSUE TITLE
Documentation: Update confusing information regarding "custom-elements-es5-adapter.js"

### ISSUE THREAD

**Issue by myuseringithub** [Polymer/polymer-cli#677]
In polymer-cli, it is mentioned that `custom-elements-es5-adapter.js` is used for older browsers, while in the webcomponentsjs documentation it is clearly stated, that its used for ES6 (ES2015+) supporting browsers to let class inheretence work properly on these native implementations.

polymer-cli readme - has a mistake concerning `custom-elements-es5-adapter.js` usage*.
https://github.com/Polymer/polymer-cli#--js-compile
```--js-compile
When your application uses the --js-compile CLI flag (or polymer.json config property) your application is compiled from ES6 to ES5. For this to work properly, some older browsers need the custom-elements-es5-adapter.js shim in addition to the webcomponents-loader.js/webcomponents-lite.js polyfill. The build process will automatically inject this ES5 adapter into your application when --js-compile is enabled so that your application works as expected on older browsers.
```

webcomponentsjs: 
https://github.com/webcomponents/webcomponentsjs/tree/v1.0.0-rc.8#custom-elements-es5-adapterjs

**Comment by FredKSchott** [comment]
@myuseringithub thanks for filing this. While I'm assuming the overall tone of your OP was friendly, comments like "polymer-cli - confusing and wrong" aren't constructive and tend to hurt the people who spend their time maintaining this software for everyone. Please be more careful in the future.

Our README is being rewritten in #675 and this section is no longer included. If we still see confusion around this behavior and what it does, we can revisit adding it back to the CLI or the `$ polymer help build` documentation.

**Comment by myuseringithub** [comment]
@FredKSchott Sorry, I didn't clarify my point, I meant that there was a mistake in the `polymer-cli` readme section contradicting the explanation in the `webcomponentsjs` readme. Which lead caused me some confusion.

**Comment by FredKSchott** [comment]
You're right, it is incorrectly written in the current readme. See #675 for our new readme-in-process.
