### ISSUE TITLE
Polymer 2 element template demo/index.html is missing <custom-style>

### ISSUE THREAD

**Issue by Tronil** [Polymer/polymer-cli#692]
### Description
In the polymer 2 element template demo/index.html,  `<style>`  has to be wrapped in a `<custom-style>` element to work.

### Versions & Environment
Polymer CLI 0.18.0

#### Steps to Reproduce
Run polymer init and select polymer-2-element

#### Expected Results
`<custom-style>` is used in demo/index.html

#### Actual Results
`<custom-style>` is missing

**Comment by FredKSchott** [comment]
Fixed by #695
