### ISSUE TITLE
npm install -g polymer-cli@next WARN deprecated node-uuid@1.4.8

### ISSUE THREAD

**Issue by lawrence9811** [Polymer/polymer-cli#697]
Run:
npm install -g polymer-cli@next

Got:
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

Could you update npm dependency to use uuid module?

**Comment by FredKSchott** [comment]
See: https://github.com/Polymer/wct-local/issues/54

This is finally unblocked as of a few days ago.

**Comment by FredKSchott** [comment]
This should be fixed as of the latest version
