### ISSUE TITLE
[lint] warnings exit in error

### ISSUE THREAD

**Issue by stramel** [Polymer/polymer-cli#699]
### Description

When `polymer lint` finds issues that result in warnings the command exits with code 1. 

### Versions & Environment

- Polymer CLI: 0.18.1
- node: 6.9.1
- Operating System: Windows 10

#### Steps to Reproduce

1. Clone PSK
2. npm i -g polymer-cli
3. npm i;polymer install
4. npm run lint

#### Expected Results

Warnings are displayed and command exits with code 0 if no errors are present.

#### Actual Results

Warnings are displayed and command exits with code 1

**Comment by stramel** [comment]
I would be happy to add at least an initial go at this if someone can point me in a desired direction.

**Comment by FredKSchott** [comment]
Thanks for filing this, someone on the team mentioned that this might be the case the other day.

Let me run through this today and take a look at what exactly is breaking. Hopefully it's a simple fix in PSK and not a bug in the linter/analyzer.

**Comment by FredKSchott** [comment]
Just realized I misunderstood your issue, and thought that you were seeing a `1` exit code when there were no warnings or errors. As of right now this is expected behavior. 

Discussing a possible enhancement to change this behavior here: https://github.com/Polymer/polymer-project-config/pull/20
