### ISSUE TITLE
polymer build --js-minify does not minify some files

### ISSUE THREAD

**Issue by lawrence9811** [Polymer/polymer-cli#704]
polymer build --js-minify

seems to work with javascript within html files only, but does not minifying standalone .js files, such as:

/bower_components/webcomponentsjs/webcomponents-loader.js

the build is exactly the same as the source, even all comments are intact.

**Comment by FredKSchott** [comment]
The `/bower_components/webcomponentsjs/*` directory is actually specifically excluded from optimization, since some of its files are polyfills that optimization/compilation completely break.

Any file in any other directory should be getting minified.
