### ISSUE TITLE
polymer lint produces error for node binary scripts: Unexpected character '#'

### ISSUE THREAD

**Issue by coreyfarrell** [Polymer/polymer-cli#711]
### Description
When a project contains executable node scripts they produce an error `Unexpected character '#'`.

### Versions & Environment
- Polymer CLI: 0.18.1
- node: 6.10.2
- Operating System: Fedora 25

#### Steps to Reproduce
* Create a script intended to be executable containing first line `#!/usr/bin/env node` per instructions at https://docs.npmjs.com/files/package.json#bin
* Run `polymer lint` with any rules.

#### Expected Results
No error, 'hash-bang' on first line should be ignored.

#### Actual Results
```
#!/usr/bin/env node
~

bin/example-script.js(0,0) error [parse-error] - Unexpected character '#'
```
This also effects vscode integration, including in projects which do not contain a `polymer.json` config.

**Comment by FredKSchott** [comment]
Looks like an error in babili :(

@coreyfarrell would you like to file this with them @ https://github.com/babel/babili/issues? Happy to do it myself if not.

**Comment by FredKSchott** [comment]
~~Looks like an error in babili :(~~ Doh, thought we were talking about build minification, not linting.

Why are you linting an executable file? The linter is meant to lint for web projects, so this kind of files falls a bit out of scope. Check out [eslint](https://github.com/eslint/eslint) for generic js linting.

**Comment by coreyfarrell** [comment]
I'm not trying to run polymer-lint on the executable file, but it still runs.  I have a project where polymer.json contains `"sources": ["html/**"]`, running `polymer lint` with no parameters still reports an error for `bin/example-script.js` even though it's not listed as a polymer source.

**Comment by FredKSchott** [comment]
Ah, got it. Yea it looks like there is an outstanding TODO for this:

```js
  /**
   * TODO(rictic): things to make configurable:
   *   ...
   *   - add option for input files to polymer.json
   */
```

/cc @rictic & @justinfagnani this should be prioritized

**Comment by coreyfarrell** [comment]
Do I need to post a separate bug for vscode integration?  I think polymer-ide should not run unless polymer.json exists.  Just by having it installed it produces this error for node.js projects which have nothing to do with polymer.

**Comment by FredKSchott** [comment]
I'm less familiar with the vscode integration, but for specific IDE plugin behavior i'd recommend you post that issue here: https://github.com/Polymer/vscode-plugin

**Comment by coreyfarrell** [comment]
I haven't used polymer-cli in over a year so I'm closing this issue.  If this is still an issue and anyone cares feel free to open a new ticket under the monorepo.
