### ISSUE TITLE
Some resources not loaded in Safari

### ISSUE THREAD

**Issue by AliMD** [Polymer/polymer-cli#713]
### Description
Some resource not load in safari!
For example all images!
![screen shot 2017-05-03 at 4 38 58 pm](https://cloud.githubusercontent.com/assets/697913/25659969/5db43fc6-301f-11e7-929a-1ebff670c2b2.png)

### Versions & Environment
- Polymer CLI: v0.18.1
- node: v7.7.0
- Operating System: OSX 10.11.6
- Safari: 9.1.2 (11601.7.7)

**Comment by justinfagnani** [comment]
Maybe a polyserve issue...

**Comment by usergenic** [comment]
@AliMD the CLI is currently at version v1.3.0 - Can you verify whether this issue still exists for your use case and if it doesn't, can you link to reproduction of the issue (either github repo or live demo?)

**Comment by AliMD** [comment]
@usergenic problem not solved yet !

### Versions & Environment
- Polymer CLI: **v1.1.3**
- node: v7.7.0
- Operating System: OSX 10.11.6
- Safari: 9.1.2 (11601.7.7)

![screen shot 2017-07-08 at 4 22 51 pm](https://user-images.githubusercontent.com/697913/27985102-ef38771a-63f9-11e7-90c1-2d95cbd41ea3.png)

**Comment by usergenic** [comment]
@alimd check https://github.com/PTCSoft/lava-web/issues/13 - i am not reproducing the issue.  can you provide exact installation steps to repro?  please note the bower.json specifies versions which require a user-prompt resolution and I don't know what you choose.  I just changed to polymer ^2.0.0

**Comment by usergenic** [comment]
@AliMD full disclosure I'm on safari 10.1.1

**Comment by AliMD** [comment]
@usergenic thank you, its solved now and i'm sure it's not related to polymer version

**Comment by AliMD** [comment]
@justinfagnani Thank you. This issue solved for me! (May be after update the polymer-cli)

**Versions & Environment**
- Polymer CLI: **v1.3.1**
- node: v7.7.0
- Operating System: OSX 10.11.6
- Safari: 9.1.2 (11601.7.7)

I'm sure it's not related to polymer-cli itself becouse it's working after publish over nginx proxy.
https://lava.ptcvdep.net
