### ISSUE TITLE
Build Presets

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-cli#714]
Add build preset support so that common build configurations are easy to use without having to specify every individual build option.

## Benefits

- Easier to use from the command line for getting started, demos, documentation, npm scripts, etc.
- Encodes some commonly used, and recommended combinations of options
- Presets can be changed over time so that new versions of the CLI bring new optimizations that are automatically applied.

## Built-in Presets

- `es5-bundled`: all optimizations, compilation, bundling
- `es6-unbundled`: all optimizations, no compilation, bundling

## `--preset` Flag

`--preset={name}`

- Additional build flags override preset
- Can be specified multiple times for multiple presets
- Additional build flags are not allowed with multiple presets
- The name of preset is used as the name of the build

## `polymer.json`

```json
{
  "builds": [
    {
      "preset": "{name}"
    }
  ]
}
```

- Each build can have one preset
- Additional options override the preset
- The name of the build defaults to the name of the preset.

**Comment by FredKSchott** [comment]
Implemented at the config level here: https://github.com/Polymer/polymer-project-config/pull/17

Changes from Justin's original design:
- Support for 3 presets: `es5-bundled`, `es6-bundled`, `es6-unbundled`
- Only thing not implemented: "Can be specified multiple times for multiple presets"
  - This changes the current behavior where command line arguments define a single build that overrides any polymer.json configuration. Would require additional work and adds a potentially unexpected behavior for the user.
  - Not convinced this is necessary or even desired. A user should not be using CLI flags for repeatable production builds. If they are using CLI flags for dev, they can build one preset at a time or define polymer.json builds.

**Comment by Ado77** [comment]
Perhaps we could get an IE11 build as well? Basically es5-bundled without the service worker? Might help people who don't know... Or maybe suggest in the documentation to override the service worker setting?

Or maybe drop service-worker from the es5 preset...

Just a thought...

**Comment by FredKSchott** [comment]
Complete!

**Comment by JGSolutions** [comment]
@justinfagnani Sorry but I get javascript errors when I use the es6-bundled preset but the es6-unbundled is fine

JS Error:
Uncaught TypeError: Cannot read property '__proto__' of undefined
