### ISSUE TITLE
Unbundled build: insert link headers

### ISSUE THREAD

**Issue by garlicnation** [Polymer/polymer-cli#72]
The `main` file should have `<link rel="prefetch"` tags added for each file in the shared bundle and main app files.

Each additional `bundle` should have `<link rel="import"` tags added for each file that they transitively depend on that isn't already prefetched in `main`

**Comment by sorvell** [comment]
Actually the additional bundles should have `<link rel="import">`. We only want to use prefetch in the `main` entry point because it's got an async import.
