### ISSUE TITLE
insertPrefetchLinks need to be relative URLs for differential serving

### ISSUE THREAD

**Issue by aomarks** [Polymer/polymer-cli#744]
Currently prefetch links injected into the entrypoint are always absolute URLs. For differential serving, the entrypoint needs to use relative URLs, and rely upon a <base> tag to anchor it to the right build subdirectory.

Perhaps when basePath is set we can use relative URLs instead.

https://github.com/Polymer/polymer-cli/blob/master/src/build/prefetch.ts#L120

**Comment by usergenic** [comment]
Incidentally has happened in this polymer-build PR https://github.com/Polymer/polymer-build/pull/220

After that lands, we'll port CLI to use the build version which does use relative urls in the entrypoint doc for prefetch links when a base tag href is present.

**Comment by usergenic** [comment]
At the same time, the prefetch links inserted into fragments are always provided as relative urls now.

**Comment by usergenic** [comment]
Fixed in https://github.com/Polymer/polymer-cli/pull/756
