### ISSUE TITLE
service workers generated for differential serving don't properly cache entrypoint

### ISSUE THREAD

**Issue by graynorton** [Polymer/polymer-cli#747]
When we generate multiple builds for differential serving, we want the service worker generated for each build to cache the server's response to the dynamic entrypoint route (`/`), not the static, build-specific entrypoint file (default: `index.html`), since the static entrypoint will never be directly requested.

Currently, the opposite is true: the static entrypoint file is cached, but the response to the dynamic route is not.

The static entrypoint file is cached as a result of the lines here:

https://github.com/Polymer/polymer-build/blob/38f6ba2/src/service-worker.ts#L62
https://github.com/Polymer/polymer-build/blob/38f6ba2/src/service-worker.ts#L79

We should be able to get the desired result by:

- Changing the lines above to skip adding the entrypoint file when the build includes the `basePath` option
- Additionally, setting the following `sw-precache` options when the build includes the `basePath` option:
```
{
  "navigateFallback": "/",
  "dynamicUrlToDependencies": ["index.html"]
}
```
...where `index.html` is replaced with the actual entrypoint filename if the project specifies an alternative `entrypoint`.

This solution would build on the current approach of varying the generated service worker based on the presence of `basePath` in the build options. (Currently, when `basePath` is present we're using `sw-precache`'s `replacePrefix` option to prepend the build folder to each resource path.)

**Comment by graynorton** [comment]
It's arguable that this would be too heavy-handed. One alternative would be to avoid adding the entrypoint when `basePath` is present, but not to set the other `sw-precache` options (or to set them only if they are not already set in the developer-provided `sw-precache-config.js` file).

**Comment by aomarks** [comment]
@graynorton and I discussed a bit offline, and we think actually just setting navigateFallback to the relative entrypoint location should achieve the same goal.

BTW I also noticed that Shop has a custom sw-precache-config.js that was setting the navigateFallback to "/index.html" which is why things have been working when served from the root.
