### ISSUE TITLE
Init Element Inside of Existing App Project

### ISSUE THREAD

**Issue by hguiney** [Polymer/polymer-cli#763]
Currently, `polymer init element` creates not just a new element, but a new element *project*, replete with `bower_components/`, `demo/`, `test/`, `index.html`, and `bower.json` in the working directory. 

But if I am already inside an app project’s elements directory, such as Starter Kit’s `src/`, I do not want these directories to be created there. Instead I would want:
- the test case to go into the existing `../test/`
- `demo/` to not be generated as I don’t necessarily need to demo the element
- `bower_components/` to not be generated as it duplicates my existing dependencies from the app project
- `index.html` to not be generated as I already have an entrypoint
- `bower.json` to not be generated as it is not meant to be a redistributable element.

I can of course work around this by duplicating existing elements and doing a find-replace, or by deleting the extraneous files/directories, but it would be much easier if I could just generate a new bare element via the CLI.

**Comment by jsilvermist** [comment]
I believe the current plan for this is to add a `polymer gen` command to generate things such as elements or components.

Once Polymer 2.0 becomes more stable and the current priorities are taken care of, this should be revisited with a plan better element generation.

**Comment by FredKSchott** [comment]
Currently being tracked here: https://github.com/Polymer/polymer-cli/issues/470

Still some open questions to tackle, like the ones you brought up in your OP. Contributions always welcome!
