### ISSUE TITLE
Can't specify bundler options cli 1.1.0

### ISSUE THREAD

**Issue by Bubbit** [Polymer/polymer-cli#788]
### Description

The polymer-bundler has many options as also specified in the readme: https://github.com/Polymer/polymer-bundler#using-polymer-bundler-programmatically

Sadly due to the fact that the Polymer CLI is basing build settings on the polymer.json, we're limited to a small set, for the bundler the defaults.

This is due to: https://github.com/Polymer/polymer-cli/blob/master/src/build/build.ts#L62

I ran into this issue due to a Polymer app based on version 1.8.1 which has urls in templates: https://www.polymer-project.org/2.0/docs/upgrade#urls-in-templates
The paths no longer worked after the upgrade to the latest cli due to this breaking change in the polymer-bundler: https://github.com/Polymer/polymer-bundler/blob/master/CHANGELOG.md#200-pre12---2017-04-14 this means that the urls aren't rewritten by default, this can be fixed by setting rewriteUrlsInTemplates to true, but as said above this is not possible with the latest CLI.

### Versions & Environment

- Polymer CLI: 1.1.0
- node: 6.92
- Operating System: OSX / Linux

#### Steps to Reproduce

Try to pass bundler options to the polymer-cli in order to rewrite urls for a 1.8.1 Polymer app (haven't tested with 1.9)

#### Expected Results

Bundler options can be passed to the bundler

#### Actual Results

Bundler options can't be passed to the bundler

**Comment by arthurevans** [comment]
Seems like the backwards-compatible mode should be the default when working with 1.x projects, if that's possible.

**Comment by usergenic** [comment]
Have two PRs out to address this:
 - https://github.com/Polymer/polymer-project-config/pull/36
 - https://github.com/Polymer/polymer-cli/pull/806

**Comment by usergenic** [comment]
Closing as fixed since PRs are merged.  Next up: NPM releases.
