### ISSUE TITLE
polymer init freezes

### ISSUE THREAD

**Issue by lp177** [Polymer/polymer-cli#799]
Hi, I encounter some problems with the polymer-cli tool:

### Description
The commande `polymer init` freezes when I need to enter a name

### Versions & Environment
- Polymer CLI: 1.2.0
- node: 8.1.0
- Operating System: Linux Mint 18.1

#### Steps to Reproduce
`polymer init`
choose polymer-2-element or polymer-2-application

#### Actual Results
the question: ? Element name ([currentDirectoryName])
is display but can not be answered, I have wait long time, the process keep 101Mo of memory but dont use processor and nothing happen, I can't write or valide white enter, I can't leave with ctrl+c or ctr+d, i need to kill manualy the process for that, this happens in 100% of cases no one success with different levels of privileges, the debug mode don't signal any problem.

#### Workaround
When I do directly `polymer init polymer-2-element` that work but if i use just `polymer init` and choose polymer-2-element the bug appears

**Comment by ezekeal** [comment]
I'm getting the same:
* Polymer CLI: 1.2.0
* node: 8.1.0
* Ubuntu 16.04.2

**Comment by baocang** [comment]
I'm getting the same, but there is not a bug of polymer, node 8.1.1 fixed that.
FYI: nodejs hanges for `readline`: A change that broke `npm init` and other code which uses `readline` multiple times on the same input stream is reverted.

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.1.1

**Comment by lp177** [comment]
Indeed, it is well seen baocang, thanks.
