### ISSUE TITLE
ability to use babel presets when --compile flag is used

### ISSUE THREAD

**Issue by jay8t6** [Polymer/polymer-cli#807]
this might just end up being a question. Can we add babel presets through .babelrc? Would the cli pick it up when compiling the code? If not, can we add this option?

**Comment by justinfagnani** [comment]
I'm about to open an issue to have us explain our policy and rationale behind hard-coding the Babel transforms. It won't include allowing arbitrary presets, at least initially, so I'm going to close this issue for now.

**Comment by jogibear9988** [comment]
I need to change a option of the "babel-plugin-minify-mangle-names" plugin, I need to set the "eval" option. How am I supposed to do this? Can I use a babelrc?
