### ISSUE TITLE
Getting huge log during build because of "warning [multiple-doc-comments] - Scanned... has both HTML doc and JSDoc comments."

### ISSUE THREAD

**Issue by schlm3** [Polymer/polymer-cli#822]
### Description
While building our project using "polymer build", the log gets flooded with warnings like "warning [multiple-doc-comments] - Scanned... has both HTML doc and JSDoc comments.".
While the warning itself alone is not that much of a problem, it is very annoying that it prints out the whole code where this occurs, thus making reading the log VERY uncomfortable.
Actually, the whole buildpipeline produces 4400 lines of log, where the warnings for "multiple-doc-comments" makes 4000 lines of it.

I already tried if I can configure the build to ignore this using:
`"lint": {
    "rules": ["polymer-1"],
    "ignoreWarnings": ["multiple-doc-comments"]
  },`
in the polymer.json file, but this has had no effect.

### Versions & Environment

- Polymer CLI: 1.3.1 (same with 1.1.0)
- node: 6.11.0
- Operating System: Windows 10 - 1703

#### Steps to Reproduce

Take a file like the attached "example-behavior.html" and build it with polymer.
[example-behavior.zip](https://github.com/Polymer/polymer-cli/files/1141871/example-behavior.zip)

#### Expected Results

Just warn about the comments (if at all).
For us, the warning is pointless. Having HTML-Comments in HTML Code is ok. Having JS-Comment in JS-Code is OK. So what?

#### Actual Results

The log is flooded with the sourcecode and underlines.

**Comment by web-padawan** [comment]
The source issue is [this one](https://github.com/Polymer/polymer-analyzer/issues/674).

Example is the `paper-item` 1.x branch for which we get following warning:

```
Polymer.PaperItemBehaviorImpl = {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    hostAttributes: {
~~~~~~~~~~~~~~~~~~~~~
      role: 'option',
~~~~~~~~~~~~~~~~~~~~~
      tabindex: '0'
~~~~~~~~~~~~~~~~~~~
    }
~~~~~
  };
~~~~

vendor/paper-item/paper-item-behavior.html(22,2) warning [multiple-doc-comments] - ScannedBehavior has both HTML doc and JSDoc comments.
```

/cc @aomarks

**Comment by schlm3** [comment]
Thanks for the link. Seems to be the same issue.
