### ISSUE TITLE
Polymer build "Unable to resolve superclass .."

### ISSUE THREAD

**Issue by yairopro** [Polymer/polymer-cli#825]
### Description
Once my project is builded (using Polymer build of course), I've got a warning message saying "Unable to resolve superclass Web.Component" (Web.Component is a class I defined), even though it is clearly imported.

### Versions & Environment
**- Polymer CLI:** 1.3.1
**- node:** v7.9.0
**- Operating System:** Windows

#### Steps to Reproduce
1. Execute "Polymer build" 

#### Expected Results
No warnings.

#### Actual Results
Got a warning about an imported class unabled to resolve.
See attachement.

![sans titre](https://user-images.githubusercontent.com/8110568/28339063-91b63060-6c13-11e7-87b8-424464e3d86d.png)

**Comment by morbidick** [comment]
You have a typo there its improt instead of import.

**Comment by yairopro** [comment]
Oh sorry, my bad!
