### ISSUE TITLE
`--fragment` argument to `polymer build` is ignored

### ISSUE THREAD

**Issue by 6112** [Polymer/polymer-cli#829]
### Versions & Environment

- Polymer CLI: 1.3.1
- node: v6.9.5
- Operating System: Ubuntu

#### Steps to Reproduce

```bash
# from a clean directory
touch index.html
touch frag.html
polymer build -v --entrypoint index.html --fragment frag.html
```

#### Expected Results

The `--fragment` argument is respected, and `frag.html` is copied for `build/default/`.

#### Actual Results

Only `index.html` is placed in `build/default/`.

As you can see in the logs below, the `--fragment` argument is parsed correctly, it's just not passed correctly to the final configuration, which expects it to be called `fragments` (with an "s").

```
{ verbose: true,
  entrypoint: 'index.html',
  fragment: [ 'frag.html' ] }
debug:   final project configuration generated:
{ lint: undefined,
  root: '/opt/test-dir',
  entrypoint: '/opt/test-dir/index.html',
  fragments: [],
  extraDependencies: [ '/opt/test-dir/bower_components/webcomponentsjs/*.js' ],
  sources:
   [ '/opt/test-dir/src/**/*',
     '/opt/test-dir/index.html' ],
  allFragments: [ '/opt/test-dir/index.html' ] }
```

**Comment by 6112** [comment]
To fix this, we can just do the same thing we do with the `--extra-dependencies` flag, and add some code to rename it explicitly. Should be an easy fix.

https://github.com/Polymer/polymer-cli/blob/5d0645e00b450747b55619363113e93df71c3bf6/src/polymer-cli.ts#L60

**Comment by FredKSchott** [comment]
Fixed!
