### ISSUE TITLE
Add index.html as default polymer lint --input

### ISSUE THREAD

**Issue by abdonrd** [Polymer/polymer-cli#83]
When we runs `polymer lint`, we get:

![screen shot 2016-05-11 at 17 24 31](https://cloud.githubusercontent.com/assets/1007051/15186427/46b7716c-179d-11e6-968e-e79bb2d98441.png)

Like all projects have a `index.html`...
We can add `index.html` as default input file? Like `polymer lint -i index.html`:

![screen shot 2016-05-11 at 17 27 39](https://cloud.githubusercontent.com/assets/1007051/15186539/af885ab2-179d-11e6-9a2c-0c75e49e21f5.png)

**Comment by justinfagnani** [comment]
Fixed by #119
