### ISSUE TITLE
dynamic views in polymer-cli

### ISSUE THREAD

**Issue by ingjaguardo98** [Polymer/polymer-cli#833]
Could create my views dynamically? That is, using a button to create a new view. For what they mention in the link you have to create the content file. Could you create this new file using code?

https://www.polymer-project.org/2.0/start/toolbox/create-a-page

**Comment by web-padawan** [comment]
You can use `importHref` to load files dynamically, or use `lazy-imports` which does the same. Creating files on the fly is not supported, I wonder how do you imagine this should work?

**Comment by ingjaguardo98** [comment]
My problem really is that I want to be able to create new tabs, ie in the example there are 3, but I want to have a button to create a fourth or a fifth. What I did now is to create a button inside the app-drawer. Its function is within the definition of the my-app class and if it calls it correctly. Now the problem is that you create the option in the left menu and its content on the right side.
``

      <app-drawer id="drawer" slot="drawer" swipe-open="[[narrow]]">
        <app-toolbar>Foros Abiertos</app-toolbar>
        <iron-selector selected="[[page]]" attr-for-selected="name" class="drawer-list" role="navigation">
          <a name="view1" href="[[rootPath]]view1">View One</a>
          <a name="view2" href="[[rootPath]]view2">View Two</a>
          <a name="view3" href="[[rootPath]]view3">View Three</a>
        </iron-selector>
        <button on-click="newforum">NUEVO FORO</button> // THIS IS MY BUTTON
      </app-drawer>

**Comment by FredKSchott** [comment]
This question would be great for our Slack channel! https://polymer-slack.herokuapp.com/
