### ISSUE TITLE
polymer-cli init element creation and bower_components

### ISSUE THREAD

**Issue by shobson** [Polymer/polymer-cli#834]
Just had a question about using polymer-cli and the file structure it generates when creating an element. I've been creating multiple elements now and noticed that for each independent element it has its own bower_components folder. Is this the right way to go about working with multiple elements? Having each element contain their on dependencies? or is there a way they could ultimately share one common bower_components folder they can all reference in a parent folder for instance?

**Comment by shobson** [comment]
I've tried installing the bower_components as a sibling to my element folders/directories using .bowerrc file. Then tried changing the import paths to get to the polymer-element.html and other dependencies that sit inside the bower_components but it seems the url structure keeps everything contained within the element folder and cant seem to find any dependencies path and just 404's. 

Any help would be greatly appreciated!

**Comment by FredKSchott** [comment]
`polymer init` is meant to generate a standalone project/element, to be published to bower. If you're generating a new element inside of an existing project/application, this will be overkill. You'll have to do that manually (copy and paste is useful!) until a command like `polymer gen element` is created.

Hope that helps!
