### ISSUE TITLE
Errors on Edge

### ISSUE THREAD

**Issue by eugv86** [Polymer/polymer-cli#842]
Getting error on edge browser.  Loads the app-drawer, app-toolbar etc but not the iron-list thats in my-app element.

image of errors
![edge-errors](https://user-images.githubusercontent.com/6775099/29154024-fbeb8af8-7d56-11e7-82a2-0e2c9d721d52.PNG)

Attached a zip of project for reference 
[PolymerCarol.zip](https://github.com/Polymer/polymer-cli/files/1213635/PolymerCarol.zip)

**Comment by web-padawan** [comment]
Please follow [this issue](https://github.com/webcomponents/shadydom/issues/168), it is polyfill-related stuff.

**Comment by FredKSchott** [comment]
Moved to https://github.com/webcomponents/shadydom/issues/168
