### ISSUE TITLE
Proposal: "find usages" 

### ISSUE THREAD

**Issue by robrez** [Polymer/polymer-cli#857]
I was going to write a shellscript to grep through my project to "find usages" of a custom element. I thought it might be worth floating the idea around here. Maybe others have wanted to do something like this?

**Comment by robrez** [comment]
After a cup of coffee I realized atom's search feature is fine for what I was trying.  I'm not sure why I was determine to do it from the command-line this morning.. heh

Closing

**Comment by TimvdLippe** [comment]
For future reference: the Polymer analyzer can retrieve all usages of custom elements in a template, so you can use that directly :)
