### ISSUE TITLE
polymer test --npm not running proper directory

### ISSUE THREAD

**Issue by stramel** [Polymer/polymer-cli#858]
### Description

Running `polymer test --npm` on `PolymerElements/marked-element` attempts to run the tests against the URL `http://localhost:8081/components/marked-element/generated-index.html?npm=true&cli_browser_id=0` instead of the expected URL `http://localhost:8081/components/@polymer/marked-element/generated-index.html?npm=true&cli_browser_id=0`

### Versions & Environment

- Polymer CLI: 1.5.1
- node: 6.11.0
- Operating System: Linux

#### Steps to Reproduce

1. Clone https://github.com/stramel/marked-element#ms/3.0-preview
1. Run `npm i -g polymer-cli yarn && yarn`
1. Run `polymer test --npm`

#### Expected Results

The tests run (URL: http://localhost:8081/components/@polymer/marked-element/generated-index.html?npm=true&cli_browser_id=0)

#### Actual Results

The tests don't run (URL: http://localhost:8081/components/marked-element/generated-index.html?npm=true&cli_browser_id=0)

**Comment by FredKSchott** [comment]
This was fixed in the latest version of wct, we'll try to get a release out soon.

**Comment by justinfagnani** [comment]
@stramel @fks can this be closed?

**Comment by stramel** [comment]
Yes, this does appear to be fixed! Thank you guys!
