### ISSUE TITLE
Can't install polymer-cli globally with yarn ! 

### ISSUE THREAD

**Issue by CICCIOSGAMINO** [Polymer/polymer-cli#859]
### Description

Can't install polymer-cli globally with yarn ! 

I run the following command with different yarn versions but the result is always the same ! 

```bash
yarn global add polymer-cli
```

i get the error : 

error The package undefined@undefined requires a flat dependency graph. Add `"flat": true` to your package.json and try again.

So i've tried to set the "flat": true   mode in the global.json file of .config/yarn/global but it's a very long process install all the dependency in flat mode with all the packages resolutions, i don't think that's the good path to handle the global package.json ! 

### Versions & Environment

- Polymer CLI:  1.4.1  & 1.5.1
- node: 8.3.0 
- Operating System: Linux 4.4.0-92-generic #115-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Comment by tanmaymazumdar** [comment]
I also face the same problem, but when I run `npm i -g polymer-cli --unsafe-perm` it works for me. Try this command in your machine, hopefully it'll work.

**Comment by tanmaymazumdar** [comment]
If it still doesn't work then go to [#issue/832](https://github.com/Polymer/polymer-cli/issues/832). They already had the same issue of installing the polymer-cli globally.

**Comment by justinfagnani** [comment]
@usergenic did we add a flat dependency in the graph via WCT maybe?

**Comment by justinfagnani** [comment]
Root cause here: https://github.com/Polymer/web-component-tester/issues/598

**Comment by JosefJezek** [comment]
Here is temporaly solution `sudo yarn global add https://github.com/StartPolymer/polymer-cli#JosefJezek-patch-1`

https://github.com/StartPolymer/polymer-cli/commit/dd86959edd7124e7638447ca9a128cc9b3c836d7

**Comment by usergenic** [comment]
polymer-cli 1.5.2 published 🎉

fixed.

**Comment by usergenic** [comment]
Please re-open if you're still seeing this issue with yarn add.
