### ISSUE TITLE
Bundled build fails silently when html imports are not found

### ISSUE THREAD

**Issue by kuza55** [Polymer/polymer-cli#862]
This seems to be a known issue in the community, but when a html import doesn't resolve, bundled builds fail silently.

I only figured this out due to a helpful comment on https://github.com/Polymer/polymer-cli/issues/821

Failing silently is a pretty ridiculous.

**Comment by FredKSchott** [comment]
Agreed, this is pretty bad. 

This bug is available for anyone to jump in, happy to help point in the right direction.

**Comment by FredKSchott** [comment]
Closing as duplicate  of #849
