### ISSUE TITLE
Fail to find Dependencies

### ISSUE THREAD

**Issue by JGSolutions** [Polymer/polymer-cli#864]
### Description
When trying to update polymer-cli to 1.5.2 can't find some registry urls

### Versions & Environment
- Polymer CLI: 1.5.2
- node: 6.10
- Operating System: Mac

#### Steps to Reproduce
just run on cli: npm install -g polymer-cli

#### Actual Results
`046 http fetch GET 404 https://registry.npmjs.org/@webcomponents%2fwebcomponentsjs 177ms
2047 silly fetchPackageMetaData error for @webcomponents/webcomponentsjs@^1.0.7 404 Not Found: @webcomponents/webcomponentsjs@^1.0.7
2048 http fetch GET 404 https://registry.npmjs.org/@polymer%2ftest-fixture 247ms
2049 silly fetchPackageMetaData error for @polymer/test-fixture@^0.0.3 404 Not Found: @polymer/test-fixture@^0.0.3
2050 http fetch GET 404 https://registry.npmjs.org/@polymer%2fsinonjs 260ms
2051 silly fetchPackageMetaData error for @polymer/sinonjs@^1.14.1 404 Not Found: @polymer/sinonjs@^1.14.1
2052 verbose stack Error: 404 Not Found: @webcomponents/webcomponentsjs@^1.0.7
2052 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
2052 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2052 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
2052 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
2052 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
2052 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
2052 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
2052 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
2052 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
2052 verbose stack     at runCallback (timers.js:666:20)
2052 verbose stack     at tryOnImmediate (timers.js:639:5)
2052 verbose stack     at processImmediate [as _immediateCallback] (timers.js:611:5)
2053 verbose cwd /Users/jerrygag/Desktop/esl.projects/restaurant/chowdashi
2054 verbose Darwin 16.6.0
2055 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "polymer-cli@1.4.1"
2056 verbose node v6.10.2
2057 verbose npm  v5.3.0
2058 error code E404
2059 error 404 Not Found: @webcomponents/webcomponentsjs@^1.0.7`

**Comment by justinfagnani** [comment]
This sounds like an npm problem. Are you able to install other packages? WHat version of npm do you have?

**Comment by JGSolutions** [comment]
Thanks for the quick reply.

Yes it does seem to be an npm problem. I actually tried installing these separately on cli and getting 404 not found.

npm i -g @polymer/test-fixture@0.0.3
npm i -g @webcomponents/webcomponentsjs@1.0.7

Tried also in yarn and get the same response.

NPM version 5.3.0

Thanks again :)

**Comment by justinfagnani** [comment]
Are you behind a firewall? Does npm work on a different network?

**Comment by JGSolutions** [comment]
Looks like an issue with my mac....I tried on my windows machine same network and everything works fine

You can close this issue. My mistake.

**Comment by baocang** [comment]
@JGSolutions  you can close the issue by yourself.
And when i get the error, I setup my mac with proxy or VPN. it can works well.

**Comment by JGSolutions** [comment]
Yes I will thx

**Comment by JGSolutions** [comment]
So i tried:

npm i -g webcomponentsjs and someother packages out of curiosity

npm i -g @webcomponents/webcomponentsjs@1.0.7 doesn't work. What can it be that is blocking?

**Comment by baocang** [comment]
@JGSolutions it works for me.
`npm install @webcomponents/webcomponentsjs@1.0.7`
 or
 `npm install @webcomponents/webcomponentsjs@^1.0.7 `

**Comment by baocang** [comment]
@JGSolutions  with the `-g` option still works. Maybe this your network issue.

**Comment by JGSolutions** [comment]
@baocang 
How did you setup a proxy on your mac?

**Comment by JGSolutions** [comment]
I decided to reinstall node.js....works now!

**Comment by baocang** [comment]
@JGSolutions I use https://github.com/getlantern/lantern
