### ISSUE TITLE
Polymer 3.0 init templates

### ISSUE THREAD

**Issue by vilarfg** [Polymer/polymer-cli#865]
### Versions & Environment

- Polymer CLI: 1..5.2
- node: 6.11.1
- Operating System: Ubuntu 16.04

#### Steps to Reproduce

1. List generators: `polymer init`

#### Expected Results
It'd be great to see `polymer-3-element` in the list. I am impatient, I know... 

#### Actual Results
no such list item.

**Comment by justinfagnani** [comment]
We're working on all kind of things related to 3.0, but it's still very, very early. We won't have templates for a little bit. We recommend using 2.0 for now.

**Comment by vilarfg** [comment]
I understand, I only opened this issue because I was about to PR this [branch](https://github.com/vilarfg/polymer-cli/tree/feature/polymer-3-element) on my fork.

**Comment by vilarfg** [comment]
This new generator produces sensible output, but it doesn't pass any of the current tests (testing it right would be very difficult since it depends on many other changes in the tooling and also we need to wait for Chrome 61).
I was going to suggest you create a new branch on polymer-cli so that I could PR against it. Doing it against master would be sheer madness.
cheers

**Comment by bicknellr** [comment]
https://github.com/Polymer/tools/pull/115 adds a Polymer 3.x element template - I don't think it's in any type of release yet.
https://github.com/Polymer/tools/pull/134 will add the (very minimal) Polymer 3.x application template.

**Comment by bicknellr** [comment]
Closing: those two templates are now in polymer-cli@1.7.0 .
