### ISSUE TITLE
Polymer build --js-compile still has ES2015 code "new Set()"

### ISSUE THREAD

**Issue by hekod777** [Polymer/polymer-cli#869]
Hi

I was trying to build my polymer 2.0 app ES5 compatible so that phantomJS can prerender it (hopefully).

but when I tried the built app on prerender, it gives me this error

```
ReferenceError: Can't find variable: Set

  http://localhost:1337/bower_components/webcomponentsjs/webcomponents-lite.js:145
  http://localhost:1337/bower_components/webcomponentsjs/webcomponents-lite.js:190
```

the reason seems to be 

**the latest version of PhantomJS does not support ES2015 Set.**

I believe `polymer build --js-compile` is supposed to convert `Set` to be ES5 compatible right?

I'd like to know for the moment being, is there any workaround for this issue?

Thanks!

**Comment by justinfagnani** [comment]
`new Set()` isn't ES2015 syntax, so it won't be compiled out. We also don't compile the polyfills because they're already compiled. We've tested that the way we use Set is supported in all of our supported browsers. Has this caused an error for you?

**Comment by baocang** [comment]
@hekod777 just for this issue, maybe you needs some polyfill such like [core-js](https://github.com/zloirock/core-js), I just little curious, Can polymer works with `PhantomJS `?

I'm now focus on Polymer, so I have interest anything about polymer.

**Comment by baocang** [comment]
In my company, we use [electron](https://electron.atom.io/), but not `PhantomJS`.

**Comment by web-padawan** [comment]
@hekod777 PhantomJS is no longer supported, consider using headless Chrome instead.

**Comment by baocang** [comment]
@web-padawan I hear the headless chrome first time, but it's sounds very good, I have a little question here: can I use it without installation chrome? Some my customer has no right to install anything on they company's computer.

**Comment by web-padawan** [comment]
@baocang as mentioned in [this article](https://developers.google.com/web/updates/2017/04/headless-chrome), headless Chrome is shipped with Chrome 59 for Linux / Mac and starting from 60 also for Windows. There is a [Docker container](https://github.com/yukinying/chrome-headless-browser-docker) available.

**Comment by hekod777** [comment]
Thank you for the advise.

actually I have tested out rendertron quite a bit and even fixed a bug in the middleware to make it work on a polymer SPA.

but we are currently using prerender. and we have to get this SEO thing work for PHP as well. thats why I am trying to see if I can get web component work with phantomJS. 

I guess it's just a dead end.

**Comment by baocang** [comment]
@web-padawan thx, seems  good, days after I'll take a while to try it.

**Comment by web-padawan** [comment]
@hekod777 the possible future of Phantom JS is here (an empty repo right now): https://github.com/Vitallium/phantomium

AFAIK, headless Chrome has a special mode called "headless lib" which you can build yourself with minimum dependencies, without installing whole Chrome.

Another option might be SlimerJS (similar to Phantom but using Gecko instead of WebKit): https://github.com/laurentj/slimerjs

**Comment by justinfagnani** [comment]
@hekod777 while PhaontomJS isn't officially supported, using a Set polyfill should get you past this one problem. Like @baocang mentioned, core-js is a good option.

I would recommend moving off of PhantomJS and to headless Chrome if you can. This might be one of the easier ways to do it: https://github.com/GoogleChrome/puppeteer

**Comment by justinfagnani** [comment]
I'm going to close this for now. If something new comes up, feel free to reopen. Good luck!

**Comment by phani1kumar** [comment]
@justinfagnani does this mean, if I test my polymer SPA in headless chrome, I can see the page in "Fetch as Google" -> Fetch and Render? Currently my site "https://giftgenie.ai" is rendering as blank page. And, there is no clue what is going wrong here. 

After going through some Google search results, I found that google search console / google crawl robot are using PhantomJS for crawling/ rendering the page. 

Are both Google Search Console / Cwarler also using Headless chrome? SEO ranking is becoming a pain for SPA / PWA applications!

**Comment by web-padawan** [comment]
@phani1kumar the Googlebot uses Chrome 41, and the Polymer library itself is tested against it, see the list of browsers [here](https://github.com/Polymer/polymer/blob/master/util/travis-sauce-test.sh#L12).

**Comment by phani1kumar** [comment]
Thank you for your answer @web-padawan . When I checked my app in Chrome 41, I get error with webcomponents-loader.js. [Here is the screenshot from browserling](https://drive.google.com/open?id=11YqqHWzNeP8N5vFSEKU1f5PUDzVUFCPa). Seems like only plain Polymer is tested and not the polyfills!
