### ISSUE TITLE
Don't force trailing slash on basePath

### ISSUE THREAD

**Issue by jab** [Polymer/polymer-cli#873]
Currently if a `basePath` is specified with no trailing slash, one is [forcibly appended](https://github.com/Polymer/polymer-cli/blob/8f4e81cdb991bc0cdbe52652a92e57b53d19f3c0/src/build/build.ts#L120-L122).

Believe it or not, some static web servers don't automatically serve a contained index.html when a directory path is requested. In this case, setting `basePath` to e.g. `/index.html` would allow a Polymer SPA with `<app-location use-hash-as-path>` to correctly address other pages. However, forcing the trailing slash on the `basePath` breaks this.

Here is a live example:
https://s3-ap-northeast-1.amazonaws.com/uproxy.org/index.html
Note the base tag of `<base href="/uproxy.org/index.html">`. I manually removed the trailing slash that `polymer build` added to get this to work.

Background:
I am on Jigsaw's anticensorship team. We are experimenting with mirroring a Polymer SPA to Amazon S3. Rather than address an S3 site like https://bucketid.s3.amazonaws.com, which is very vulnerable to DNS-poisoning based censorship, you can instead address it like https://s3.amazonaws.com/bucketid/index.html. This forces censors to poison the shared s3.amazonaws.com domain, which would cause a lot more collateral damage than they can often tolerate. Unfortunately though, with the bucket-in-path addressing scheme, S3 does not automatically serve index.html, so it must be included explicitly in the path.

Rather than "auto-correcting" a configured `basePath` to always have a trailing slash, would you consider just logging a warning or something instead? Allowing a `basePath` like `/<bucketid>/index.html` would support a critical use case for access to information and free expression for vulnerable users all over the world.

**Comment by jab** [comment]
PR for this in #874 in case it's helpful!

**Comment by jab** [comment]
Thinking about this further, to be able to reference a static subresource that's located alongside index.html from within a template (e.g. `<img src="/basePath/foo.png">`, as opposed to an SPA/"virtual" page like `<a href="/basePath/index.html#/page">`) , `basePath` actually does have to be the directory containing index.html. Writing a helper `urlForPage(..)` function that includes the "index.html#/" in page URLs seems like the proper approach here, so I'm going with that for now. Closing this and #874, but please still chime in if you have time and any thoughts to share. Thanks!

**Comment by justinfagnani** [comment]
Thanks for the explanation for closing, that's helpful.

**Comment by jsilvermist** [comment]
This was also a blocker for some techniques I was trying to get prebuilt demo pages working easily.
