### ISSUE TITLE
Polymer-2-application sample has HTTP404 errors when Edge dev tools are open

### ISSUE THREAD

**Issue by johannesh2** [Polymer/polymer-cli#883]
### Description

After opening Edge dev tools on vanilla polymer-2-application sample served with polymer serve, there are bunch of HTTP404 errors in console.

### Versions & Environment
- Polymer CLI: 1.5.4
- node: v6.10.3
- Operating System: Win 10. Microsoft EdgeHTML 15.15063. Microsoft Edge 40.15063.0.0

├─┬ polymer#2.1.0
│ ├── shadycss#1.0.6
│ └── webcomponentsjs#1.0.12
├─┬ web-component-tester#6.2.0
│ ├── accessibility-developer-tools#2.12.0
│ ├── async#1.5.2 (latest is 2.5.0)
│ ├── chai#3.5.0 (latest is 4.1.2)
│ ├── lodash#3.10.1 (3.11.0-npm-packages available, latest is 4.17.4)
│ ├── mocha#3.5.3
│ ├── sinon-chai#2.13.0
│ ├── sinonjs#1.17.1
│ ├── stacky#1.3.2
│ └── test-fixture#3.0.0
└── webcomponentsjs#1.0.12

#### Steps to Reproduce

1. `polymer init polymer-2-application`
2. `bower install`
3. `polymer serve`
4. Open served app with Edge
5. Open Edge dev tools. 

#### Expected Results
No errors

#### Actual Results
51 errors in console

`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/scoping-shim.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/custom-style-interface.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/document-watcher.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/style-cache.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/style-properties.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/style-info.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/Patch/Interface/ChildNode.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/Utilities.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/style-transformer.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/css-parse.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/CustomElementState.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/Patch/Element.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/Patch/Node.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/Patch/Document.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/Patch/Interface/ParentNode.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/Patch/HTMLElement.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/CustomElementRegistry.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/attach-shadow.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/DocumentConstructionObserver.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/logical-tree.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/webcomponentsjs/webcomponents-hi-sd-ce-index.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/Deferred.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/CustomElementInternals.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/observe-changes.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/utils.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/innerHTML.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/native-tree.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/patch-accessors.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/flush.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/patch-events.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/style-util.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/style-settings.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/patch-builtins.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/array-splice.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/apply-shim-utils.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/html-imports/src/html-imports.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/native-methods.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/shadydom.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadydom/src/logical-mutation.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/document-wait.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/custom-elements.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/AlreadyConstructedMarker.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/style-placeholder.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/Patch/Native.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/common-regex.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/template-map.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/entrypoints/scoping-shim.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/src/post-polyfill.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/src/unresolved.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/custom-elements/src/Patch/DocumentFragment.js`
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`
`(XHR)GET - http://127.0.0.1:8000/bower_components/node_modules/@webcomponents/shadycss/src/common-utils.js`

**Comment by baocang** [comment]
This is the issue of javascript source map. that where no peerDependents in `webcomponentsjs`, you can install such as shadycss、custom-elements by yourself or move some dependents of `webcomponentsjs` to peerDependents.

**Comment by vlukashov** [comment]
Here is a PR addressing this issue: https://github.com/webcomponents/webcomponentsjs/pull/858

**Comment by TimvdLippe** [comment]
Closing this per https://github.com/webcomponents/webcomponentsjs/issues/869#issuecomment-397883961
