### ISSUE TITLE
Object spread/rest syntax not supported

### ISSUE THREAD

**Issue by kaste** [Polymer/polymer-cli#888]
Unpacking an object like 

```
    let {name, ...rest} = {name: 'Kevin', age: 29}
```
 breaks `polymer build`

```
> polymer build
info:    Clearing build\ directory...
info:    (default) Building...


    let {name, ...rest} = {name: 'Kevin', age: 29}
               ~

src/ptest-app/ptest-app.html(14,15) error [parse-error] - Unexpected token ...
```
This relatively new syntax is supported in Chrome and Firefox so babel/transpiling should not be necessary.

**Comment by barnomics** [comment]
I'm seeing the same issue.  Isn't spread an ES6 feature?  Wonder why it has trouble compiling down

**Comment by davidmaxwaterman** [comment]
just for reference:
https://babeljs.io/docs/plugins/transform-object-rest-spread/

**Comment by justinfagnani** [comment]
Object spread isn't ES2015, it's still stage 3. But it is implemented in two released browsers: Chrome and Firefox, and in Safari TP.

We really haven't formalized our JS language feature support, and we should, but it seems likely to me that the threshold for including in the transforms would be implementation in two browsers. I think we can go ahead and enable this. PRs welcome.

**Comment by AliMD** [comment]
@justinfagnani Any news?
Can we use some nightly build with spread support to prevent refactor our code?

**Comment by justinfagnani** [comment]
This is a polymer-build issue, and should be fixed along with https://github.com/Polymer/polymer-build/issues/277
