### ISSUE TITLE
Integration tests fail when updating to wct 6.4.0

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-cli#927]
It looks like it runs tests fine, but the `polymer test` invocation doesn't terminate afterwards. package.json and yarn.lock will protect us for the time being, but it needs investigation.

**Comment by limonte** [comment]
Same issue here:

![](https://i.imgur.com/mwJEMss.png)

**Comment by rictic** [comment]
Related: https://github.com/Polymer/web-component-tester/issues/648

This should be fixed with a fresh install. See that issue for details (somewhat subtle version constraints there)
