### ISSUE TITLE
CLI doesn't seem to pick up npm and moduleResolution options from polymer.json

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer-cli#978]
### Description

Using Polymer CLI 1.7.0-pre.2

Running this project:

https://github.com/PolymerLabs/start-polymer3

With `polymer serve` (no command line args), the page fails to load correctly, even though the 
"npm" and "nodeResolution" flags are specified in polymer.json.

With `polymer serve --npm --module-resolution=node`, it works fine.

**Comment by JohnGorter** [comment]
polymer serve --npm --module-resolution=node in the directory where the node_modules are located still gives me the same error...
