### ISSUE TITLE
`polymer serve` should only serve app shell if 404'ing URL does not end with file extension

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer-cli#98]
The current simple logic to serve the app shell (index.html) for pretty URL's by sending any 404 to the app shell should be tightened a little to avoid really confusing errors:

Use case: if you import an HTML Import that you haven't properly bower installed, you end up getting the `index.html` which will be evaluated, and can lead to strange errors when the scripts in index.html run again.

Solution: We should only serve the app shell for URL's that don't end in a file extension like `.html` or `.jpg`, and instead send a 404 for those URL's.  This still allows `http://localhost:8080/home` and `http://localhost:8080/detail/123456` to still serve the app shell.

**Comment by justinfagnani** [comment]
Fixed by #105
