### ISSUE TITLE
1.7.0-pre.3 regression: not injecting babelHelpers

### ISSUE THREAD

**Issue by web-padawan** [Polymer/polymer-cli#987]
### Description
When serving demo and tests in IE11, the error appears:

```
SCRIPT5009: 'babelHelpers' is undefined
```
This causes any tests to fail. Same happens with the Safari 9.3

### Versions & Environment
- Polymer CLI: 1.7.0-pre.3
- node: v8.9.4
- Operating System: Mac OS

#### Steps to Reproduce

1. Fork the [vaadin-button](https://github.com/vaadin/vaadin-button) repository and clone it locally
2. When in the vaadin-button directory, run `bower install`
3. Run `npm i -g polymer-cli@next`
4. Run `polymer serve`
5. Open IE11 and go to http://127.0.0.1:8081/components/vaadin-button/test
6. See the errors in the console

#### Expected Results
Babel helpers injected, no errors, tests passing (as with `polymer-cli` 1.6.0).

#### Actual Results
No babel helpers, errors in the console:
![screen shot 2018-04-04 at 15 18 22](https://user-images.githubusercontent.com/10589913/38307477-8c420c64-381c-11e8-9455-fb615febc6d3.png)

**Comment by aomarks** [comment]
Should be fixed in polymer-cli `3.0.0-pre.6` which was just published (via https://github.com/Polymer/tools/pull/78).

**Comment by aomarks** [comment]
Actually don't think this was fixed by `pre.6`. Should have another release that brings in the update correctly.

**Comment by web-padawan** [comment]
Yep, I also can confirm this. Thank you for all the work you're guys doing!

**Comment by aomarks** [comment]
polymer-cli `1.7.0-pre.7` published, hopefully has picked up this fix. Sorry for the slow rollout, we're switching to a new repo and hit some issues with the new release process.

**Comment by web-padawan** [comment]
@aomarks after installing the new version, I'm getting the following error:
```sh
+ polymer-cli@1.7.0-pre.7
added 1672 packages and updated 3 packages in 53.308s

8:54:26 sergey kulikov ~/vaadin/vaadin-themable-mixin p3-preview-bare ⚡
$ polymer serve --npm --module-resolution=node
module.js:549
    throw err;
    ^

Error: Cannot find module '../lib/run'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/bin/polymer.js:40:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by aomarks** [comment]
Wow, that one was published unbuilt. It's too late here to do another release, will have to fix tomorrow. Again, sorry for the chaos.

**Comment by web-padawan** [comment]
@aomarks no problem at all. We realize that the monorepo migration is a huge work, and we appreciate all the feedback and support from the Tools team.

**Comment by aomarks** [comment]
Let's try again with 1.7.0-pre.9

**Comment by web-padawan** [comment]
I can confirm it's working now. Thanks!
